/*
 * ProtocolDefine.h
 *
 *  Created on: 2015-8-21
 *      Author: lipman
 */

#ifndef PROTOCOLDEFINE_H_
#define PROTOCOLDEFINE_H_

#include "Kernel.h"

#define MAGIC_HEADER 26284
#define MAX_PROTOCOL_BODY_SIZE 0xF000
#define PACKET_HEADER_SIZE 22
#define MAX_PACKET_SIZE (PACKET_HEADER_SIZE + MAX_PROTOCOL_BODY_SIZE + sizeof(byte))

/*-----------------内部进程间通讯------------------*/
#define PROTOCOL_TYPE_ACCESS_TRANSFER 1
#define PROTOCOL_TYPE_ACCESS_ANSWER 2
#define PROTOCOL_TYPE_HEARBEAT 3
#define PROTOCOL_TYPE_COFFLINE 4
#define PROTOCOL_TYPE_LOFFLINE 5
#define PROTOCOL_TYPE_CHANGE_LOGIN 6
#define PROTOCOL_TYPE_KICK_CROSS 7
#define PROTOCOL_TYPE_LOGIN_TRANSFER 8
#define PROTOCOL_TYPE_BATTLE_TRANSFER 9
#define PROTOCOL_TYPE_BATTLE_ANSWER 10
#define PROTOCOL_TYPE_ASYNC_DB 11
#define PROTOCOL_TYPE_SECOND_TIMER 12
#define PROTOCOL_TYPE_STATE_TRANSFER 13
#define PROTOCOL_TYPE_STATE_ANSWER 14
#define PROTOCOL_TYPE_ASYNC_DB_TRANSFER 15

#define PROTOCOL_TYPE_TRANSIT_TRANSFER 21
#define PROTOCOL_TYPE_TRANSIT_ANSWER 22
#define PROTOCOL_TYPE_SERVER_ASYNC 23
#define PROTOCOL_TYPE_ALL_SERVER_TRANSFER 24
#define PROTOCOL_TYPE_ALL_SERVER_ANSWER 25

#define PROTOCOL_TYPE_TEST 100
#define PROTOCOL_TYPE_ADMIN 101						// 管理系统
#define PROTOCOL_TYPE_ACCESS_ADMIN 102

/*-----------------逻辑相关协议------------------*/
#define PROTOCOL_CMD_LOGIC 0
#define PROTOCOL_SUBCMD_HEART_BEAT 1				//心跳

#define PROTOCOL_RSP_SUBCMD_SERVER_TIME 1			//服务器时间
#define PROTOCOL_RSP_SUBCMD_SYSTEM_TIPS 2			//语言包提示
/*-----------------登陆相关协议------------------*/
#define PROTOCOL_CMD_LOGIN 1
#define PROTOCOL_SUBCMD_LOGIN 1
#define PROTOCOL_SUBCMD_OFFLINE 2
#define PROTOCOL_RSP_SUBCMD_LOGIN 1
/*-----------------装备相关协议------------------*/
#define PROTOCOL_CMD_EQUIPMENT 2
#define PROTOCOL_SUBCMD_EQUIPMENTLIST 1
#define PROTOCOL_SUBCMD_BAGLIST 2
#define PROTOCOL_SUBCMD_WEAR 3
#define PROTOCOL_SUBCMD_UNWEAR 4
#define PROTOCOL_SUBCMD_BAG_ADD 5
#define PROTOCOL_SUBCMD_BAG_REMOVE 6
#define PROTOCOL_SUBCMD_COUNT_CHANGE 7
#define PROTOCOL_SUBCMD_STRENGTH 8
#define PROTOCOL_SUBCMD_STONE_MOUNT 9
#define PROTOCOL_SUBCMD_STONE_UNMOUNT 10
#define PROTOCOL_SUBCMD_STONE_UNLOCK 11
#define PROTOCOL_SUBCMD_STONE_LOCK_QUERY 12
#define PROTOCOL_SUBCMD_STRENGTH_QUERY 13
#define PROTOCOL_SUBCMD_STONE_COMPOSE 14			// 晶石合成
#define PROTOCOL_SUBCMD_EQUIP_SELL 15				// 装备卖出
#define PROTOCOL_SUBCMD_BAG_UNLOCK 16				// 背包格子解锁
#define PROTOCOL_SUBCMD_SHOP_BUY 17					// 商店购买
#define PROTOCOL_SUBCMD_EQUIPMENT_USE 18			// 使用装备
#define PROTOCOL_SUBCMD_EQUIP_SELL_ALL 19			// 装备一键卖出
#define PROTOCOL_SUBCMD_STONE_REPLACE 20			// 晶石替换
#define PROTOCOL_SUBCMD_STONE_UPGRADE 21			// 晶石升级
#define PROTOCOL_SUBCMD_QUERY_ONE_EQUIPMENT 22		// 查询一个装备
#define PROTOCOL_SUBCMD_EQUIPMENT_SMELT 23			// 装备洗炼
#define PROTOCOL_SUBCMD_QUERY_BUILDING_LOCK 24		// 建筑宝石
#define PROTOCOL_SUBCMD_BUILDING_UNLOCK 25			// 建筑宝石
#define PROTOCOL_SUBCMD_BUILDING_STONE_MOUNT 26		// 建筑宝石
#define PROTOCOL_SUBCMD_BUILDING_STONE_UNMOUNT 27	// 建筑宝石
#define PROTOCOL_SUBCMD_BUILDING_STONE_REPLACE 28	// 晶石替换
#define PROTOCOL_SUBCMD_BUILDING_STONE_UPGRADE 29	// 晶石替换
#define PROTOCOL_SUBCMD_EQUIP_SET_BUILD 30			// 套装打造
#define PROTOCOL_SUBCMD_EQUIP_SET_UPGRADE 31		// 套装升级
#define PROTOCOL_SUBCMD_EQUIP_SET_CHANGE 32			// 套装制式转换
#define PROTOCOL_SUBCMD_EQUIP_OPEN_RED_BAG 33		// 开红包成功
#define PROTOCOL_SUBCMD_EQUIP_SMELT_LOCK_TIMES 34	//
#define PROTOCOL_SUBCMD_SOME_EQUIP_INFO 35			// 多个物品信息
#define PROTOCOL_SUBCMD_EQUIP_UPGRADE 36			// 装备突破
#define PROTOCOL_SUBCMD_EQUIP_GIFT_REWARD 37		// 随机包打开结果
#define PROTOCOL_SUBCMD_GEM_POINT_INFO 38			// 宝石镶嵌信息
#define PROTOCOL_SUBCMD_GEM_POINT 39				// 宝石镶嵌
#define PROTOCOL_SUBCMD_GEM_COMBINE 40				// 宝石合成
#define PROTOCOL_SUBCMD_EQUIP_COMBINE 41			// 碎片合成

// 装备回包返回值
#define PROTOCOL_RET_EQUIP_SUCCESS 0 			// 操作成功
#define PROTOCOL_RET_EQUIP_FAIL 1 				// 操作失败
#define PROTOCOL_RET_EQUIP_PACKET_ERROR 2 		// 收包数据有错

/*-----------------英雄相关协议------------------*/
#define PROTOCOL_CMD_HERO 3
#define PROTOCOL_SUBCMD_HEROLIST 1							//
#define PROTOCOL_SUBCMD_HERO_TIMER_QUERY 2					//
#define PROTOCOL_SUBCMD_HERO_RECOVE_OVER 3					//
#define PROTOCOL_SUBCMD_HERO_TRAIN 4						//
#define PROTOCOL_SUBCMD_HERO_INFO 5							//
#define PROTOCOL_SUBCMD_HERO_TRAIN_OVER 6					// 英雄训练完成
#define PROTOCOL_SUBCMD_HERO_SET_STATE 7			 		// 设置英雄出战状态
#define PROTOCOL_SUBCMD_HERO_STATE_LIST_QUERY 8				// 英雄状态列表查询
#define PROTOCOL_SUBCMD_HERO_PROP_CHANGE 9 					// 英雄属性变化
#define PROTOCOL_SUBCMD_HERO_FULL_HP 10 					// 英雄一键恢复
#define PROTOCOL_SUBCMD_HERO_ADD_ONE 11 					// 招募一个英雄
#define PROTOCOL_SUBCMD_HERO_REFRESH 12 					// 英雄刷新
#define PROTOCOL_SUBCMD_HERO_AUTO_REFRESH 13 				// 英雄刷新一键十次
#define PROTOCOL_SUBCMD_HERO_CULTURE 14 					// 英雄培养
#define PROTOCOL_SUBCMD_HERO_QUERY_PROP_CHANGE_BY_POINT 15	// 潜能提升属性
#define PROTOCOL_SUBCMD_HERO_QUERY_CREDIT_TRADE_LIST 16		// 查询积分兑换列表
#define PROTOCOL_SUBCMD_HERO_REFRESH_CREDIT_TRADE_LIST 17	// 刷新积分兑换列表
#define PROTOCOL_SUBCMD_HERO_CREDIT_TRADE 18				// 积分兑换物品
#define PROTOCOL_SUBCMD_HERO_CAPTIVE 19						// 俘虏将领
#define PROTOCOL_SUBCMD_HERO_RESCUE 20						// 营救将领
#define PROTOCOL_SUBCMD_HERO_QUERY_CAPTIVE 21				// 查询被俘虏将领
#define PROTOCOL_SUBCMD_HERO_UP_STAR 22 					// 英雄升星
#define PROTOCOL_SUBCMD_HERO_PAY_TO_FULL_HP 23 				// 英雄花钱回血
#define PROTOCOL_SUBCMD_HERO_SHIELD_ARMOR_REINFORCE 24 		// 金盾铁甲加固
#define PROTOCOL_SUBCMD_HERO_FIRED 25						// 解雇将领
#define PROTOCOL_SUBCMD_HERO_BUDDY 26						// 上阵
#define PROTOCOL_SUBCMD_HERO_ENERGY_COST 27					// 精力消耗
#define PROTOCOL_SUBCMD_HERO_ENERGY_ADD 28					// 精力购买
#define PROTOCOL_SUBCMD_HERO_UNLOCK 29						// 解锁

#define PROTOCOL_RSP_SUBCMD_HEROLIST 1
#define PROTOCOL_RSP_SUBCMD_HERO_TIMER_QUERY 2
#define PROTOCOL_RSP_SUBCMD_HERO_RECOVE_OVER 3
#define PROTOCOL_RSP_SUBCMD_HERO_TRAIN 4
#define PROTOCOL_RSP_SUBCMD_HERO_INFO 5
#define PROTOCOL_RSP_SUBCMD_HERO_TRAIN_OVER 6 				// 英雄训练完成回包
#define PROTOCOL_RSP_SUBCMD_HERO_SET_STATE 7 				// 设置英雄出战状态回包
#define PROTOCOL_RSP_SUBCMD_HERO_STATE_LIST_QUERY 8			// 英雄状态列表查询回包
#define PROTOCOL_RSP_SUBCMD_HERO_PROP_CHANGE 9 				// 英雄属性变化回包
#define PROTOCOL_RSP_SUBCMD_HERO_FULL_HP 10 				// 英雄一键恢复回包
#define PROTOCOL_RSP_SUBCMD_HERO_ADD_ONE 11 				// 招募一个英雄回包
#define PROTOCOL_RSP_SUBCMD_HERO_REFRESH 12 				// 英雄刷新
#define PROTOCOL_RSP_SUBCMD_HERO_AUTO_REFRESH 13 			// 英雄刷新一键十次
#define PROTOCOL_RSP_SUBCMD_HERO_CULTURE 14 				// 英雄培养

// 英雄回包返回值
#define PROTOCOL_RET_HERO_SUCCESS 0 			// 操作成功
#define PROTOCOL_RET_HERO_FAIL 1 				// 操作失败
#define PROTOCOL_RET_HERO_PACKET_ERROR 2 		// 收包数据有错
#define PROTOCOL_RET_HERO_NOT_EXIST 3 			// 英雄不存在
#define PROTOCOL_RET_HERO_USER_LEVEL_LIMIT 4 	// 玩家等级限制
#define PROTOCOL_RET_HERO_FULL_HP 5

/*-----------------建筑相关协议------------------*/
#define PROTOCOL_CMD_BUILDING 4
#define PROTOCOL_SUBCMD_BUILDINGLIST 1 						// 获取建筑列表
#define PROTOCOL_SUBCMD_BUILDING_QUERY_ONE 2 				// 查询单个建筑信息
#define PROTOCOL_SUBCMD_BUILDING_BUILD 3 					// 建造
#define PROTOCOL_SUBCMD_BUILDING_MOVE 4 					// 建筑移动
#define PROTOCOL_SUBCMD_BUILDING_UPGRADE 5 					// 建筑升级
#define PROTOCOL_SUBCMD_BUILDING_REPAIR 6 					// 建筑修复
#define PROTOCOL_SUBCMD_BUILDING_BUILD_OVER 7 				// 建筑建造完成
#define PROTOCOL_SUBCMD_BUILDING_UPGRADE_OVER 8 			// 建筑升级完成
#define PROTOCOL_SUBCMD_BUILDING_REPAIR_OVER 9 				// 建筑修复完成
#define PROTOCOL_SUBCMD_BUILDING_TIMER_QUERY 10 			// 所有建筑定时完成信息查询
#define PROTOCOL_SUBCMD_BUILDING_PROP_CHANGE 11 			// 建筑属性变化
#define PROTOCOL_SUBCMD_BUILDING_COLLECT_RESOURCE 12 		// 搜集建筑产出资源
#define PROTOCOL_SUBCMD_BUILDING_BASE_STATE_QUERY 13 		// 基地状态查询
#define PROTOCOL_SUBCMD_BUILDING_FULL_HP 14 				// 建筑一键恢复
#define PROTOCOL_SUBCMD_BUILDING_COLLECT_ALL_RESOURCE 15	// 资源全收
#define PROTOCOL_SUBCMD_BUILDING_UPGRADE_WALL 16 			// 升级城墙
#define PROTOCOL_SUBCMD_BUILDING_SET_LAYOUT 17 				// 设置布局
#define PROTOCOL_SUBCMD_BUILDING_BUY_WORK_SHED 18 			// 购买建造仓
#define PROTOCOL_SUBCMD_BUILDING_BUY_LAYOUT_SLOT 19			// 购买建筑布局队列
#define PROTOCOL_SUBCMD_BUILDING_QUERY_LAYOUT_SLOT 20		// 查询建筑布局队列
#define PROTOCOL_SUBCMD_BUILDING_REMOVE_LAYOUT 21			// 删除建筑布局
#define PROTOCOL_SUBCMD_BUILDING_LOAD_LAYOUT 22				// 读取建筑布局
#define PROTOCOL_SUBCMD_BUILDING_SAVE_LAYOUT 23				// 保存建筑布局
#define PROTOCOL_SUBCMD_BUILDING_COLLECT_BLOOD_BAG 24 		// 搜集建筑产出血包

#define PROTOCOL_SUBCMD_BUILDING_SUPER_WEAPON_QUERY 25
#define PROTOCOL_SUBCMD_BUILDING_SUPER_WEAPON_RESEARCH 26
#define PROTOCOL_SUBCMD_BUILDING_SUPER_WEAPON_MADE 27
#define PROTOCOL_SUBCMD_BUILDING_SUPER_WEAPON_USE 28
#define PROTOCOL_SUBCMD_BUILDING_SUPER_WEAPON_RESEARCH_FINISH_NOW 29
#define PROTOCOL_SUBCMD_BUILDING_SUPER_WEAPON_MADE_FINISH_NOW 30
#define PROTOCOL_SUBCMD_BUILDING_REMOVE 31
#define PROTOCOL_SUBCMD_BUILDING_STRONG 32
#define PROTOCOL_SUBCMD_BUILDING_CHECK_OVERLAP_DONE 33
#define PROTOCOL_SUBCMD_BUILDING_SET_HS 34
#define PROTOCOL_SUBCMD_BUILDING_UPGRADE_ACC 35
#define PROTOCOL_SUBCMD_BUILDING_TOWER 36
#define PROTOCOL_SUBCMD_BUILDING_UPGRADE_TOWER 37
#define PROTOCOL_SUBCMD_BUILDING_TOWER_STAR_INFO 38
#define PROTOCOL_SUBCMD_BUILDING_TOWER_STAR_UPGRADE 39


#define PROTOCOL_RSP_SUBCMD_BUILDINGLIST 1
#define PROTOCOL_RSP_SUBCMD_BUILDING_QUERY_ONE 2
#define PROTOCOL_RSP_SUBCMD_BUILDING_BUILD 3
#define PROTOCOL_RSP_SUBCMD_BUILDING_MOVE 4
#define PROTOCOL_RSP_SUBCMD_BUILDING_UPGRADE 5
#define PROTOCOL_RSP_SUBCMD_BUILDING_REPAIR 6
#define PROTOCOL_RSP_SUBCMD_BUILDING_BUILD_OVER 7
#define PROTOCOL_RSP_SUBCMD_BUILDING_UPGRADE_OVER 8
#define PROTOCOL_RSP_SUBCMD_BUILDING_REPAIR_OVER 9
#define PROTOCOL_RSP_SUBCMD_BUILDING_TIMER_QUERY 10
#define PROTOCOL_RSP_SUBCMD_BUILDING_PROP_CHANGE 11
#define PROTOCOL_RSP_SUBCMD_BUILDING_COLLECT_RESOURCE 12 	// 搜集建筑产出资源回包
#define PROTOCOL_RSP_SUBCMD_BUILDING_BASE_STATE_QUERY 13 	// 基地状态查询
#define PROTOCOL_RSP_SUBCMD_BUILDING_FULL_HP 14 		// 建筑一键恢复
#define PROTOCOL_RSP_SUBCMD_BUILDING_COLLECT_ALL_RESOURCE 15 	// 资源全收

// 建筑回包返回值
#define PROTOCOL_RET_BUILDING_SUCCESS 0 			// 操作成功
#define PROTOCOL_RET_BUILDING_FAIL 1 				// 操作失败
#define PROTOCOL_RET_BUILDING_PACKET_ERROR 2 		// 收包数据有错
#define PROTOCOL_RET_BUILDING_COUNT_LIMIT 3 		// 可建数量限制
#define PROTOCOL_RET_BUILDING_RESOURCE_LIMIT 4 		// 资源数量限制
#define PROTOCOL_RET_BUILDING_POSITION_ERROR 5 		// 位置不合法
#define PROTOCOL_RET_BUILDING_NOT_EXIST 6			// 建筑不存在

/*-----------------玩家相关协议------------------*/
#define PROTOCOL_CMD_USER 5

#define PROTOCOL_SUBCMD_USERINFO 1
#define PROTOCOL_SUBCMD_MENUBAR_QUERY 2
#define PROTOCOL_SUBCMD_MENUBAR_SET 3
#define PROTOCOL_SUBCMD_USER_HERO_REFRESH 4				// 刷将
#define PROTOCOL_SUBCMD_CHOOSE_HERO_REFRESH_ITEM 5		// 选择刷新物品
#define PROTOCOL_SUBCMD_HERO_RECRUIT 6					// 招募
#define PROTOCOL_SUBCMD_QUERY_HERO_REFRESH_ITEM 7		// 查询刷新的物品
#define PROTOCOL_SUBCMD_HERO_SET_CHIEF 8 				// 英雄设置成主将
#define PROTOCOL_SUBCMD_HERO_SET_STATION 9 				// 英雄派驻
#define PROTOCOL_SUBCMD_HERO_RECALL_STATION 11 			// 驻将召回
#define PROTOCOL_SUBCMD_HERO_TRAIN_LIST_QUERY 12 		// 英雄训练列表查询
#define PROTOCOL_SUBCMD_HERO_TRAIN_SLOT_OPEN 13 		// 开启英雄训练槽位
#define PROTOCOL_SUBCMD_HERO_TRAIN_FINISH_NOW 14 		// 英雄训练立即完成
#define PROTOCOL_SUBCMD_BUILDING_ACC_UPGRADE 15			// 建筑升级加速(15min)
#define PROTOCOL_SUBCMD_BUILDING_ACC_UPGRADE_QUERY 16	// 建筑升级加速免费次数查询
#define PROTOCOL_SUBCMD_SET_USRE_KINGDOM 17				// 设置玩家归属国
#define PROTOCOL_SUBCMD_BUY_BUILDING_ACC_UPGRADE 18		// 购买建筑升级加速(15min)次数
#define PROTOCOL_SUBCMD_BAG_SIZE 19						// 背包格子数量
#define PROTOCOL_SUBCMD_TUTORIAL_STAGE_SET 20			// 设置新手阶段
#define PROTOCOL_SUBCMD_TRAILER_STAGE_SET 21			// 设置预告阶段
#define PROTOCOL_SUBCMD_USRE_COMBAT 22					// 玩家战力
#define PROTOCOL_SUBCMD_QUERY_HERO_REFRESH_LIST 23		// 英雄刷新列表
#define PROTOCOL_SUBCMD_SET_BLOOD_BANK_THRESHOLD 24		// 设置血库回血门限
#define PROTOCOL_SUBCMD_USER_GET_VIP_LEVEL_REWARD 25	// vip等级奖励
#define PROTOCOL_SUBCMD_USER_GET_VIP_CHARGE_REWARD 26	// vip充值奖励
#define PROTOCOL_SUBCMD_USER_BUY_PVP_TIMES 27			// 购买掠夺次数
#define PROTOCOL_SUBCMD_USER_GET_BLUE_VALID_TIME 28		// 获取蓝钻有效时间
#define PROTOCOL_SUBCMD_USER_GET_PAY_TOKEN 29			// 获取蓝钻续费token
#define PROTOCOL_SUBCMD_USER_COMBAT_DETECT 30			// 战力检测
#define PROTOCOL_SUBCMD_USER_TENCENT_INFO 31			// 腾讯玩家信息
#define PROTOCOL_SUBCMD_USER_ADDICTION_RATE 32			// 防沉迷收益倍数
#define PROTOCOL_SUBCMD_USER_ADDICTION_RATE_QUERY 34	// 防沉迷收益倍数
#define PROTOCOL_SUBCMD_USER_VIP_DAILY_REWARD 35		// VIP每日礼包
#define PROTOCOL_SUBCMD_USER_RESET_PROTECT_TIME 36		// 重置保护时间
#define PROTOCOL_SUBCMD_USER_PROTECT_TIME 37			// 保护时间
#define PROTOCOL_SUBCMD_USER_PROTECT_INFO 38			// 护盾
#define PROTOCOL_SUBCMD_USER_PROTECT_STOP 39			// 护盾
#define PROTOCOL_SUBCMD_USER_NEXT_DAY 40				// 通知前台已经过了一天
#define PROTOCOL_SUBCMD_USER_OFFLINE_INFO 41			// 离线收益
#define PROTOCOL_SUBCMD_USER_ADD_SHORTCUT_REWARD 42		// 收藏奖励
#define PROTOCOL_SUBCMD_USER_CLIENT_STATE 43			// 前台存储标志位
#define PROTOCOL_SUBCMD_USER_REWARD_INFO 44				// 奖励列表

#define PROTOCOL_SUBCMD_USER_TECH_INFO 46				// 科技信息
#define PROTOCOL_SUBCMD_USER_TECH_UPGRADE 47			// 科技升级
#define PROTOCOL_SUBCMD_USER_TECH_FINISH 48				// 科技立即升级
#define PROTOCOL_SUBCMD_USER_RUINS_INFO 49				// 遗迹信息
#define PROTOCOL_SUBCMD_USER_RUINS_OPEN 50				// 遗迹开采
#define PROTOCOL_SUBCMD_USER_RUINS_ACC 51				// 遗迹减CD
#define PROTOCOL_SUBCMD_USER_PLATFORM_GIFT 52			// 平台礼包
#define PROTOCOL_SUBCMD_USER_DAILY_LOGIN_INFO 53		// 每日登陆奖励
#define PROTOCOL_SUBCMD_USER_DAILY_LOGIN_REWARD 54		// 每日登陆奖励
#define PROTOCOL_SUBCMD_USER_LEVEL_REWARD_INFO 55		// 等级奖励
#define PROTOCOL_SUBCMD_USER_LEVEL_REWARD 56			// 等级奖励
#define PROTOCOL_SUBCMD_USER_DAILY_SIGN_INFO 57			// 每日签到奖励
#define PROTOCOL_SUBCMD_USER_DAILY_SIGN_REWARD 58		// 每日签到奖励
#define PROTOCOL_SUBCMD_USER_AUTO_REWARD_INFO 59		// 挂机奖励信息
#define PROTOCOL_SUBCMD_USER_AUTO_REWARD_BAG 60			// 挂机奖励宝箱
#define PROTOCOL_SUBCMD_USER_AUTO_REWARD_PUSH 61		// 挂机奖励推送
#define PROTOCOL_SUBCMD_USER_AUTO_REWARD_TS_PUSH 62		// 挂机时间推送
#define PROTOCOL_SUBCMD_USER_VIP_INFO 63				// VIP数据
#define PROTOCOL_SUBCMD_USER_VIP_REWARD 64				// VIP奖励
#define PROTOCOL_SUBCMD_USER_CHARGE_REWARD 65			// 充值奖励信息
#define PROTOCOL_SUBCMD_USER_DAILY_CHARGE_REWARD 66		// 每日充值奖励
#define PROTOCOL_SUBCMD_USER_TOTAL_CHARGE_REWARD 67		// 累计充值奖励
#define PROTOCOL_SUBCMD_USER_SET_NAME 68				// 设置名字和头像
#define PROTOCOL_SUBCMD_USER_FIRST_CHARGE 69			// 首充奖励
#define PROTOCOL_SUBCMD_USER_MONTH_GIFT_INFO 70			// 月度宝箱
#define PROTOCOL_SUBCMD_USER_MONTH_GIFT_REWARD 71		// 月度宝箱
#define PROTOCOL_SUBCMD_USER_IS_NEW 72					// 是否新注册
#define PROTOCOL_SUBCMD_USER_BUY_VIP_GIFT 73			// vip礼包
#define PROTOCOL_SUBCMD_USER_CHARGE_REPORT 74			// 充值统计
#define PROTOCOL_SUBCMD_USER_HELP 75					// 点赞
#define PROTOCOL_SUBCMD_USER_HELP_BOX 76				// 点赞兑换
#define PROTOCOL_SUBCMD_USER_HELP_NOTICE 77				// 点赞通知
#define PROTOCOL_SUBCMD_USER_AUTO_REWARD 78				// 挂机奖励

#define PROTOCOL_RSP_SUBCMD_USERINFO 1
#define PROTOCOL_RSP_SUBCMD_USER_HERO_REFRESH 4			// 刷将回包
#define PROTOCOL_RSP_SUBCMD_CHOOSE_HERO_REFRESH_ITEM 5	// 选中刷新物品回包
#define PROTOCOL_RSP_SUBCMD_HERO_RECRUIT 6				// 招募
#define PROTOCOL_RSP_SUBCMD_QUERY_HERO_REFRESH_ITEM 7	// 查询刷新的物品回包
#define PROTOCOL_RSP_SUBCMD_HERO_SET_CHIEF 8 			// 英雄设置成主将
#define PROTOCOL_RSP_SUBCMD_HERO_SET_STATION 9 			// 英雄派驻
#define PROTOCOL_RSP_SUBCMD_HERO_FIRED 10 				// 英雄解雇
#define PROTOCOL_RSP_SUBCMD_HERO_RECALL_STATION 11 		// 驻将召回
#define PROTOCOL_RSP_SUBCMD_HERO_TRAIN_LIST_QUERY 12 	// 英雄训练列表查询
#define PROTOCOL_RSP_SUBCMD_HERO_TRAIN_SLOT_OPEN 13 	// 开启英雄训练槽位
#define PROTOCOL_RSP_SUBCMD_HERO_TRAIN_FINISH_NOW 14 	// 英雄训练立即完成
#define PROTOCOL_RSP_SUBCMD_BUILDING_ACC_UPGRADE 15		// 建筑升级加速(15min)回包
#define PROTOCOL_RSP_SUBCMD_BUILDING_ACC_UPGRADE_QUERY 16	// 建筑升级加速免费次数查询
#define PROTOCOL_RSP_SUBCMD_SET_USER_KINGDOM 17			// 设置玩家归属国回包
#define PROTOCOL_RSP_SUBCMD_BUY_BUILDING_ACC_UPGRADE 18	// 购买建筑升级加速(15min)次数
#define PROTOCOL_RSP_SUBCMD_USRE_COMBAT 22				// 玩家战力
#define PROTOCOL_RSP_SUBCMD_QUERY_HERO_REFRESH_LIST 23	// 英雄刷新列表
#define PROTOCOL_RSP_SUBCMD_ADDTCTION_NOTIFY 33			// 防沉迷
#define PROTOCOL_RSP_SUBCMD_USER_VIP_DAILY_REWARD 35	// VIP每日礼包

// 玩家回包返回值
#define PROTOCOL_RET_USER_SUCCESS 0 				// 操作成功
#define PROTOCOL_RET_USER_FAIL 1 					// 操作失败
#define PROTOCOL_RET_USER_PACKET_ERROR 2 			// 收包数据有错
#define PROTOCOL_RET_USER_RESOURCE_LIMIT_ERROR 3	// 资源限制
#define PROTOCOL_RET_USER_HERO_NOT_EXIST 4			// 英雄不存在
#define PROTOCOL_RET_USER_BUILDING_NOT_EXIST 5		// 建筑不存在
#define PROTOCOL_RET_USER_BUILDING_TYPE_MISSMATCH 6	// 建筑类型不匹配

/*-----------------资源相关协议------------------*/
#define PROTOCOL_CMD_RESOURCE 6
#define PROTOCOL_SUBCMD_RESOURCE_QUERY 1 			// 请求单个用户资源信息
#define PROTOCOL_SUBCMD_BUY_TL 2 					// 购买体力
#define PROTOCOL_SUBCMD_QUERY_BUY_TL 3 				// 查询今日购买体力次数
#define PROTOCOL_SUBCMD_BUY_RES 4					// 购买资源
#define PROTOCOL_SUBCMD_QUERY_BUY_TIMES 5			// 购买资源
#define PROTOCOL_SUBCMD_USE_RES 6					// 消耗资源

#define PROTOCOL_RSP_SUBCMD_RESOURCE_QUERY 1 		// 响应单个用户资源信息
#define PROTOCOL_RSP_SUBCMD_BUY_TL 2 				// 购买体力回包
#define PROTOCOL_RSP_SUBCMD_QUERY_BUY_TL 3 			// 查询今日购买体力次数回包

// 战斗回包返回值
#define PROTOCOL_RET_RESOURCE_SUCCESS 0 			// 操作成功
#define PROTOCOL_RET_RESOURCE_FAIL 1 				// 操作失败


/*-----------------战斗相关协议------------------*/

#define PROTOCOL_CMD_BATTLE 7
#define PROTOCOL_RSP_SUBCMD_BATTLE_ATTACK_REFUSE 0
#define PROTOCOL_SUBCMD_BATTLE_SPY 1 				// 侦查
#define PROTOCOL_SUBCMD_BATTLE_ERROR 2 				// 战场错误
#define PROTOCOL_SUBCMD_BATTLE_MOVE 3				// 移动
#define PROTOCOL_SUBCMD_BATTLE_ENTER_SINGLE 4		// 进入1v1战战场
#define PROTOCOL_SUBCMD_BATTLE_UNDER_ATTACK 5		// 被攻击
#define PROTOCOL_SUBCMD_BATTLE_ATTACK 6				// 攻击
#define PROTOCOL_SUBCMD_BATTLE_SPAWN_HERO 7 		// 投放英雄
#define PROTOCOL_SUBCMD_BATTLE_OFFLINE 9			// 玩家下线(l->b)
#define PROTOCOL_SUBCMD_BATTLE_OVER 10				// 战斗信息同步(b->l)
#define PROTOCOL_SUBCMD_BATTLE_ONLINE 11			// 玩家上线(l->b)
#define PROTOCOL_SUBCMD_BATTLE_INFO_STORE 12		// 战斗结果(b->l)
#define PROTOCOL_SUBCMD_BATTLE_CONFIRM 13			// 战斗结束确认
#define PROTOCOL_SUBCMD_BATTLE_GET_ONLINE_LIST 14	// 查询在线用户

#define PROTOCOL_SUBCMD_BATTLE_JOIN_BATTLES 17		// 正在参与的战场信息
#define PROTOCOL_SUBCMD_BATTLE_PLAYER_WATCH 18		// 玩家进入大地图战场
#define PROTOCOL_SUBCMD_BATTLE_LOGIN_SERVERID 19 	// 同步serverid(l->b)
#define PROTOCOL_SUBCMD_BATTLE_GET_BATTLE_LIST 20	// 查询战斗列表
#define PROTOCOL_SUBCMD_BATTLE_SINGLE_LOAD 21 		// 加载地图信息(b->l)
#define PROTOCOL_SUBCMD_BATTLE_CARBON_LOAD 22 		// 加载地图信息(b->l)
#define PROTOCOL_SUBCMD_BATTLE_OVERVIEW 23			// 战场概况
#define PROTOCOL_SUBCMD_BATTLE_STORE 26				// 地图信息存档
#define PROTOCOL_SUBCMD_BATTLE_EXIT 27				// 退出战场
#define PROTOCOL_SUBCMD_BATTLE_OBSERVE 29 		    // 进入旁观
#define PROTOCOL_SUBCMD_BATTLE_QUIT 31				// 退出战场
#define PROTOCOL_SUBCMD_BATTLE_BACK_HOME 	32		// 退出战场回基地
#define PROTOCOL_SUBCMD_BATTLE_BACK_WORLD 	33		// 退出战场回大地图
#define PROTOCOL_SUBCMD_BATTLE_AUTO_MANU 	34		// 设置手动或是自动模式
#define PROTOCOL_SUBCMD_BATTLE_ENABLE_SPAWN_HERO 35	// 投将许可包
#define PROTOCOL_SUBCMD_BATTLE_NVN_WAITER_LIST 36	// 攻击者列表
#define PROTOCOL_SUBCMD_BATTLE_SINGLE_OUT 37		// 单挑
#define PROTOCOL_SUBCMD_BATTLE_CITY_OWNER_CHIEF_INFO 38	// 城主信息
#define PROTOCOL_SUBCMD_BATTLE_GET_DATA 39			// 获取战场数据
#define PROTOCOL_SUBCMD_BATTLE_ENTER_NEGATIVE 40	// 进入被动推图
#define PROTOCOL_SUBCMD_BATTLE_HERO_ENTER_WORLD 41 	// 英雄进入世界地图战场
#define PROTOCOL_SUBCMD_BATTLE_HERO_EXIT_WORLD 42	// 英雄退出世界地图战场
#define PROTOCOL_SUBCMD_BATTLE_PLAYER_EXIT_WORLD 43	// 玩家退出世界地图战场
#define PROTOCOL_SUBCMD_BATTLE_ENTER_POSITIVE 44	// 进入进攻推图战场
#define PROTOCOL_SUBCMD_BATTLE_SINGLE_OUT_MOVE 45	// 单挑移动
#define PROTOCOL_SUBCMD_BATTLE_SINGLE_OUT_ATTACK 46	// 单挑攻击
#define PROTOCOL_SUBCMD_BATTLE_SINGLE_OUT_PLAYER_ENTER 47	// 玩家进单挑战场
#define PROTOCOL_SUBCMD_BATTLE_SINGLE_OUT_PLAYER_EXIT 48	// 玩家退单挑战场
#define PROTOCOL_SUBCMD_BATTLE_WORLD_PLAYER_STATE 49	// 玩家世界地图状态
//#define PROTOCOL_SUBCMD_BATTLE_CARBON_LOAD 50 		// 加载副本地图(b->l)
#define PROTOCOL_SUBCMD_BATTLE_SINGLE_OUT_AUTO_MANU 51	// 单挑切换将领操作模式
#define PROTOCOL_SUBCMD_BATTLE_NVN_LOAD 52 				// 加载NVN地图信息(b->l)
#define PROTOCOL_SUBCMD_BATTLE_ALLOW_SPAWN_HERO_LIST 53 // 可投将领列表
#define PROTOCOL_SUBCMD_BATTLE_SPAWN_TIME 54 			// 战场相关时间
#define PROTOCOL_SUBCMD_BATTLE_BATTLE_TIME 55 			// 战场相关时间
#define PROTOCOL_SUBCMD_BATTLE_BASE_DAMAGE 56 			// 摧毁百分比
#define PROTOCOL_SUBCMD_BATTLE_ROBS 57 					// 战利品
#define PROTOCOL_SUBCMD_BATTLE_USER_GAIN_REWARD 58			// 玩家获得经验
#define PROTOCOL_SUBCMD_BATTLE_DESTROY 59				// 结束战斗
#define PROTOCOL_SUBCMD_BATTLE_BASE_RECOVE_TIME	60		// 基地恢复时间
#define PROTOCOL_SUBCMD_BATTLE_SYSTEM_TIPS	61			// 战斗服务器提示信息
#define PROTOCOL_SUBCMD_BATTLE_SKILL_ATTACK 62
#define PROTOCOL_SUBCMD_BATTLE_HERO_CARRY_HOSTAGE	62	// 英雄携带人质数量
#define PROTOCOL_SUBCMD_BATTLE_BUILDING_EXIST_TARGET	63	// 建筑是否有暗杀目标
#define PROTOCOL_SUBCMD_BATTLE_ENTER_CARBON_BOSS	64	// 进入副本BOSS战场
#define PROTOCOL_SUBCMD_BATTLE_PLAYER_DAMAGE	65		// 玩家输出伤害
#define PROTOCOL_SUBCMD_BATTLE_BUY_REVIVE	66			// 战场付费买活
#define PROTOCOL_SUBCMD_BATTLE_STORE_WORLD_BOSS 67		// 世界BOSS信息存档
#define PROTOCOL_SUBCMD_BATTLE_BOSS_OVER 68				// BOSS战结束
#define PROTOCOL_SUBCMD_BATTLE_ROBOT_NUM 69				// 机器人数
#define PROTOCOL_SUBCMD_BATTLE_SAVED_HOSTAGE_COUNT 70	// 营救人质数
#define PROTOCOL_SUBCMD_BATTLE_SINGLE_REFRESH_TARGET 71	// 刷新PVP攻击目标
#define PROTOCOL_SUBCMD_BATTLE_MAP_OBJ_DIE 72			// 地图对象死亡
#define PROTOCOL_SUBCMD_BATTLE_DEL_WATCH_PLAYER	73		// 删除观战玩家
#define PROTOCOL_SUBCMD_BATTLE_STOP	74					// 暂停战斗
#define PROTOCOL_SUBCMD_BATTLE_ALLOW_SOLDIER_LIST 75	// 可投兵种列表
#define PROTOCOL_SUBCMD_BATTLE_SPAWN_SOLDIER 76			// 投兵
#define PROTOCOL_SUBCMD_BATTLE_RESULT 77				// 战斗结果
#define PROTOCOL_SUBCMD_BATTLE_REVENGE	78				// 复仇
#define PROTOCOL_SUBCMD_BATTLE_ENTER_INVADE	79			// 进入生死防线副本
#define PROTOCOL_SUBCMD_SYNC_SKILL_TO_BATTLE 80			// pvp战斗结果
#define PROTOCOL_SUBCMD_BATTLE_ENTER_MULTI_INVADE	81	// 进入联合副本
#define PROTOCOL_SUBCMD_BATTLE_MULTI_INVADE_LOAD	82	// 副本加载
#define PROTOCOL_SUBCMD_BATTLE_ENTER_WARRIOR 85			// 进入名将试练战场
#define PROTOCOL_SUBCMD_BATTLE_GET_CARBON_REBEL 86		// 副本叛军
#define PROTOCOL_SUBCMD_BATTLE_MULTI_POSITIVE 90		// 多人联合防守副本
#define PROTOCOL_SUBCMD_BATTLE_TUTOR_ENTER_DEMO 91		// 新手示例战场
#define PROTOCOL_SUBCMD_BATTLE_TUTOR_ACTIVE_OPTION 92	// 对象激活
#define PROTOCOL_SUBCMD_BATTLE_TUTOR_ACTIVE_SKILL 93	// 新手示例技能
#define PROTOCOL_SUBCMD_BATTLE_TUTOR_SPAWN 94			// 新手投将包
#define PROTOCOL_SUBCMD_BATTLE_VIEW_HOME 95				// 访问家园
#define PROTOCOL_SUBCMD_BATTLE_CAMP_KILL_HERO 96		// 阵营杀英雄数
#define PROTOCOL_SUBCMD_BATTLE_CLEAR 100				// 清除战场
#define PROTOCOL_SUBCMD_BATTLE_NEW_ALLIANCE 101			// 开辟盟战
#define PROTOCOL_SUBCMD_BATTLE_ENTER_ALLIANCE 102		// 进入盟战
#define PROTOCOL_SUBCMD_BATTLE_BUILDING_LEFT_HP 103		// 剩余血量百分比
#define PROTOCOL_SUBCMD_BATTLE_READY_TIME 104			// 准备时间
#define PROTOCOL_SUBCMD_BATTLE_ENTER_JOINT_OPERATION 105// 进入联合副本
#define PROTOCOL_SUBCMD_BATTLE_HERO_ENTER_RESULT 106	// 英雄进战场结果
#define PROTOCOL_SUBCMD_BATTLE_BROAD 107				// 战场广播
#define PROTOCOL_SUBCMD_BATTLE_CREATE_DUEL 108			// 创建斗将战场
#define PROTOCOL_SUBCMD_BATTLE_UNDER_TRANS_RES_ATTACK 109	// 资源运输被攻击
#define PROTOCOL_SUBCMD_BATTLE_KICK 110					// 战场踢下线
#define PROTOCOL_SUBCMD_BATTLE_BUY_HERO_COPY 111		// 购买英雄幻影
#define PROTOCOL_SUBCMD_BATTLE_ENTER_BUTCHER 112		// 进屠夫战场
#define PROTOCOL_SUBCMD_BATTLE_THROW_HOOK 113			// 放钩
#define PROTOCOL_SUBCMD_BATTLE_HOOK_TARGET 114			// 钩中目标
#define PROTOCOL_SUBCMD_BATTLE_SYNC_HOOK 115			// 同步钩子位置
#define PROTOCOL_SUBCMD_BATTLE_CREATE_GOD 116			// 战场踢下线
#define PROTOCOL_SUBCMD_BATTLE_ENTER_BOAT 117			// 拦船战场
#define PROTOCOL_SUBCMD_BATTLE_SPACE 118				// 战场空间
#define PROTOCOL_SUBCMD_BATTLE_CANNON_ATTACK 119		//
#define PROTOCOL_SUBCMD_BATTLE_ENTER_GATE_DEFEND 120	//
#define PROTOCOL_SUBCMD_BATTLE_ADD_BULLET 121			//
#define PROTOCOL_SUBCMD_BATTLE_ENTER_DEFEND 122			//
#define PROTOCOL_SUBCMD_BATTLE_REPORT 123			    //

#define PROTOCOL_RSP_SUBCMD_BATTLE_ATTACK_REFUSE 0 		// 攻击包拒绝
#define PROTOCOL_RSP_SUBCMD_BATTLE_SPY 1 				// 侦查回包
#define PROTOCOL_RSP_SUBCMD_BATTLE_ESTABLISH 2 			// 开辟战场回包
#define PROTOCOL_RSP_SUBCMD_BATTLE_MOVE 3 				// 移动
#define PROTOCOL_RSP_SUBCMD_BATTLE_INFO 4 				// 同步给客户端战场信息
#define PROTOCOL_RSP_SUBCMD_BATTLE_UNDER_ATTACK 5 		// 被攻击
#define PROTOCOL_RSP_SUBCMD_BATTLE_ATTACK 6				// 攻击
#define PROTOCOL_RSP_SUBCMD_BATTLE_HERO_APPEAR 7		// 英雄出现
#define PROTOCOL_RSP_SUBCMD_BATTLE_PROP_CHANGE 8 		// 属性变化
#define PROTOCOL_RSP_SUBCMD_BATTLE_HERO_DISAPPEAR 9		// 英雄消失(死亡)
#define PROTOCOL_RSP_SUBCMD_BATTLE_OVER 10				// 战斗信息同步(b->l)
#define PROTOCOL_RSP_SUBCMD_BATTLE_CONFIRM 13			// 重新load数据完成确认
#define PROTOCOL_RSP_SUBCMD_BATTLE_GET_ONLINE_LIST 14	// 查询在线用户回包
#define PROTOCOL_RSP_SUBCMD_BATTLE_POS_RESET 15			// 位置校验拉回
//#define PROTOCOL_RSP_SUBCMD_BATTLE_EXIT 16				// 退出战场回包
#define PROTOCOL_RSP_SUBCMD_BATTLE_PLAYER_ENTER_WORLD 18// 玩家进入战场回包
#define PROTOCOL_RSP_SUBCMD_BATTLE_GET_BATTLE_LIST 20	// 查询战斗列表回包
#define PROTOCOL_RSP_SUBCMD_BATTLE_LOAD 21 				// 加载地图信息回包
#define PROTOCOL_RSP_SUBCMD_BATTLE_CARBON_LOAD 22 		// 加载地图信息回包
#define PROTOCOL_RSP_SUBCMD_BATTLE_OVERVIEW 23			// 战场概况回包
#define PROTOCOL_RSP_SUBCMD_BATTLE_CAMP_KILL_COUNT 24	// 阵营杀敌数
#define PROTOCOL_RSP_SUBCMD_BATTLE_CAMP_JOIN_COUNT 25	// 阵营参战人数
#define PROTOCOL_RSP_SUBCMD_BATTLE_STORE 26			 	// 战场信息存档
#define PROTOCOL_RSP_SUBCMD_BATTLE_EXIT 27			 	// 战场信息存档
#define PROTOCOL_RSP_SUBCMD_BATTLE_AUTO_MANU 34			// 设置手动或是自动模式
#define PROTOCOL_RSP_SUBCMD_BATTLE_SINGLE_OUT 37		// 单挑确认包
#define PROTOCOL_RSP_SUBCMD_BATTLE_CITY_OWNER_CHIEF_INFO 38	// 城主信息
#define PROTOCOL_RSP_SUBCMD_BATTLE_HERO_ENTER_WORLD 41	// 英雄进入大地图战场
#define PROTOCOL_RSP_SUBCMD_BATTLE_HERO_EXIT_WORLD 42	// 英雄退出世界地图战场
#define PROTOCOL_RSP_SUBCMD_BATTLE_PLAYER_EXIT_WORLD 43	// 玩家退出世界地图战场回包
#define PROTOCOL_RSP_SUBCMD_BATTLE_SINGLE_OUT_MOVE 45	// 单挑移动
#define PROTOCOL_RSP_SUBCMD_BATTLE_SINGLE_OUT_ATTACK 46	// 单挑攻击
#define PROTOCOL_RSP_SUBCMD_BATTLE_SINGLE_OUT_PLAYER_ENTER 47	// 玩家进单挑战场
#define PROTOCOL_RSP_SUBCMD_BATTLE_SINGLE_OUT_PLAYER_EXIT 48	// 玩家退单挑战场
#define PROTOCOL_RSP_SUBCMD_BATTLE_WORLD_PLAYER_STATE 49	// 玩家世界地图状态回包
#define PROTOCOL_RSP_SUBCMD_BATTLE_FIGHTER_LIST 50		// 打包将领信息
#define PROTOCOL_RSP_SUBCMD_BATTLE_SINGLE_OUT_AUTO_MANU 51	// 玩家世界地图状态回包
#define PROTOCOL_RSP_SUBCMD_BATTLE_NVN_LOAD 52 				// 加载NVN地图信息(b->l)
#define PROTOCOL_RSP_SUBCMD_BATTLE_ALLOW_SPAWN_HERO_LIST 53 // 可投将领列表回包
#define PROTOCOL_RSP_SUBCMD_BATTLE_USER_GAIN_REWARD 58			// 玩家获得经验
#define PROTOCOL_RSP_SUBCMD_BATTLE_DESTROY 59				// 结束战斗回包
#define PROTOCOL_RSP_SUBCMD_BATTLE_BASE_RECOVE_TIME	60		// 基地恢复时间回包
#define PROTOCOL_RSP_SUBCMD_BATTLE_SYSTEM_TIPS	61			// 战斗服务器提示信息回包
#define PROTOCOL_RSP_SUBCMD_BATTLE_HERO_CARRY_HOSTAGE	62	// 英雄携带人质数量回包
#define PROTOCOL_RSP_SUBCMD_BATTLE_BUILDING_EXIST_TARGET	63	// 建筑是否有暗杀目标回包
#define PROTOCOL_RSP_SUBCMD_BATTLE_ENTER_CARBON_BOSS	64	// 进入副本BOSS战场回包
#define PROTOCOL_RSP_SUBCMD_BATTLE_PLAYER_DAMAGE	65		// 玩家输出伤害回包
#define PROTOCOL_RSP_SUBCMD_BATTLE_BUY_REVIVE	66			// 战场付费买活
#define PROTOCOL_RSP_SUBCMD_BATTLE_STORE_WORLD_BOSS 67		// 世界BOSS信息存档
#define PROTOCOL_RSP_SUBCMD_BATTLE_BOSS_OVER 68				// BOSS战结束回包
#define PROTOCOL_RSP_SUBCMD_BATTLE_ROBOT_NUM 69				// 机器人数回包
#define PROTOCOL_RSP_SUBCMD_BATTLE_SAVED_HOSTAGE_COUNT 70	// 营救人质数
#define PROTOCOL_RSP_SUBCMD_BATTLE_SINGLE_REFRESH_TARGET 71	// 刷新攻击目标回包
#define PROTOCOL_RSP_SUBCMD_BATTLE_MAP_OBJ_DIE 72			// 地图对象死亡
#define PROTOCOL_RSP_SUBCMD_BATTLE_DEL_WATCH_PLAYER	73		// 删除观战玩家
#define PROTOCOL_RSP_SUBCMD_BATTLE_STOP	74					// 暂停战斗回包
#define PROTOCOL_RSP_SUBCMD_BATTLE_ALLOW_SOLDIER_LIST 75	// 可投兵种列表
#define PROTOCOL_RSP_SUBCMD_BATTLE_SPAWN_SOLDIER 76			// 投兵回包
//#define PROTOCOL_RSP_SUBCMD_BATTLE_SINGLE_RESULT 77			// pvp战斗结果
#define PROTOCOL_RSP_SUBCMD_BATTLE_INVADE_STAT 80			// 生死防线副本战场数据
#define PROTOCOL_RSP_SUBCMD_BATTLE_MULTI_INFO 81			// 生死防线副本战场数据
#define PROTOCOL_RSP_SUBCMD_BATTLE_MULTI_STAT 83			// 生死防线副本战场数据
#define PROTOCOL_RSP_SUBCMD_BATTLE_GET_CARBON_REBEL 86		// 副本叛军回包
#define PROTOCOL_RSP_SUBCMD_BATTLE_MULTI_AWARDS 87			// 战场奖励
#define PROTOCOL_RSP_SUBCMD_BATTLE_MULTI_TURN 88			// 第几轮刷兵
#define PROTOCOL_RSP_SUBCMD_BATTLE_DEMO_OVER 94				// DEMO战场结束
#define PROTOCOL_RSP_SUBCMD_BATTLE_KICK 110					// 战场踢下线
// 战斗回包返回值
#define PROTOCOL_RET_BATTLE_SUCCESS 0 			// 操作成功
#define PROTOCOL_RET_BATTLE_FAIL 1 				// 操作失败
#define PROTOCOL_RET_BATTLE_PACKET_ERROR 2 		// 收包数据有错
#define PROTOCOL_RET_BATTLE_NOT_EXIST 3 		// 战斗不存在
#define PROTOCOL_RET_BATTLE_NOT_FIGHT 4 		// 不在战斗状态
#define PROTOCOL_RET_BATTLE_WORLD_ON_FIGHT 5 	// 世界地图上处于战斗状态
#define PROTOCOL_RET_BATTLE_WORLD_OUT_FIGHT 6 	// 世界地图上退出战斗状态
#define PROTOCOL_RET_BATTLE_HERO_NOT_EXIST 7 	// 英雄不存在
#define PROTOCOL_RET_BATTLE_HERO_ON_FIGHT 8		// 英雄在战斗状态
#define PROTOCOL_RET_BATTLE_HERO_DIE 9			// 英雄死亡
#define PROTOCOL_RET_BATTLE_HERO_TRY_AGAIN 10	// 英雄重新尝试进战场

/*-----------------玩家数据状态相关协议------------------*/

#define PROTOCOL_CMD_PLAYER_DATA_STATE 8
#define PROTOCOL_SUBCMD_PLAYER_DATA_STATE_REFRESH_HERO_QUERY 1 		// 查询

#define PROTOCOL_RSP_SUBCMD_PLAYER_DATA_STATE_REFRESH_HERO_QUERY 1 		// 查询

/*-----------------战斗状态相关协议-------------------------*/
#define PROTOCOL_CMD_STATE_BATTLE 107
#define PROTOCOL_SUMCMD_STATE_BATTLE_QUERY 1		// 战斗查询
#define PROTOCOL_SUMCMD_STATE_BATTLE_NEW 2			// 开辟战场
#define PROTOCOL_SUMCMD_STATE_BATTLE_OVER 3			// 战斗结束
#define PROTOCOL_SUMCMD_STATE_BATTLE_LIST 4			// 战斗列表
#define PROTOCOL_SUMCMD_STATE_BATTLE_EXIST 5		// 战斗是否存在
#define PROTOCOL_SUMCMD_STATE_BATTLE_QUIT 6			// 退出战场
#define PROTOCOL_SUMCMD_STATE_BATTLE_QUERY_PLAYER_IN_FIGHT 7	// 玩家在战斗中

#define PROTOCOL_RSP_SUMCMD_STATE_BATTLE_QUERY 1	// 战斗查询回包
#define PROTOCOL_RSP_SUMCMD_STATE_BATTLE_NEW 2		// 开辟战场回包
#define PROTOCOL_RSP_SUMCMD_STATE_BATTLE_OVER 3		// 战斗结束回包
#define PROTOCOL_RSP_SUMCMD_STATE_BATTLE_LIST 4		// 战斗列表回包
#define PROTOCOL_RSP_SUMCMD_STATE_BATTLE_EXIST 5	// 战斗是否存在回包
#define PROTOCOL_RSP_SUMCMD_STATE_BATTLE_QUIT 6		// 退出战场回包
#define PROTOCOL_RSP_SUMCMD_STATE_BATTLE_QUERY_PLAYER_IN_FIGHT 7	// 玩家在战斗中

// 状态服务器回包返回值
#define PROTOCOL_RET_STATE_SUCCESS 0 				// 操作成功
#define PROTOCOL_RET_STATE_FAIL 1 					// 操作失败
#define PROTOCOL_RET_STATE_PACKET_ERROR 2 			// 收包数据有错
#define PROTOCOL_RET_STATE_IN_BATTLE 3 				// 在战斗状态
#define PROTOCOL_RET_STATE_OUT_BATTLE 4 			// 不在战斗状态
#define PROTOCOL_RET_STATE_NO_AVAIL_BATTLE_SERVER 5 // 无可用战斗服务器
#define PROTOCOL_RET_STATE_NO_AVAIL_LOGIN_SERVER 6	// 无可用登录服务器
#define PROTOCOL_RET_STATE_NO_MATCH_LOGIN_SERVER 7	// 匹配登录服务器
#define PROTOCOL_RET_STATE_USER_DEFENSE_STATE_SYNC 8		// 防守者处于同步状态
#define PROTOCOL_RET_STATE_BATTLE_NOT_EXIST	9			// 战场不存在
#define PROTOCOL_RET_STATE_BATTLE_PLAYER_IN_FIGHT	10	// 玩家在战斗

/*-----------------用户状态相关协议------------------*/
#define PROTOCOL_CMD_STATE_USER 108
#define PROTOCOL_SUBCMD_STATE_USER_SET_ONLINE 1 		// 设置玩家在线状态
#define PROTOCOL_SUBCMD_STATE_USER_SET_OFFLINE 2		// 设置玩家下线状态
#define PROTOCOL_SUBCMD_STATE_USER_QUERY_ONLINE 3 		// 获取玩家在线状态
#define PROTOCOL_SUBCMD_STATE_USER_GET_ONLINE_LIST 4	// 获取在线玩家列表
#define PROTOCOL_SUBCMD_STATE_USER_GET_MIN_LOAD_LOGIN 5	// 最小负载login
#define PROTOCOL_SUBCMD_STATE_USER_SET_SYNC 6			// 设置玩家同步状态
#define PROTOCOL_SUBCMD_STATE_USER_DECR_OPENID_REF 7	// 减少openid引用次数
#define PROTOCOL_SUBCMD_STATE_USER_GET_MIN_LOAD_LOGIN_BY_UID 8	// 使用uid分配最小负载login
#define PROTOCOL_SUBCMD_STATE_USER_GET_ONLINE_OPENID 9	// 获取在线玩家openId
#define PROTOCOL_SUBCMD_STATE_USER_DELETE 10 			// 删除玩家状态

// 用户状态回包返回值
#define PROTOCOL_RSP_SUBCMD_STATE_USER_SET_ONLINE 1 		// 设置玩家在线状态回包
#define PROTOCOL_RSP_SUBCMD_STATE_USER_SET_OFFLINE 2 		// 设置玩家下线状态回包
#define PROTOCOL_RSP_SUBCMD_STATE_USER_QUERY_ONLINE 3 		// 获取玩家在线状态回包
#define PROTOCOL_RSP_SUBCMD_STATE_USER_GET_ONLINE_LIST 4	// 获取在线玩家列表回包
#define PROTOCOL_RSP_SUBCMD_STATE_USER_GET_MIN_LOAD_LOGIN 5	// 最小负载login回包
#define PROTOCOL_RSP_SUBCMD_STATE_USER_SET_SYNC 6 			// 设置玩家同步状态回包
#define PROTOCOL_RSP_SUBCMD_STATE_USER_DECR_OPENID_REF 7 	// 减少openid引用次数回包
#define PROTOCOL_RSP_SUBCMD_STATE_USER_GET_MIN_LOAD_LOGIN_BY_UID 8	// 使用uid分配最小负载login回包
#define PROTOCOL_RSP_SUBCMD_STATE_USER_GET_ONLINE_OPENID 9	// 获取在线玩家openId回包
#define PROTOCOL_RSP_SUBCMD_STATE_USER_DELETE 10 			// 删除玩家状态回包
/*-----------------任务相关协议------------------*/
#define PROTOCOL_CMD_TASK 9
#define PROTOCOL_SUBCMD_TASK_LIST 1
#define PROTOCOL_SUBCMD_TASK_SUBMIT 2
#define PROTOCOL_SUBCMD_TASK_FINISH 3
#define PROTOCOL_SUBCMD_TASK_COUNT 4

#define PROTOCOL_RSP_SUBCMD_USERINFO 1

/*-----------------战报相关协议------------------*/
#define PROTOCOL_CMD_VIDEO 11
#define PROTOCOL_SUBCMD_VIDEOLIST 1
#define PROTOCOL_SUBCMD_VIDEADD 2
#define PROTOCOL_SUBCMD_NEW_TIPS 3

#define PROTOCOL_RSP_SUBCMD_VIDEOLIST 1
/*-----------------邮件相关协议------------------*/
#define PROTOCOL_CMD_EMAIL 12
#define PROTOCOL_SUBCMD_EMAIL_REC_BOX 1
#define PROTOCOL_SUBCMD_EMAIL_SEND_BOX  2
#define PROTOCOL_SUBCMD_EMAIL_DEL 3
#define PROTOCOL_SUBCMD_EMAIL_READ 4
#define PROTOCOL_SUBCMD_EMAIL_GET 5
#define PROTOCOL_SUBCMD_EMAIL_WRITE 6
#define PROTOCOL_CMD_NEW_MAIL 7
/*-----------------推图相关协议------------------*/
#define PROTOCOL_CMD_GATE 13
#define PROTOCOL_SUBCMD_GATE_INDEX 1
#define PROTOCOL_SUBCMD_GATE_LIST 2
#define PROTOCOL_SUBCMD_GATE_OVER 3
#define PROTOCOL_SUBCMD_GATE_ROBOT 4
#define PROTOCOL_SUBCMD_GATE_ROBOT_CONTINUE 6
#define PROTOCOL_SUBCMD_GATE_REWARD 7
#define PROTOCOL_SUBCMD_GATE_GET_TREASURE_INFO 8	// 获取关卡宝箱信息
#define PROTOCOL_SUBCMD_GATE_SET_TREASURE_INFO 9	// 设置关卡宝箱信息
#define PROTOCOL_SUBCMD_GATE_GET_STAR_INFO 10	// 关卡星级信息
#define PROTOCOL_SUBCMD_GATE_ROBOT_ACC 11		// 扫荡挂机加速
#define PROTOCOL_SUBCMD_GATE_RAND_CARD_AWARD 12
#define PROTOCOL_SUBCMD_GATE_RAND_CARD_AWARD_IN_BAG 13
#define PROTOCOL_SUBCMD_GATE_KILL_NUMBER 14
#define	PROTOCOL_SUBCMD_GATE_GET_STAR_BOX_INFO 15		//获取星级宝箱信息
#define	PROTOCOL_SUBCMD_GATE_GET_STAR_BOX_REWARD 16		//获取星级宝箱奖励
#define PROTOCOL_SUBCMD_GATE_GET_ALL_BOX_FLAG 17		//获取所有宝箱是否开启标志位

#define PROTOCOL_SUBCMD_GATE_DEFEND_RET 51
#define PROTOCOL_SUBCMD_GATE_DEFEND_ADD_EXP 52

//战役相关
#define PROTOCOL_SUBCMD_BATTLE_LIST 50
#define PROTOCOL_SUBCMD_BATTLE_RET 53
#define	PROTOCOL_SUBCMD_SET_SPEED_UP_FLAG 54			//战役加速标志位

//护卫副本相关
#define PROTOCOL_SUBCMD_DEFEND_LIST 60
#define PROTOCOL_SUBCMD_DEFEND_RET 61


#define PROTOCOL_RSP_SUBCMD_GATE_INDEX 1
#define PROTOCOL_RSP_SUBCMD_GATE_LIST 2
#define PROTOCOL_RSP_SUBCMD_GATE_OVER 3
#define PROTOCOL_RSP_SUBCMD_GATE_ROBOT 4
#define PROTOCOL_RSP_SUBCMD_GATE_ROBOT_REWARD 5 	// 每次挂机结果
#define PROTOCOL_RSP_SUBCMD_GATE_ROBOT_CONTINUE 6 	// 登录挂机结果
#define PROTOCOL_RSP_SUBCMD_GATE_GET_TREASURE_INFO 8	// 获取关卡宝箱信息回包
#define PROTOCOL_RSP_SUBCMD_GATE_SET_TREASURE_INFO 9	// 设置关卡宝箱信息回包
#define PROTOCOL_RSP_SUBCMD_GATE_GET_STAR_INFO 10	// 关卡星级信息回包
/*-----------------排行榜相关协议------------------*/
#define PROTOCOL_CMD_RANK 14

#define PROTOCOL_SUBCMD_RANK_EXP 1
#define PROTOCOL_SUBCMD_RANK_COMBAT 2
#define PROTOCOL_SUBCMD_RANK_TRANSPORT 3
#define PROTOCOL_SUBCMD_RANK_NOTICE 4
#define PROTOCOL_SUBCMD_RANK_REPORT 5

/*-----------------运输列表协议------------------*/
#define PROTOCOL_CMD_TRANSPORT 15
#define PROTOCOL_SUBCMD_TRANSPORT_START 1
#define PROTOCOL_SUBCMD_TRANSPORT_SEARCH 2
#define PROTOCOL_SUBCMD_TRANSPORT_ROB 3
#define PROTOCOL_SUBCMD_TRANSPORT_SPEED_UP 4
#define PROTOCOL_SUBCMD_TRANSPORT_TARGET 5

/*-----------------奖励相关协议------------------*/
#define PROTOCOL_CMD_REWARD 16
#define PROTOCOL_SUBCMD_REWARD_QUERY 1					//查询
#define PROTOCOL_SUBCMD_REWARD_GET 2					//领奖
#define PROTOCOL_SUBCMD_REWARD_QUERY_WARRIOR_GATE 3		//查询名将试练奖励

#define PROTOCOL_RSP_SUBCMD_REWARD_LIST 1				//查询
#define PROTOCOL_RSP_SUBCMD_REWARD_FLAG 2				//查询
#define PROTOCOL_RSP_SUBCMD_REWARD_QUERY_WARRIOR_GATE 3	//查询名将试练奖励
/*--------------座驾相关协议--------------------*/
#define PROTOCOL_CMD_RIDE  17
#define PROTOCOL_SUBCMD_RIDE_QUERY_ALL 1 				// 查询所有座驾信息
#define PROTOCOL_SUBCMD_RIDE_LEVEL_UP 2 				// 查询所有座驾升级
#define PROTOCOL_SUBCMD_RIDE_QUALITY 3	 				// 查询所有座驾改造
#define PROTOCOL_SUBCMD_RIDE_QUERY_ONE 4 				// 查询一个座驾信息

#define PROTOCOL_RSP_SUBCMD_RIDE_QUERY_ALL 1 			// 查询所有座驾信息回包
#define PROTOCOL_RSP_SUBCMD_RIDE_LEVEL_UP 2 			// 查询所有座驾升级回包
#define PROTOCOL_RSP_SUBCMD_RIDE_QUALITY 3	 			// 查询所有座驾改造回包
#define PROTOCOL_RSP_SUBCMD_RIDE_QUERY_ONE 4 			// 查询一个座驾信息回包
/*-------------每日任务相关协议----------------*/
#define PROTOCOL_CMD_DAILY_TASK  18
#define PROTOCOL_SUBCMD_DAILY_TASK_PROCESS  1 			// 进度
#define PROTOCOL_SUBCMD_DAILY_TASK_ACTIVE  2 			// 活跃度
#define PROTOCOL_SUBCMD_DAILY_TASK_SYN_CHAT  3 			// 聊天同步到服务器
#define PROTOCOL_SUBCMD_DAILY_TASK_FINISH  4			// 任务完成
#define PROTOCOL_SUBCMD_DAILY_TASK_REWARD  5			// 任务奖励

#define PROTOCOL_RSP_SUBCMD_DAILY_TASK_PROCESS  1 		// 进度回包
#define PROTOCOL_RSP_SUBCMD_DAILY_TASK_ACTIVE  2 		// 活跃度回包
#define PROTOCOL_RSP_SUBCMD_DAILY_TASK_SYN_CHAT  3 		// 聊天同步到服务器回包
#define PROTOCOL_RSP_SUBCMD_DAILY_TASK_FINISH 4

/**************技能开始*****************************/
#define PROTOCOL_CMD_SKILL  19
#define PROTOCOL_SUBCMD_SKILL_QUERY  1 					// 查询
#define PROTOCOL_SUBCMD_SKILL_UP 2 						// 升级
#define PROTOCOL_SUBCMD_SKILL_USE 3 					// 技能使用
#define PROTOCOL_SUBCMD_SKILL_POINTS 4 					// 技能点
#define PROTOCOL_SUBCMD_COST_SKILL_TIMES 6 				// 大招使用次数
#define PROTOCOL_SUBCMD_SYNC_TO_BATTLE 7 				// 同步到battle
#define PROTOCOL_SUBCMD_SET_SKILL_POS 8
#define PROTOCOL_SUBCMD_BUY_QUEUE 9
#define PROTOCOL_SUBCMD_SKILL_UP_ACC 10
#define PROTOCOL_SUBCMD_SKILL_UP_RESULT 11
#define PROTOCOL_SUBCMD_SKILL_EFFECT 12
#define PROTOCOL_SUBCMD_SKILL_STATUS 13

#define PROTOCOL_RSP_SUBCMD_SKILL_USE 5 				// 技能使用
/**************技能结束*****************************/


/*************杂项相关 如登陆活动类小活动 begin*****************/

#define PROTOCOL_CMD_MISC  20
#define PROTOCOL_SUBCMD_TOTAL_LOGIN_INFO  1 			//累计登陆信息
#define PROTOCOL_SUBCMD_TOTAL_LOGIN_REWARD 2 			//累计登陆领奖
#define PROTOCOL_SUBCMD_CON_LOGIN_INFO  3 				//连续登陆信息
#define PROTOCOL_SUBCMD_CON_LOGIN_REWARD_PRE  4 		//连续登陆抽奖
#define PROTOCOL_SUBCMD_MISC_ACT_LIST  5 				//连续登陆抽奖
#define PROTOCOL_SUBCMD_CON_LOGIN_REWARD 6
#define PROTOCOL_SUBCMD_QUERY_ACTIVITY_BOSS 7 			//boss战活动信息
#define PROTOCOL_SUBCMD_YELLOW_AWARD_QUERY  8			//黄钻每日礼品领取
#define PROTOCOL_SUBCMD_YELLOW_AWARD_GET  9				//黄钻每日礼品领取
#define PROTOCOL_SUBCMD_GENERAL_DATA  10				//通用数据
#define PROTOCOL_SUBCMD_CHAT_AD 11
#define PROTOCOL_SUBCMD_NEW_SERVER_INFO 12
#define PROTOCOL_SUBCMD_NEW_SERVER_REWARD 13
#define PROTOCOL_SUBCMD_NEW_SERVER_COMBAT_ACT 14
#define PROTOCOL_SUBCMD_NEW_SERVER_STONE_ACT 15
#define PROTOCOL_SUBCMD_NEW_SERVER_STRENGTH_ACT 16
#define PROTOCOL_SUBCMD_BLUE_DAILY_AWARD_GET  17		//蓝钻每日礼包
#define PROTOCOL_SUBCMD_BLUE_LEVEL_UP_AWARD_GET  18		//蓝钻等级成长礼包
#define PROTOCOL_SUBCMD_MISC_DAILY_CHARGE_QUERY 19
#define PROTOCOL_SUBCMD_MISC_SEVEN_FOUNDS_QUERY 20
#define PROTOCOL_SUBCMD_MISC_SEVEN_FOUNDS_BUY 21
#define PROTOCOL_SUBCMD_MISC_SEVEN_FOUNDS_AWARD 22
#define PROTOCOL_SUBCMD_QQGAME_DAILY_LOGIN_REWARD 23 	//大厅每日登陆礼包
#define PROTOCOL_SUBCMD_QQGAME_GROW_REWARD 24 	//大厅成长礼包
#define PROTOCOL_SUBCMD_QQGAME_QUERY_LOGIN_REWARD 25 	//查询大厅特权
#define PROTOCOL_SUBCMD_QQGAME_NEW_REWARD 26 	//大厅新手礼包
#define PROTOCOL_SUBCMD_QZONE_DAILY_LOGIN_REWARD 27 	//qzone每日登陆礼包
#define PROTOCOL_SUBCMD_QZONE_GROW_REWARD 28 	//qzone成长礼包
#define PROTOCOL_SUBCMD_QZONE_QUERY_LOGIN_REWARD 29 	//查询qzone特权
#define PROTOCOL_SUBCMD_QZONE_NEW_REWARD 30 	//qzone新手礼包
#define PROTOCOL_SUBCMD_MISC_DAILY_GROUP_BUY_QUERY 31	//每日团购查询
#define PROTOCOL_SUBCMD_MISC_DAILY_GROUP_BUY 32			//每日团购购买
#define PROTOCOL_SUBCMD_MISC_DAILY_GROUP_BUY_AWARD 33	//每日团购奖励
#define PROTOCOL_SUBCMD_MISC_MYSTICAL_SHOP_QUERY 34   //神秘商店查询
#define PROTOCOL_SUBCMD_MISC_MYSTICAL_SHOP_BUY 35   	//神秘商店购买
#define PROTOCOL_SUBCMD_MISC_GET_NOTICE_STATE 36   		//查询公告状态
#define PROTOCOL_SUBCMD_MISC_SET_NOTICE_STATE 37   		//设置公告状态
#define PROTOCOL_SUBCMD_MISC_SET_COMBAT_DETECT_POINT 38 //设置战力检测分数
#define PROTOCOL_SUBCMD_NEW_SERVER_ALLIANCE_ACT 40
#define PROTOCOL_SUBCMD_NEW_SERVER_ROBOT_ACT 41
#define PROTOCOL_SUBCMD_NEW_SERVER_HERO_TAR_ACT 42

#define PROTOCOL_SUBCMD_MISC_BARBARIAN_CHALLENGE 43
#define PROTOCOL_SUBCMD_MISC_BARBARIAN_ALLIANCE_RANK 44
#define PROTOCOL_SUBCMD_MISC_BARBARIAN_ALLIANCE_MEM_RANK 45
#define PROTOCOL_SUBCMD_MISC_BARBARIAN_CHALLENGE_TIMES 46

#define PROTOCOL_SUBCMD_MISC_SHOOT_QUERY 47
#define PROTOCOL_SUBCMD_MISC_SHOOT_RANK 48
#define PROTOCOL_SUBCMD_MISC_SHOOT_INFO 49
#define PROTOCOL_SUBCMD_MISC_SHOOT_HIT 50
#define PROTOCOL_SUBCMD_MISC_SHOOT_HIT_100 51
#define PROTOCOL_SUBCMD_MISC_SHOOT_DAILY_AWARD 52
#define PROTOCOL_SUBCMD_MISC_SHOOT_CAST 55

#define PROTOCOL_SUBCMD_MISC_COST_QUERY 53
#define PROTOCOL_SUBCMD_MISC_COST_BUY 54

#define PROTOCOL_SUBCMD_MISC_GOLDEN_EGG_QUERY 56
#define PROTOCOL_SUBCMD_MISC_GOLDEN_EGG_HIT 57
#define PROTOCOL_SUBCMD_MISC_GOLDEN_EGG_REFRESH 58
#define PROTOCOL_SUBCMD_MISC_GOLDEN_EGG_CAST 59

#define PROTOCOL_SUBCMD_MISC_ALLIANCE_CHARGE_QUERY 60
#define PROTOCOL_SUBCMD_MISC_ALLIANCE_CHARGE_AWARD 61
#define PROTOCOL_SUBCMD_MISC_ALLIANCE_CHARGE_SALE 62

#define PROTOCOL_SUBCMD_MISC_NEWYEAR_FUNDS 63

#define PROTOCOL_SUBCMD_MISC_MONTH_CHARGE_QUERY 64
#define PROTOCOL_SUBCMD_MISC_MONTH_CHARGE_AWARD 65

#define PROTOCOL_SUBCMD_MISC_HERO_EXCHANGE_QUERY 66
#define PROTOCOL_SUBCMD_MISC_HERO_EXCHANGE 67

#define PROTOCOL_SUBCMD_MISC_MATERIAL_SALE_QUERY 68
#define PROTOCOL_SUBCMD_MISC_MATERIAL_SALE_BUY 69

#define PROTOCOL_SUBCMD_MISC_MATERIAL_WHEEL_QUERY 70
#define PROTOCOL_SUBCMD_MISC_MATERIAL_WHEEL_BUY_TIMES 71
#define PROTOCOL_SUBCMD_MISC_MATERIAL_WHEEL_HIT 72
#define PROTOCOL_SUBCMD_MISC_MATERIAL_WHEEL_AWARD 73

#define PROTOCOL_SUBCMD_MISC_CHARGE_RETURN_QUERY 74
#define PROTOCOL_SUBCMD_MISC_CHARGE_RETURN_BUY 75

#define PROTOCOL_SUBCMD_MISC_MAGIC_SQUARE_QUERY 76
#define PROTOCOL_SUBCMD_MISC_MAGIC_SQUARE_UP 77
#define PROTOCOL_SUBCMD_MISC_MAGIC_SQUARE_UP_ALL 78

#define PROTOCOL_SUBCMD_MISC_BUSINESS_QUERY 79
#define PROTOCOL_SUBCMD_MISC_BUSINESS_BUY 80

#define PROTOCOL_SUBCMD_MISC_WAR_KING_QUERY 81
#define PROTOCOL_SUBCMD_MISC_WAR_KING_BUY 82
#define PROTOCOL_SUBCMD_MISC_WAR_KING_AWARD 83

#define PROTOCOL_SUBCMD_MISC_EXP_TIME 84

#define PROTOCOL_SUBCMD_MISC_CROSS_SHOOT_QUERY 85
#define PROTOCOL_SUBCMD_MISC_CROSS_SHOOT_RANK 86
#define PROTOCOL_SUBCMD_MISC_CROSS_SHOOT_INFO 87
#define PROTOCOL_SUBCMD_MISC_CROSS_SHOOT_HIT 88
#define PROTOCOL_SUBCMD_MISC_CROSS_SHOOT_HIT_100 89
#define PROTOCOL_SUBCMD_MISC_CROSS_SHOOT_DAILY_AWARD 90
#define PROTOCOL_SUBCMD_MISC_CROSS_SHOOT_CAST 91

#define PROTOCOL_SUBCMD_MISC_DAILY_PAY_CASH 92

#define PROTOCOL_SUBCMD_MISC_CHARGE_QUERY 93

#define PROTOCOL_SUBCMD_MISC_SOLDIER_QUERY 94
#define PROTOCOL_SUBCMD_MISC_SOLDIER_REFRESH 95

#define PROTOCOL_SUBCMD_MISC_FIRST_CHARGE 96
#define PROTOCOL_SUBCMD_MISC_REST_TIME 97
#define PROTOCOL_SUBCMD_MISC_SOLDIER_ADDITIONAL 98

#define PROTOCOL_SUBCMD_MISC_ZHUANPAN 99
#define PROTOCOL_SUBCMD_MISC_ZHUANPAN_FREE_COUNT 100

#define PROTOCOL_SUBCMD_MISC_SYSTEM_MSG 101
#define PROTOCOL_SUBCMD_MISC_FUND_INFO 102
#define PROTOCOL_SUBCMD_MISC_FUND_REWARD 103

/*************杂项相关 如登陆活动类小活动 end *****************/


/*-------------联盟相关协议----------------*/
#define PROTOCOL_CMD_LEAGUE  21
#define PROTOCOL_SUBCMD_LEAGUE_QUERY_INFO 1 			//联盟信息查询
#define PROTOCOL_SUBCMD_LEAGUE_QUERY_MEMBER 2 			//查询联盟成员
#define PROTOCOL_SUBCMD_LEAGUE_UPDATE_NOTICE 3 			//修改公告
#define PROTOCOL_SUBCMD_LEAGUE_QUERY_VOTE 4 			//查询选举信息
#define PROTOCOL_SUBCMD_LEAGUE_VOTE 5 					//查询投票
#define PROTOCOL_SUBCMD_LEAGUE_QUERY_VOTE_HISTORY 6 	//历届排名
#define PROTOCOL_SUBCMD_LEAGUE_QUERY_CONTRIBUTE 7 		//查询捐献
#define PROTOCOL_SUBCMD_LEAGUE_CONTRIBUTE 8 			//捐献
#define PROTOCOL_SUBCMD_LEAGUE_JOIN 9 					//申请
#define PROTOCOL_SUBCMD_LEAGUE_LEVELUP 10 				//联盟升级
#define PROTOCOL_SUBCMD_LEAGUE_MEMBER_QUERY_TECH 11 	//联盟成员科技查询
#define PROTOCOL_SUBCMD_LEAGUE_MEMBER_TECH_UP 12 		//联盟成员科技升级
//#define PROTOCOL_SUBCMD_LEAGUE_CHANGE_ID 13 			//to login:玩家联盟ID改变
#define PROTOCOL_SUBCMD_LEAGUE_CHANGE_RESOURCE 14 		//to login:玩家资源变化
#define PROTOCOL_SUBCMD_LEAGUE_CHANGE_MONEY 15 			//to login:玩家金钱变化
//#define PROTOCOL_SUBCMD_LEAGUE_ONLINE 16 				//上线通知
//#define PROTOCOL_SUBCMD_LEAGUE_OFFLINE 17 				//下线通知
//#define PROTOCOL_SUBCMD_LEAGUE_UPDATE_USER_COMBAT 18 	//更新玩家战力
#define PROTOCOL_SUBCMD_LEAGUE_APPOINT_OFFICE 19		//任命官职
#define PROTOCOL_SUBCMD_LEAGUE_GET_SALARY 20			//领薪水
#define PROTOCOL_SUBCMD_LEAGUE_QUERY_MEMBER_SELF_INFO	21	//查询联盟成员个人信息
//#define PROTOCOL_SUBCMD_LEAGUE_QUERY_TECH_PROPS_ADD	22	//查询联盟科技属性加成
//#define PROTOCOL_SUBCMD_LEAGUE_CONTRIBUTE_CHANGE 23		//联盟数量变化
#define PROTOCOL_SUBCMD_LEAGUE_CREATE 24				//创建联盟
#define PROTOCOL_SUBCMD_LEAGUE_APPLY_JOIN 25			//申请加入联盟
#define PROTOCOL_SUBCMD_LEAGUE_QUERY_KINGDOM_ALLIANCE 26	//查询本国所有联盟
#define PROTOCOL_SUBCMD_LEAGUE_QUERY_ALLIANCE_RECV_REQUEST 27	//查询联盟收到的请求
#define PROTOCOL_SUBCMD_LEAGUE_CANCEL_APPLY_JOIN 28	//查询联盟收到的请求
#define PROTOCOL_SUBCMD_LEAGUE_ACCEPT_USER_APPLY_JOIN 29	//接收玩家加入联盟申请
#define PROTOCOL_SUBCMD_LEAGUE_REJECT_USER_APPLY_JOIN 30	//拒绝玩家加入联盟申请
#define PROTOCOL_SUBCMD_LEAGUE_QUIT 31	//退出联盟
#define PROTOCOL_SUBCMD_LEAGUE_KICK 32	//盟主踢人
//#define PROTOCOL_SUBCMD_LEAGUE_QUERY_ALLIANCE_ID 33			//查询玩家联盟ID
#define PROTOCOL_SUBCMD_LEAGUE_RECRUIT 34					//联盟招募
#define PROTOCOL_SUBCMD_LEAGUE_ACCEPT_INVITE 35				//接受邀请
#define PROTOCOL_SUBCMD_LEAGUE_QUERY_INVITE 36				//查询邀请
#define PROTOCOL_SUBCMD_LEAGUE_DISSOLVE 37					//联盟解散
#define PROTOCOL_SUBCMD_LEAGUE_QUERY_PEAK 38 				//巅峰人物
#define PROTOCOL_SUBCMD_LEAGUE_QUERY_TECH 39 				//联盟科技查询
#define PROTOCOL_SUBCMD_LEAGUE_TECH_UP 40 					//联盟科技升级
#define PROTOCOL_SUBCMD_LEAGUE_QUERY_ALL_ALLIANCE 41		//查询所有联盟
#define PROTOCOL_SUBCMD_LEAGUE_REVENGE_QUERY 42

#define PROTOCOL_RSP_SUBCMD_LEAGUE_QUERY_INFO 1			//
#define PROTOCOL_RSP_SUBCMD_LEAGUE_QUERY_MEMBER 2 		//
#define PROTOCOL_RSP_SUBCMD_LEAGUE_QUERY_VOTE 4 		//查询选举信息回包
#define PROTOCOL_RSP_SUBCMD_LEAGUE_QUERY_VOTE_HISTORY 6 //历届排名回包
#define PROTOCOL_RSP_SUBCMD_LEAGUE_QUERY_CONTRIBUTE 7 	//查询捐献
#define PROTOCOL_RSP_SUBCMD_LEAGUE_CONTRIBUTE 8 		//捐献回包
#define PROTOCOL_RSP_SUBCMD_LEAGUE_MEMBER_QUERY_TECH 11 		//
#define PROTOCOL_RSP_SUBCMD_LEAGUE_MEMBER_TECH_UP 12 			//科技升级
//#define PROTOCOL_RSP_SUBCMD_LEAGUE_ONLINE 16 			//上线通知
//#define PROTOCOL_RSP_SUBCMD_LEAGUE_OFFLINE 17 			//下线通知
//#define PROTOCOL_RSP_SUBCMD_LEAGUE_UPDATE_USER_COMBAT 18 		//更新玩家战力
#define PROTOCOL_RSP_SUBCMD_LEAGUE_APPOINT_OFFICE 19 	//任命官职
#define PROTOCOL_RSP_SUBCMD_LEAGUE_GET_SALARY 20		//领薪水
#define PROTOCOL_RSP_SUBCMD_LEAGUE_QUERY_MEMBER_SELF_INFO	21	//查询联盟成员个人信息
//#define PROTOCOL_RSP_SUBCMD_LEAGUE_QUERY_TECH_PROPS_ADD	22	//查询联盟科技属性加成
#define PROTOCOL_RSP_SUBCMD_LEAGUE_CREATE 24				//创建联盟回包
#define PROTOCOL_RSP_SUBCMD_LEAGUE_APPLY_JOIN 25			//申请加入联盟回包
#define PROTOCOL_RSP_SUBCMD_LEAGUE_QUERY_KINGDOM_ALLIANCE 26	//查询本国所有联盟回包
#define PROTOCOL_RSP_SUBCMD_LEAGUE_QUERY_ALLIANCE_RECV_REQUEST 27	//查询联盟收到的请求回包
#define PROTOCOL_RSP_SUBCMD_LEAGUE_CANCEL_APPLY_JOIN 28	//查询联盟收到的请求
#define PROTOCOL_RSP_SUBCMD_LEAGUE_ACCEPT_USER_APPLY_JOIN 29	//接收玩家加入联盟申请
#define PROTOCOL_RSP_SUBCMD_LEAGUE_REJECT_USER_APPLY_JOIN 30	//拒绝玩家加入联盟申请
#define PROTOCOL_RSP_SUBCMD_LEAGUE_QUIT 31	//退出联盟
#define PROTOCOL_RSP_SUBCMD_LEAGUE_KICK 32	//盟主踢人
//#define PROTOCOL_RSP_SUBCMD_LEAGUE_QUERY_ALLIANCE_ID 33			//查询玩家联盟ID
#define PROTOCOL_RSP_SUBCMD_LEAGUE_RECRUIT 34					//联盟招募
#define PROTOCOL_RSP_SUBCMD_LEAGUE_ACCEPT_INVITE 35				//接受邀请
#define PROTOCOL_RSP_SUBCMD_LEAGUE_QUERY_INVITE 36				//查询邀请
#define PROTOCOL_RSP_SUBCMD_LEAGUE_DISSOLVE 37					//联盟解散
#define PROTOCOL_RSP_SUBCMD_LEAGUE_QUERY_PEAK 38 				//巅峰人物
#define PROTOCOL_RSP_SUBCMD_LEAGUE_QUERY_TECH 39 				//联盟科技查询
#define PROTOCOL_RSP_SUBCMD_LEAGUE_TECH_UP 40 					//联盟科技升级
#define PROTOCOL_RSP_SUBCMD_LEAGUE_QUERY_ALL_ALLIANCE 41		//查询所有联盟回包



// 联盟回包返回值
#define PROTOCOL_RET_LEAGUE_SUCCESS 0 			// 操作成功
#define PROTOCOL_RET_LEAGUE_FAIL 1 				// 操作失败
#define PROTOCOL_RET_LEAGUE_ALLIANCE_NOT_EXIST 2	// 联盟不存在
#define PROTOCOL_RET_LEAGUE_MEMBER_OUT_OF_LIMIT 3	// 联盟成员人数满
#define PROTOCOL_RET_LEAGUE_ALLIANCE_NAME_TOO_LONG 4	// 联盟名过长
#define PROTOCOL_RET_LEAGUE_ALLIANCE_NAME_EXIST 5		// 联盟名已存在
#define PROTOCOL_RET_LEAGUE_ALLIANCE_NAME_SENS 6	// 联盟名含敏感关键字
#define PROTOCOL_RET_LEAGUE_ALLIANCE_DESC_TOO_LONG 7	// 联盟简介无效
#define PROTOCOL_RET_LEAGUE_ALLIANCE_DESC_SENs 8	// 联盟简介含敏感关键字
#define PROTOCOL_RET_LEAGUE_ALREADY_IN_ALLIANCE 9	// 已经加入联盟
#define PROTOCOL_RET_LEAGUE_RESOURCE_NOT_ENOUGH	10	// 资源不足
#define PROTOCOL_RET_LEAGUE_COINS_NOT_ENOUGH	11	// 金币不足
#define PROTOCOL_RET_LEAGUE_CASH_NOT_ENOUGH	12		// 钻石不足
#define PROTOCOL_RET_LEAGUE_ALLIANCE_EXIST 13	// 联盟已存在
#define PROTOCOL_RET_LEAGUE_QUIT_TIME_IN_24_HOUR 14	// 退出联盟不到24小时
#define PROTOCOL_RET_LEAGUE_IN_DIFF_KINGDOM 15		// 不同国家
#define PROTOCOL_RET_LEAGUE_USER_NOT_EXIST 16	// 玩家不存在
#define PROTOCOL_RET_LEAGUE_ALREADY_APPLY_JOIN 17 // 已申请加入

/********************士兵开始*************************/
#define PROTOCOL_CMD_SOLDIER  22

#define PROTOCOL_SUBCMD_SOLDIER_LIST 1					//士兵列表
#define PROTOCOL_SUBCMD_SOLDIER_UPGRADE 2				//士兵升级
#define PROTOCOL_SUBCMD_SOLDIER_UPGRADE_FINISH_NOW 3 	//士兵升级立即完成
#define PROTOCOL_SUBCMD_SOLDIER_TRAIN 4					//士兵训练
#define PROTOCOL_SUBCMD_SOLDIER_TRAIN_FINISH_NOW 5 		//士兵训练立即完成
#define PROTOCOL_SUBCMD_SOLDIER_INFO 6			 		//士兵信息
#define PROTOCOL_SUBCMD_SOLDIER_TRAIN_LIST 7			//士兵训练列表
#define PROTOCOL_SUBCMD_SOLDIER_UPGRADE_OVER 8			//士兵升级结束
#define PROTOCOL_SUBCMD_SOLDIER_TRAIN_SLOT_OPEN 9		//士兵训练槽位打开
#define PROTOCOL_SUBCMD_SOLDIER_STATION_QUERY 10
#define PROTOCOL_SUBCMD_SOLDIER_STATION_ADD 11
#define PROTOCOL_SUBCMD_SOLDIER_STATION_DEL 12
#define PROTOCOL_SUBCMD_SOLDIER_ALLIANCE_STATION_ADD 13
#define PROTOCOL_SUBCMD_SOLDIER_ALLIANCE_STATION_QUERY 14
#define PROTOCOL_SUBCMD_SOLDIER_TRAIN_CANCEL 15
#define PROTOCOL_SUBCMD_SOLDIER_STRONG 16
#define PROTOCOL_SUBCMD_SOLDIER_RECOVER_TRAIN_INFO 17
#define PROTOCOL_SUBCMD_SOLDIER_RECOVER_TRAIN_DEL 18
#define PROTOCOL_SUBCMD_SOLDIER_RECOVER_TRAIN_ADD 19
#define PROTOCOL_SUBCMD_SOLDIER_STAR 20
#define PROTOCOL_SUBCMD_SOLDIER_BOX_SCORE 21
#define PROTOCOL_SUBCMD_SOLDIER_ADD_BOX_SCORE 22
#define PROTOCOL_SUBCMD_SOLDIER_BOX_REWARD 23

#define PROTOCOL_RSP_SUBCMD_SOLDIER_LIST 1				//士兵列表
#define PROTOCOL_RSP_SUBCMD_SOLDIER_UPGRADE 2			//士兵升级
#define PROTOCOL_RSP_SUBCMD_SOLDIER_UPGRADE_FINISH_NOW 3 //士兵升级立即完成
#define PROTOCOL_RSP_SUBCMD_SOLDIER_TRAIN 4				//士兵训练
#define PROTOCOL_RSP_SUBCMD_SOLDIER_TRAIN_FINISH_NOW 5 	//士兵训练立即完成
#define PROTOCOL_RSP_SUBCMD_SOLDIER_INFO 6			 	//士兵信息
#define PROTOCOL_RSP_SUBCMD_SOLDIER_TRAIN_LIST 7		//士兵训练列表
#define PROTOCOL_RSP_SUBCMD_SOLDIER_UPGRADE_OVER 8		//士兵升级结束
#define PROTOCOL_RSP_SUBCMD_SOLDIER_TRAIN_SLOT_OPEN 9	//士兵训练槽位打开

// 英雄回包返回值
#define PROTOCOL_RET_SOLDIER_SUCCESS 0 					//操作成功
#define PROTOCOL_RET_SOLDIER_FAIL 1 					//操作失败
#define PROTOCOL_RET_SOLDIER_PACKET_ERROR 2 			//收包数据有错
#define PROTOCOL_RET_SOLDIER_NOT_EXIST 3 				//士兵不存在
#define PROTOCOL_RET_SOLDIER_USER_LEVEL_LIMIT 4 		//玩家等级限制

/********************社交系统开始*************************/
#define PROTOCOL_CMD_SOCIAL  23
#define PROTOCOL_SUBCMD_SOCIAL_FRIEND_QUERY 1			//查询好友列表
#define PROTOCOL_SUBCMD_SOCIAL_FRIEND_REQUEST_QUERY 2	//查询请求列表
#define PROTOCOL_SUBCMD_SOCIAL_FRIEND_ADD_REQUEST 4		//添加好友
#define PROTOCOL_SUBCMD_SOCIAL_FRIEND_ADD_RESPONSE 5	//添加好友应答
#define PROTOCOL_SUBCMD_SOCIAL_FRIEND_DELETE 6			//删除好友
#define PROTOCOL_SUBCMD_SOCIAL_FRIEND_NEW 7				//有新好友请求
#define PROTOCOL_SUBCMD_SOCIAL_FRIEND_RECOMMEND 8		//查询推荐列表
#define PROTOCOL_SUBCMD_SOCIAL_FRIEND_RESULT 9			//添加好友结果
#define PROTOCOL_SUBCMD_SOCIAL_FRIEND_HELP 10			//帮助好友
#define PROTOCOL_SUBCMD_SOCIAL_FRIEND_GIFT 11			//

// 社交回包返回值
#define PROTOCOL_RET_SOCIAL_SUCCESS 0 			// 操作成功
#define PROTOCOL_RET_SOCIAL_FAIL 1 				// 操作失败
#define PROTOCOL_RET_SOCIAL_PACKET_ERROR 2 		// 收包数据有错
#define PROTOCOL_RET_SOCIAL_ACC_LIMIT_ONE_FRIEND_ONE_DAY 3 		// 单个好友加速次数上限
#define PROTOCOL_RET_SOCIAL_PLAYER_NOT_EXIST 4 		// 角色不存在
#define PROTOCOL_RET_SOCIAL_SAVE_FAIL 5 		// 存档失败
#define PROTOCOL_RET_SOCIAL_NO_FRIEND 6 		// 没朋友
#define PROTOCOL_RET_SOCIAL_NO_ACC_BUILDING 7 	// 无可加速建筑
#define PROTOCOL_RET_SOCIAL_DB_ERR 8 			// 数据库错误
#define PROTOCOL_RET_SOCIAL_PLAYER_LEVEL_LIMIT 9	// 玩家等级不够
#define PROTOCOL_RET_SOCIAL_HELP_ACTIVE_LIMIT 10	// 帮助好友次数达上限
#define PROTOCOL_RET_SOCIAL_HELP_PASSIVE_LIMIT 11	// 被好友次帮助次数达上限

/********************社交系统结束*************************/

/********************BUFF开始*************************/
#define PROTOCOL_CMD_BUFF  24
#define PROTOCOL_SUBCMD_ADD_BUFF 1					//查询排行
#define PROTOCOL_SUBCMD_REMOVE_BUFF  2					//参加
//#define PROTOCOL_SUBCMD_INVADE_OVER  3				//结束
/********************BUFF活动结束*************************/

/********************好友邀请与分享系统开始*********************/
#define PROTOCOL_CMD_INVITE  25
#define PROTOCOL_SUBCMD_INVITE_REQUEST 1				//邀请发送
#define PROTOCOL_SUBCMD_INVITE_SUCCESS 2				//邀请成功
#define PROTOCOL_SUBCMD_INVITE_QUERY  3					//邀请查询
#define PROTOCOL_SUBCMD_INVITE_AWARD  4					//邀请领奖
#define PROTOCOL_SUBCMD_SHARE_SUCCESS 5					//分享成功
#define PROTOCOL_SUBCMD_SHARE_REWARD 6					//分享奖励
/********************好友邀请与分享系统结束**********************/

/*-----------------名将试练相关协议------------------*/
#define PROTOCOL_CMD_WARRIOR_GATE 26
#define PROTOCOL_SUBCMD_WARRIOR_GATE_INDEX 1
#define PROTOCOL_SUBCMD_WARRIOR_GATE_LIST 2
#define PROTOCOL_SUBCMD_WARRIOR_GATE_OVER 3
#define PROTOCOL_SUBCMD_WARRIOR_GATE_ROBOT 4
#define PROTOCOL_SUBCMD_WARRIOR_GATE_ROBOT_CONTINUE 6
#define PROTOCOL_SUBCMD_WARRIOR_GATE_REWARD 7
#define PROTOCOL_SUBCMD_WARRIOR_GATE_BUY_TIMES 8

#define PROTOCOL_RSP_SUBCMD_WARRIOR_GATE_INDEX 1
#define PROTOCOL_RSP_SUBCMD_WARRIOR_GATE_LIST 2
#define PROTOCOL_RSP_SUBCMD_WARRIOR_GATE_OVER 3
#define PROTOCOL_RSP_SUBCMD_WARRIOR_GATE_ROBOT 4
#define PROTOCOL_RSP_SUBCMD_WARRIOR_GATE_ROBOT_REWARD 5 	// 每次挂机结果
#define PROTOCOL_RSP_SUBCMD_WARRIOR_GATE_ROBOT_CONTINUE 6 	// 登录挂机结果
#define PROTOCOL_RSP_SUBCMD_WARRIOR_GATE_REWARD 7
#define PROTOCOL_RSP_SUBCMD_WARRIOR_GATE_BUY_TIMES 8

/********************匹配系统开始*********************/
#define PROTOCOL_CMD_MATCH  27
#define PROTOCOL_SUBCMD_MATCH_QUERY_ALL_ROOM 1			//查询所有房间信息
#define PROTOCOL_SUBCMD_MATCH_QUERY_ONE_ROOM 2			//单个房间信息查询
#define PROTOCOL_SUBCMD_MATCH_QUERY_RANK 3				//查询排行榜信息
#define PROTOCOL_SUBCMD_MATCH_MATCH_START 4				//开始匹配
#define PROTOCOL_SUBCMD_MATCH_JOIN_ROOM 5				//加入房间
#define PROTOCOL_SUBCMD_MATCH_EXIT_ROOM 6				//退出房间
#define PROTOCOL_SUBCMD_MATCH_KICK_ROOM 7				//踢出房间
#define PROTOCOL_SUBCMD_MATCH_BATTLE_START 8			//开始战斗(房主)
#define PROTOCOL_SUBCMD_MATCH_BATTLE_OVER 9				//战斗结束
#define PROTOCOL_SUBCMD_MATCH_START_ERROR 10			//匹配失败
#define PROTOCOL_SUBCMD_MATCH_BATTLE_RESULT 11			//战斗结果
#define PROTOCOL_SUBCMD_MATCH_START_NOTIFY 12			//进入战斗
#define PROTOCOL_SUBCMD_MATCH_CREATE_ROOM 13			//创建房间
#define PROTOCOL_SUBCMD_MATCH_PLAYER_EXIT 14			//玩家退出战场
#define PROTOCOL_SUBCMD_MATCH_POINT_STORE 15			//多人副本
#define PROTOCOL_SUBCMD_MATCH_JOIN_TIMES 16				//生死防线参加次数
#define PROTOCOL_SUBCMD_MATCH_POSITIVE 17				//多人副本
#define PROTOCOL_SUBCMD_MATCH_POSITIVE_START_NOTIFY 18	//多人副本
#define PROTOCOL_SUBCMD_MATCH_POSITIVE_BATTLE_OVER 19	//多人副本
#define PROTOCOL_SUBCMD_MATCH_POSITIVE_PLAYER_INTER 20	//多人副本
#define PROTOCOL_SUBCMD_MATCH_MULTI_INVADE_BUY 21		//生死防线购买


#define PROTOCOL_RSP_SUBCMD_ALL_ROOM_INFO 1				//房间信息
#define PROTOCOL_RSP_SUBCMD_ONE_ROOM_INFO 2				//房间信息
#define PROTOCOL_RSP_SUBCMD_RANK 3						//房间信息
/********************匹配系统结束**********************/

/********************生死防线活动开始*************************/
#define PROTOCOL_CMD_INVADE  28
#define PROTOCOL_SUBCMD_INVADE_QUERY 1					//查询排行
#define PROTOCOL_SUBCMD_INVADE_JOIN  2					//参加
#define PROTOCOL_SUBCMD_INVADE_OVER  3					//结束
/********************生死防线活动结束*************************/

/********** 工人系统开始  *******************/
#define PROTOCOL_CMD_WORKER 29
#define PROTOCOL_SUBCMD_WORKER_LIST 1
#define PROTOCOL_SUBCMD_WORKER_BUY 2
#define PROTOCOL_SUBCMD_WORKER_UPGRADE 3
#define PROTOCOL_SUBCMD_WORKER_DISPATCH 4
#define PROTOCOL_SUBCMD_WORKER_INFO 5
#define PROTOCOL_SUBCMD_WORKER_QUERY 6

// 工人回包返回值
#define PROTOCOL_RET_WORKER_SUCCESS 0 			// 操作成功
#define PROTOCOL_RET_WORKER_FAIL 1 				// 操作失败
#define PROTOCOL_RET_WORKER_PACKET_ERROR 2 		// 收包数据有错

/********** 工人系统结束  *******************/



/********************家园系统开始*************************/
#define PROTOCOL_CMD_HOME  30
#define PROTOCOL_SUBCMD_HOME_QUERY 	1						//家园查询
#define PROTOCOL_SUBCMD_BASE_LIFT 	2						//基地车变形为车
#define PROTOCOL_SUBCMD_BASE_DOWN 	3						//基地车变形为基地
#define PROTOCOL_SUBCMD_BASE_MOVE 	4						//移动

#define PROTOCOL_RSP_SUBCMD_HOME_INFO 	1					//家园信息
#define PROTOCOL_RSP_SUBCMD_HOME_BATTLE_OVER 	5			//家园信息
/********************家园系统结束*************************/

/*-----------------建筑相关协议------------------*/
#define PROTOCOL_CMD_ALLIANCE_BUILDING 31
#define PROTOCOL_SUBCMD_ALLIANCE_BUILDINGLIST 1 			// 获取建筑列表
#define PROTOCOL_SUBCMD_ALLIANCE_BUILDING_QUERY_ONE 2 		// 查询单个建筑信息
#define PROTOCOL_SUBCMD_ALLIANCE_BUILDING_BUILD 3 			// 建造
#define PROTOCOL_SUBCMD_ALLIANCE_BUILDING_MOVE 4 			// 建筑移动
#define PROTOCOL_SUBCMD_ALLIANCE_BUILDING_UPGRADE 5 		// 建筑升级

/*-----------------盟战协议------------------*/
#define PROTOCOL_CMD_ALLIANCE_BATTLE 32
#define PROTOCOL_SUBCMD_ALLIANCE_GROUP_QUERY 1 				// 查询分组信息
#define PROTOCOL_SUBCMD_ALLIANCE_ENTER_BATTLE 2 			// 进入战场
#define PROTOCOL_SUBCMD_ALLIANCE_BATTLE_OVER 3 				// 战斗结束

#define PROTOCOL_SUBCMD_ALLIANCE_BATTLE_OVER 3 				// 战斗结束
#define PROTOCOL_SUBCMD_ALLIANCE_BATTLE_DAMAGE 4 			// 战斗结束
#define PROTOCOL_SUBCMD_ALLIANCE_BATTLE_KILL 5 				// 战斗结束
#define PROTOCOL_SUBCMD_ALLIANCE_BATTLE_FINISH 6 			// 战斗结束

/*-----------------联合行动------------------*/
#define PROTOCOL_CMD_JOINT_OPERATION 33

#define PROTOCOL_SUBCMD_JOINT_OPERATION_QUERY_ALL_ROOM 1	//查询所有房间信息
#define PROTOCOL_SUBCMD_JOINT_OPERATION_QUERY_ONE_ROOM 2	//单个房间信息查询
#define PROTOCOL_SUBCMD_JOINT_OPERATION_CREATE_ROOM 3		//创建房间
#define PROTOCOL_SUBCMD_JOINT_OPERATION_JOIN_ROOM 4			//加入房间
#define PROTOCOL_SUBCMD_JOINT_OPERATION_EXIT_ROOM 5			//退出房间
#define PROTOCOL_SUBCMD_JOINT_OPERATION_KICK_ROOM 6			//踢出房间
#define PROTOCOL_SUBCMD_JOINT_OPERATION_MATCH_START 7		//开始匹配
#define PROTOCOL_SUBCMD_JOINT_OPERATION_BATTLE_START 8		//开始战斗(房主)
#define PROTOCOL_SUBCMD_JOINT_OPERATION_BATTLE_OVER 9		//战斗结束
#define PROTOCOL_SUBCMD_JOINT_OPERATION_START_ERROR 10		//匹配失败
#define PROTOCOL_SUBCMD_JOINT_OPERATION_BATTLE_RESULT 11	//战斗结果
#define PROTOCOL_SUBCMD_JOINT_OPERATION_START_NOTIFY 12		//进入战斗
#define PROTOCOL_SUBCMD_JOINT_OPERATION_JOIN_TIMES 13		//参加次数
#define PROTOCOL_SUBCMD_JOINT_OPERATION_TIMES_BUY 14		//次数购买
#define PROTOCOL_SUBCMD_JOINT_OPERATION_PLAYER_EXIT 15		//玩家退出战场

#define PROTOCOL_RSP_SUBCMD_JOINT_OPERATION_ALL_ROOM_INFO 1					//房间信息
#define PROTOCOL_RSP_SUBCMD_JOINT_OPERATION_ONE_ROOM_INFO 2					//房间信息
/********************资源运输*************************/
#define PROTOCOL_CMD_BOAT 34

#define PROTOCOL_SUBCMD_MERCHANT_ASRV_TARGET 1
#define PROTOCOL_SUBCMD_MERCHANT_TARGET_INFO_REQ 2
#define PROTOCOL_SUBCMD_MERCHANT_TARGET_INFO_RESP 3
#define PROTOCOL_SUBCMD_MERCHANT_ASRV_REVENGE 4
#define PROTOCOL_SUBCMD_MERCHANT_ROB_RES 5

#define PROTOCOL_SUBCMD_MERCHANT_INFO 20
#define PROTOCOL_SUBCMD_MERCHANT_FRONT 21
#define PROTOCOL_SUBCMD_MERCHANT_START 22
#define PROTOCOL_SUBCMD_MERCHANT_HELP 23
#define PROTOCOL_SUBCMD_MERCHANT_REFRESH 24
#define PROTOCOL_SUBCMD_MERCHANT_BUY_COUNT 25
#define PROTOCOL_SUBCMD_MERCHANT_FINISH_INFO 26
#define PROTOCOL_SUBCMD_MERCHANT_HELP_INFO 27
#define PROTOCOL_SUBCMD_MERCHANT_REWARD 28
#define PROTOCOL_SUBCMD_MERCHANT_GET_TARGET 29
#define PROTOCOL_SUBCMD_MERCHANT_GET_TARGET_COUNT 30
#define PROTOCOL_SUBCMD_MERCHANT_ROB_RESULT 31
#define PROTOCOL_SUBCMD_MERCHANT_ROB_LOG 32
#define PROTOCOL_SUBCMD_MERCHANT_ROB_NOTICE 33
#define PROTOCOL_SUBCMD_MERCHANT_SPEED_UP 34
#define PROTOCOL_SUBCMD_MERCHANT_STAR 35
#define PROTOCOL_SUBCMD_MERCHANT_REVENGE 36
#define PROTOCOL_SUBCMD_MERCHANT_CASH_RESET 37

/********************竞技场*************************/
#define PROTOCOL_CMD_ARENA 35
#define PROTOCOL_SUBCMD_ARENA_QUERY 1
#define PROTOCOL_SUBCMD_ARENA_BUY_ENERGY 2
#define PROTOCOL_SUBCMD_ARENA_BEGIN_ATTACK 3
#define PROTOCOL_SUBCMD_ARENA_END_ATTACK 4
#define PROTOCOL_SUBCMD_ARENA_RANK 5
#define PROTOCOL_SUBCMD_ARENA_REWARD 6
#define PROTOCOL_SUBCMD_ARENA_SHOP 7
#define PROTOCOL_SUBCMD_ARENA_SHOP_BUY 8
#define PROTOCOL_SUBCMD_ARENA_LOG 9
#define PROTOCOL_SUBCMD_ARENA_REFRESH 10
#define PROTOCOL_SUBCMD_ARENA_SHOP_REFRESH 11

/********************竞技场*************************/
#define PROTOCOL_CMD_COST 36
#define PROTOCOL_SUBCMD_COST_QUERY 1
#define PROTOCOL_SUBCMD_COST_BUY 2

/********************活动*************************/
#define PROTOCOL_CMD_ACTIVITY 36
#define PROTOCOL_SUBCMD_ACTIVITY_TIME 1
#define PROTOCOL_SUBCMD_ACTIVITY_DATA 2
#define PROTOCOL_SUBCMD_ACTIVITY_REWARD 3
#define PROTOCOL_SUBCMD_ACTIVITY_ADD_COUNT 4
#define PROTOCOL_SUBCMD_ACTIVITY_BUY_SCORE 5
#define PROTOCOL_SUBCMD_ACTIVITY_LEVEL_REWARD 6
#define PROTOCOL_SUBCMD_ACTIVITY_QUEST_REWARD 7
#define PROTOCOL_SUBCMD_ACTIVITY_CHARGE_HISTORY 8
#define PROTOCOL_SUBCMD_ACTIVITY_LOTTERY 9
#define PROTOCOL_SUBCMD_ACTIVITY_ALL_DATA 10

/********************神将*************************/
#define PROTOCOL_CMD_GOD 37

#define PROTOCOL_SUBCMD_GOD_GATE_INDEX 1
#define PROTOCOL_SUBCMD_GOD_GATE_LIST 2
#define PROTOCOL_SUBCMD_GOD_GATE_OVER 3
#define PROTOCOL_SUBCMD_GOD_GATE_ROBOT 4
#define PROTOCOL_SUBCMD_GOD_GATE_ROBOT_CONTINUE 6
#define PROTOCOL_SUBCMD_GOD_GATE_REWARD 7

#define PROTOCOL_RSP_SUBCMD_GOD_GATE_INDEX 1
#define PROTOCOL_RSP_SUBCMD_GOD_GATE_LIST 2
#define PROTOCOL_RSP_SUBCMD_GOD_GATE_OVER 3
#define PROTOCOL_RSP_SUBCMD_GOD_GATE_ROBOT 4
#define PROTOCOL_RSP_SUBCMD_GOD_GATE_ROBOT_REWARD 5 	// 每次挂机结果
#define PROTOCOL_RSP_SUBCMD_GOD_GATE_ROBOT_CONTINUE 6 	// 登录挂机结果
#define PROTOCOL_RSP_SUBCMD_GOD_GATE_REWARD 7

/********************火炮系统开始*************************/
#define PROTOCOL_CMD_CANNON 38
#define PROTOCOL_SUBCMD_CANNON_INFO 1
#define PROTOCOL_SUBCMD_CANNON_UPGRATE 2
#define PROTOCOL_SUBCMD_CANNON_ADD_BULLET 3
#define PROTOCOL_SUBCMD_CANNON_FIRE_COST 4

/********************建筑队列开始*************************/
#define PROTOCOL_CMD_BUILDING_TRAIN 39
#define PROTOCOL_SUBCMD_BUILDING_TRAIN_INFO 1
#define PROTOCOL_SUBCMD_BUILDING_TRAIN_RENT 2

/********************布阵开始***************************/
#define PROTOCOL_CMD_TROOPS 40
#define PROTOCOL_SUNCMD_TROOPS_GET_DEFEND 1
#define PROTOCOL_SUNCMD_TROOPS_SET_DEFEND 2
#define PROTOCOL_SUNCMD_TROOPS_GET_ATTACK 3
#define PROTOCOL_SUNCMD_TROOPS_SET_ATTACK 4

/********************每日交易***************************/
#define PROTOCOL_CMD_DAILY_BUY 41
#define PROTOCOL_SUBCMD_DAILY_BUY_QUERY 1
#define PROTOCOL_SUBCMD_DAILY_BUY_BUY 2
#define PROTOCOL_SUBCMD_DAILY_BUY_REFRESH 3

/********************随机政务****************************/
#define PROTOCOL_CMD_RANDOM_QUEST 42
#define PROTOCOL_SUBCMD_RANDOM_QUEST_INFO 1
#define PROTOCOL_SUBCMD_RANDOM_QUEST_QUEST 2
#define PROTOCOL_SUBCMD_RANDOM_QUEST_REWARD 3

/********************世界战争****************************/
#define PROTOCOL_CMD_WORLD 44
#define PROTOCOL_SUBCMD_WORLD_ALL_INFO 1
#define PROTOCOL_SUBCMD_WORLD_CITY_INFO 2
#define PROTOCOL_SUBCMD_WORLD_SELF_INFO 3
#define PROTOCOL_SUBCMD_WORLD_SOLDIER 4
#define PROTOCOL_SUBCMD_WORLD_ATTACK 5
#define PROTOCOL_SUBCMD_WORLD_FINISH 6
#define PROTOCOL_SUBCMD_WORLD_SHOP_INFO 7
#define PROTOCOL_SUBCMD_WORLD_SHOP_BUY 8
#define PROTOCOL_SUBCMD_WORLD_HARVEST 9
#define PROTOCOL_SUBCMD_WORLD_RANK_INFO 10

/********************世界BOSS**************************/
#define PROTOCOL_CMD_BOSS 45
#define PROTOCOL_SUBCMD_BOSS_INFO 1
#define PROTOCOL_SUBCMD_BOSS_RESULT 2
#define PROTOCOL_SUBCMD_BOSS_SHOP 3

/********************广告观看*************************/
#define PROTOCOL_CMD_AD 47
#define PROTOCOL_SUBCMD_WATCH_INFO 1
#define PROTOCOL_SUBCMD_WATCH_REWARD 2

/********************管理系统开始*************************/
#define PROTOCOL_CMD_ADMIN  50

#define PROTOCOL_SUBCMD_ADMIN_SET_ALL_HERO_EXIT_BATTLE  1 	// 清理英雄出战状态
#define PROTOCOL_SUBCMD_ADMIN_CHANGE_ACT_TIME 2  			// 活动开关
#define PROTOCOL_SUBCMD_ADMIN_ADD_MONEY 3
#define PROTOCOL_SUBCMD_ADMIN_KICK_USER 4					// 踢玩家下线
#define PROTOCOL_SUBCMD_ADMIN_ADD_EQUIP 5					// 加装备
#define PROTOCOL_SUBCMD_ADMIN_PRINT_LOG 6					// 打印日志
#define PROTOCOL_SUBCMD_ADMIN_LOGIN 7
#define PROTOCOL_SUBCMD_ADMIN_CLIENT 8
/********************管理系统结束*************************/

/********************服务器间通信*************************/
#define PROTOCOL_CMD_OTHSRV  51
#define PROTOCOL_SUBCMD_OTHSRV_INTERACT_REQ 1
#define PROTOCOL_SUBCMD_OTHSRV_INTERACT_RESP 2
#define PROTOCOL_SUBCMD_OTHSRV_INFO_REQ 3
#define PROTOCOL_SUBCMD_OTHSRV_INFO_RESP 4

/*-------------Transit相关协议----------------*/
#define PROTOCOL_CMD_TRANSIT  250
#define PROTOCOL_SUBCMD_TRANSIT_LOGIN 1
#define PROTOCOL_SUBCMD_TRANSIT_BUY 2
#define PROTOCOL_SUBCMD_TRANSIT_DELIVER 3
#define PROTOCOL_SUBCMD_TRANSIT_OFFLINE 4
#define PROTOCOL_SUBCMD_TRANSIT_PAY_SUCCESS_REPORT 6
#define PROTOCOL_SUBCMD_TRANSIT_BLUE_RENEW 5			// 蓝钻续费
#define PROTOCOL_SUBCMD_TRANSIT_BLUE_GET 6				// 蓝钻信息
#define PROTOCOL_SUBCMD_TRANSIT_PAY_GET_TOKEN 7 		// 获取token信息
#define PROTOCOL_SUBCMD_TRANSIT_GET_BALANCE 8			// 查询平台游戏币余额
#define PROTOCOL_SUBCMD_TRANSIT_PAY 9					// 扣除平台游戏币兑换商品
#define PROTOCOL_SUBCMD_TRANSIT_FRIEND_INFO 10			// 
#define PROTOCOL_SUBCMD_TRANSIT_REPORT 11				//
#define PROTOCOL_SUBCMD_TRANSIT_GIFT_EXHANGE 12			//
#define PROTOCOL_SUBCMD_TRANSIT_PER_ORDER 13			// qq平台 预下单

#pragma pack(1)
//客户端，服务器通讯包头定义
typedef struct PackHead{
	uint16_t magic;
	uint16_t bodyLen;
	uint16_t crc1;
	uint16_t crc2;
	uint32_t padding1;
	uint32_t padding2;
}PackHead;

//内部服务器通讯包头定义
typedef struct ServerHead{
	uint16_t magic;
	uint16_t bodyLen;
	uint16_t ptype;			//对应PROTOCOL_TYPE_系列
	uint32_t fd;
	uint32_t time;
	uint32_t microTime;
	uint32_t clientIp;
}ServerHead;

#pragma pack()

//客户端到服务器包体部分组成：流水序列号+cmd+subcmd+包体正文
//服务器到客户端包头部分组成：cmd+subcmd+包体正文

#endif /* PROTOCOLDEFINE_H_ */
