all:
	@make -C ./common
	@make -C ./kernel
	@make -C ./platform
	@make -C ./data
	@make -C ./logic
	@make -C ./cgi
	@make -C ./server
clean:
	@make -C ./common clean
	@make -C ./kernel clean
	@make -C ./platform clean
	@make -C ./data clean
	@make -C ./logic clean
	@make -C ./cgi clean
	@make -C ./server clean
