#ifndef _SERVER_INC_H_
#define _SERVER_INC_H_

#include <stdexcept>

#include "Kernel.h"
#include "DataInc.h"
#include "LogicManager.h"
#include "UserManager.h"
#include "LogicEquipmentManager.h"
#include "LogicEquipShopManager.h"
#include "LogicBuildManager.h"
#include "WorldManager.h"
#include "LogicHeroManager.h"
#include "LogicScienceMgr.h"
#include "LogicWeaponsMgr.h"
#include "LogicResourceManager.h"
#include "LogicUserManager.h"
#include "LogicMissionManager.h"
#include "LogicYellowVipManager.h"
#include "LogicNPCPassMgr.h"
#include "LogicMarketManager.h"
#include "LogicGemMgr.h"
#include "LogicCumulationLoginManager.h"
#include "LogicPkFieldMgr.h"
#include "LogicOfficialMgr.h"
#include "LogicFogGateManager.h"
#include "LogicMineMgr.h"
#include "LogicPassActivityMgr.h"
#include "LogicDailyMissionManager.h"
#include "LogicTimeLimitPropMgr.h"
#include "LogicCompProduceManager.h"
#include "LogicComponentManager.h"
#include "LogicAchievementManager.h"
#include "LogicFriendManager.h"
#include "LogicNotifyManager.h"
#include "LogicResourceCopyManager.h"
#include "LogicOperaBattleManager.h"
#include "LogicModelTrialManager.h"
#include "LogicCrossBusinessManager.h"
#include "LogicAttackHarborManager.h"
#include "LogicEliteMilitaryManager.h"

#include "NPCActivity.h"
#include "LogicShop.h"
#include "LogicCashBack.h"
#include "LogicSmeltActivity.h"
#include "LogicTouchGoldActivity.h"
#include "LogicHugeDiscount.h"
#include "LogicShakeDiceActivity.h"
#include "LogicLittleChargeActivity.h"
#include "LogicEnlivenKillActivity.h"
#include "LogicSellComponentActivity.h"

#endif
