all:
	@make -j8 -C ./common
	@make -j8 -C ./kernel
#	@make -C ./platform
#	@make -C ./data
#	@make -C ./logic
#	@make -C ./cgi
clean:
	@make -C ./common clean
	@make -C ./kernel clean
	@make -C ./platform clean
	@make -C ./data clean
	@make -C ./logic clean
	@make -C ./cgi clean
