/*
 * ServerInc.h
 *
 *  Created on: 2019年4月17日
 *      Author: Administrator
 */

#ifndef _BATTLE_INC_H_
#define _BATTLE_INC_H_

#include "BattleBaseInc.h"
#include "FdManager.h"
#include "MapAreaManager.h"
#include "Map.h"
#include "MapHang.h"
#include "MapCopy.h"
#include "MapMoveObject.h"
#include "MapManager.h"
#include "LogicManager.h"
#include "MapAreaManager.h"
#include "SpecialEntity.h"
#include "RoleManager.h"
#include "Human.h"
#include "CarbonManager.h"
#include "StdMonster.h"
#include "MonsterManager.h"
#include "SkillControler.h"
#include "SkillManager.h"
#include "ConfigWrap.h"
#include "EquipsManager.h"
#include "HangManager.h"
#include "DestoryManager.h"
#include "MapMoveManager.h"
#include "UserManager.h"
#include "MissionManager.h"
#include "CacheManager.h"
#include "AdvanceManager.h"
#include "UpdateManager.h"
#include "ShenQiManager.h"
#include "PropertyManager.h"
#include "ChatManager.h"
#include "ForgeManager.h"
#include "ReinCarnManager.h"
#include "CardManager.h"
#include "PurifyManager.h"
#include "TitleManager.h"
#include "FashionManager.h"
#include "GemManager.h"
#include "OnlineRewardManager.h"
#include "TreasureManager.h"
#include "RuneManager.h"
#include "RoleSuitManager.h"
#include "ActivityManager.h"
#include "TreasureRecordManager.h"
#include "CopyManager.h"
#include "ZhuLingManager.h"
#include "ZhanLingManager.h"
#include "DevilAngelManager.h"
#include "LevelRewardRecordManager.h"
#include "NearEnemy.h"
#include "RewardManager.h"
#include "TrumpManager.h"
#include "ReinCarnShengManager.h"
#include "TeamManager.h"
#include "BuffControler.h"
#include "NearEnemyManager.h"
#include "ToplistManager.h"
#include "ShopManager.h"


#endif /* _BATTLE_INC_H_ */
