all:
	@make -C ./common
	@make -C ./kernel
	@make -C ./data
	@make -C ./platform
	@make -C ./proto
	@make -C ./config
	@make -C ./dbwriter
	@make -C ./battle
clean:
	@make -C ./common clean
	@make -C ./kernel clean
	@make -C ./data clean
	@make -C ./platform clean
	@make -C ./proto clean
	@make -C ./config clean
	@make -C ./dbwriter clean
	@make -C ./battle clean
