/*
 * Packet.h
 *
 *  Created on: 2012-2-10
 *      Author: dada
 */

#ifndef _LIP_FIRE_PACKET_H_
#define _LIP_FIRE_PACKET_H_

#include "Common.h"
#include "IPacket.h"

#define PACKET_HEADER_SIZE 22
#define MAX_PROTOCOL_BODY_SIZE 0xF000
#define MAX_PACKET_SIZE (PACKET_HEADER_SIZE + MAX_PROTOCOL_BODY_SIZE + sizeof(byte))

#define PROTOCOL_TYPE_ROLE 0XFF
#define PROTOCOL_TYPE_ENTERGAME 0
#define PROTOCOL_TYPE_LOGIC 0
#define PROTOCOL_TYPE_MOVE 1
#define PROTOCOL_TYPE_BUFF 4
#define PROTOCOL_TYPE_SKILL 5
#define PROTOCOL_TYPE_QUEST 6		//任务
#define PROTOCOL_TYPE_EQUIP 7
#define PROTOCOL_TYPE_BAG 8
#define PROTOCOL_TYPE_CHAT 9		//聊天
#define PROTOCOL_TYPE_GUILD 10
#define PROTOCOL_TYPE_INTERNAL 11
#define PROTOCOL_TYPE_SHOP 12
#define PROTOCOL_TYPE_TRADE 13
#define PROTOCOL_TYPE_DROP 15
#define PROTOCOL_TYPE_TEAM 16
#define PROTOCOL_TYPE_TEAMINVITE 17
#define PROTOCOL_TYPE_INSURE 19
#define PROTOCOL_TYPE_STORE 23
#define PROTOCOL_TYPE_PK 24
#define PROTOCOL_TYPE_OTHER 26
#define PROTOCOL_TYPE_PETS    34
#define PROTOCOL_TYPE_TRAFFIC 35
#define PROTOCOL_TYPE_MARKET 39
#define PROTOCOL_TYPE_HORNOR 40
#define PROTOCOL_TYPE_SOCIAL 41		//社交
#define PROTOCOL_TYPE_MOUNT 42
#define PROTOCOL_TYPE_STONE 43
#define PROTOCOL_TYPE_ACTIVITY_CHARGE 43
#define PROTOCOL_TYPE_RANK_LIST 90
#define PROTOCOL_TYPE_TITLE 101
#define PROTOCOL_TYPE_ACTIVITY  108//活动
#define PROTOCOL_TYPE_SHABAK 119
#define PROTOCOL_TYPE_SEVENDAYS 120
#define PROTOCOL_TYPE_NPCSHOP 133
#define PROTOCOL_TYPE_SHORTCUT 134
#define PROTOCOL_TYPE_FIX 136
#define PROTOCOL_TYPE_ONLINEREWARD 138
#define PROTOCOL_TYPE_MISC 139
#define PROTOCOL_TYPE_CONVOY 145	//护送
#define PROTOCOL_TYPE_BLESS 146
#define PROTOCOL_TYPE_CIRCLE 147
#define PROTOCOL_TYPE_LUCK_DRAW 148  // 抽奖
#define PROTOCOL_TYPE_ACTIVITY_CROSS_WORLD_BOSS 254  // 跨服boss
#define PROTOCOL_TYPE_ACTIVITY_QUNYINGZHUJIAN 254  //群英铸剑
#define PROTOCOL_TYPE_HIT_JAR 149  // 砸罐子
#define PROTOCOL_TYPE_COMBAT_CMP 38//战力竞技
#define PROTOCOL_TYPE_ACTIVENESS 150   //活跃度
#define PROTOCOL_TYPE_PAY_POINTS 151	//消费积分
#define PROTOCOL_TYPE_MAP_BOSS	 152	//地图boss
#define PROTOCOL_TYPE_INVEST_PLAN 153   //投资计划
#define PROTOCOL_TYPE_STAGE_CONSUME 154 //阶段消费
#define PROTOCOL_TYPE_HOLIDAY_ACTIVITY 155 //
#define PROTOCOL_TYPE_TREASURE_BOX	156		// 聚宝盆活动
#define PROTOCOL_TYPE_TRANSIT		203
#define PROTOCOL_TYPE_YELLOW_VIP	204
#define PROTOCOL_TYPE_SIGN_IN		205
#define PROTOCOL_TYPE_ACTIVITY_WORLDBOSS	206
#define PROTOCOL_TYPE_ACTIVITY_ALLEXP		207
#define PROTOCOL_TYPE_ACTIVITY_DRUMSARENA	208
#define PROTOCOL_TYPE_ACTIVITY_DEMONINVATE	209
#define PROTOCOL_TYPE_ACTIVITY_PAY		210
#define PROTOCOL_TYPE_GROUP_BUY			211	// 团购活动
#define PROTOCOL_TYPE_ACTIVITY_CROSS_TEAM_BATTLE 251
#define PROTOCOL_TYPE_ACTIVITY_HOLIDAY	245	// 暑期活动
#define PROTOCOL_TYPE_BOSS_GATE			246
#define PROTOCOL_TYPE_HEART_BREATH		255 // 心跳
#define PROTOCOL_TYPE_VIP_BOSS 244
#define PROTOCOL_TYPE_CROSS  1
#define PROTOCOL_CMD_ACTIVITY_CROSS_TEAM_BATTLE_ENTER 1
#define PROTOCOL_CMD_ACTIVITY_CROSS_TEAM_BATTLE_GET_RESULT 2
#define PROTOCOL_CMD_ACTIVITY_CROSS_TEAM_BATTLE_GET_ENTER_TIMES 3

#define PROTOCOL_TYPE_MAP 1


//和接入层通讯命令字
#define PROTOCOL_ACCESS_TRANSFER 1          // 客户端到login,login可直接转发
#define PROTOCOL_ACCESS_ANSWER 2            // 回包到客户端,login可直接转发
#define PROTOCOL_ACCESS_HEARBEAT 3          // 心跳
#define PROTOCOL_ACCESS_COFFLINE 4          // 客户端下线
#define PROTOCOL_ACCESS_LOFFLINE 5          // 服务端下线
#define PROTOCOL_ACCESS_CHANGE_LOGIN 6      // 切换login
#define PROTOCOL_ACCESS_KICK_CROSS  7

//登录服务器，地图服务器通讯命令字
#define PROTOCOL_LOGIN_BEGIN 100
#define PROTOCOL_LOGIN_TRANSFER 101           // login 到地图
#define PROTOCOL_LOGIN_ANSWER 102             // 地图端到login
#define PROTOCOL_LOGIN_HEARBEAT 103
#define PROTOCOL_LOGIN_COFFLINE 104
#define PROTOCOL_LOGIN_LOFFLINE 105
#define PROTOCOL_LOGIN_TRANSIT 106            // login转发地图包，地图之间通信使用
#define PROCOTOL_LOGIN_CHANGE_LOGIN 107      // 切换login


#define PROTOCOL_CMD_ACTIVITY_GET_DATA 34
#define PROTOCOL_CMD_ACTIVITY_GET_REWARD 35

//内部通讯命令字
#define PROTOCOL_EVENT_BEGIN 100
#define PROTOCOL_EVENT_OFFLINE 200
#define PROTOCOL_EVENT_SECOND_TIMER 201
#define PROTOCOL_EVENT_MANAGER 202
#define PROTOCOL_EVENT_BUY_GOODS 203
#define PROTOCOL_EVENT_LOGIN 204
#define PROTOCOL_ENENT_ACTIVITY 205

#define PROTOCOL_CMD_ENTER_CROSS_VIP_BOSS_MAP 1
#define PROTOCOL_CMD_CHALLENGE_BOSS_GATE 1
#define PROTOCOL_CMD_GET_BOSS_GATE_INFO 2

#define PROTOCOL_CMD_PRE_LOGIN 100
#define PROTOCOL_CMD_LOGIN_RET 101
#define PROTOCOL_CMD_BUY_GOODS 102
#define PROTOCOL_CMD_BUY_GOODS_RET 103
#define PROTOCOL_CMD_DELIVER 104
#define PROTOCOL_CMD_DELIVER_RET 105

#define PROTOCOL_CMD_LOGIN 1
#define PROTOCOL_CMD_ENTERGAME 1
#define PROTOCOL_CMD_RELOGIN 100
#define PROTOCOL_CMD_MOVE 1
#define PROTOCOL_CMD_RUN 2
#define PROTOCOL_CMD_QUERY_MY_EQUIP 4
#define PROTOCOL_CMD_QUERY_MY_ITEM 2
#define PROTOCOL_CMD_ITEM_PICKUP 9
#define PROTOCOL_CMD_SHORTCUT_GET_ALL 2
#define PROTOCOL_CMD_SHORTCUT_SET 1
#define PROTOCOL_CMD_DELETE_ITEM 1
#define PROTOCOL_CMD_CHANGE_LOGIN 13

#define PROTOCOL_CMD_STORE_QUERY 1
#define PROTOCOL_CMD_EQUIP_WEAR 1
#define PROTOCOL_CMD_EQUIP_UNWEAR 2
#define PROTOCOL_CMD_EQUIP_QUERY_OTHER 5
#define PROTOCOL_CMD_EQUIP_HIDE_SHAPE 6
#define PROTOCOL_CMD_EQUIP_QUERY_RANK  7
#define PROTOCOL_CMD_STORE_QUERY 1
#define PROTOCOL_CMD_STORE_ADD 2
#define PROTOCOL_CMD_STORE_DEL 3
#define PROTOCOL_CMD_STORE_MONEY 8
#define PROTOCOL_CMD_STORE_PASSWORD 6
#define PROTOCOL_CMD_NPCDEAL_BUY_ITEM 1
#define PROTOCOL_CMD_NPCDEAL_SELL_ITEM 4
#define PROTOCOL_CMD_NPCDEAL_REBUY_ITEM 5
#define PROTOCOL_CMD_TRAFFIC_ARRIVE 1
#define PROTOCOL_CMD_MISC_TRANSFER 7
#define PROTOCOL_CMD_PK_SET_MODE 3
#define PROTOCOL_CMD_BAG_USE_ITEM 7
#define PROTOCOL_CMD_BAG_DILATATION_PRICE 3
#define PROTOCOL_CMD_BAG_DILATATION 4
#define PROTOCOL_CMD_BAG_SPLIT 5
#define PROTOCOL_CMD_BAG_OVERLAY 6
#define PROTOCOL_CMD_BAG_DROP_MONEY 14
#define PROTOCOL_CMD_BAG_QUERY_UPGRADES 15
#define PROTOCOL_CMD_BAG_AGGRANDIZ 8
#define PROTOCOL_CMD_BAG_NEED_ITEMS 9
#define PROTOCOL_CMD_BAG_PERFECT 16
#define PROTOCOL_CMD_BAG_TRANS_STRONG 17
#define PROTOCOL_CMD_BAG_DECOMPOSE_PREVIEW 30
#define PROTOCOL_CMD_BAG_DECOMPOSE 31
#define PROTOCOL_CMD_BAG_COMPOSE_PREVIEW 32
#define PROTOCOL_CMD_BAG_COMPOSE 33



#define PROTOCOL_RSPCMD_MISC_OFFLINEEXP 5
#define PROTOCOL_RSPCMD_MISC_EXPRLT 6
#define PROTOCOL_RSPCMD_MISC_RECOVE 34

#define PROTOCOL_RSPCMD_MISC_NOTICE 41
#define PROTOCOL_RSPCMD_MISC_RCHARGE 110
#define PROTOCOL_RSPCMD_MISC_PAY_AWARD 75
#define PROTOCOL_RSPCMD_MISC_PAY_STATE 76
#define PROTOCOL_RSPCMD_MISC_DAYS_CHARGE 80
#define PROTOCOL_RSPCMD_MISC_RCHARGE 110
#define PROTOCOL_RSPCMD_MISC_GET_ACTIVITY_TIME 251


#define PROTOCOL_CMD_MISC_SIGN_IN 1
#define PROTOCOL_CMD_MISC_SIGN_IN_AWARD 2
#define PROTOCOL_CMD_MISC_BUY_SIGN_IN 3
#define PROTOCOL_CMD_MISC_OFFLINE_EXPGET 9
#define PROTOCOL_CMD_MISC_BOSS_STATUS 12
#define PROTOCOL_CMD_MISC_RECOVE 35
#define PROTOCOL_CMD_MISC_LEAVE_SCENE 59
#define PROTOCOL_CMD_MISC_OFFLINE 41
#define PROTOCOL_CMD_MISC_BOSS_SOUL 105
#define PROTOCOL_CMD_MISC_BOSS_REWARD_NOTICE 123
#define PROTOCOL_CMD_MISC_BOSS_REWARD_REQUEST 123
#define PROTOCOL_CMD_MISC_BOSS_HURT_RANK 122
#define PROTOCOL_CMD_MISC_WHITE_WING 127
#define PROTOCOL_CMD_MISC_GET_ACTIVITY_TIME 251
#define PROTOCOL_CMD_MISC_REWARD 254
#define PROTOCOL_CMD_MISC_HORSE_POINTS 253

#define PROTOCOL_CMD_MARKET_SET 1
#define PROTOCOL_CMD_MARKET_END 2
#define PROTOCOL_CMD_MARKET_TALK 3
#define PROTOCOL_CMD_MARKET_BUY 4
#define PROTOCOL_CMD_MARKET_CHECK 5
#define PROTOCOL_CMD_MARKET_CHANAGE 7
#define PROTOCOL_CMD_MARKET_ENABLE 8
#define PROTOCOL_CMD_LOGIN_MARKET_CHECK 10

#define PROTOCOL_CMD_MOUNT_RIDE 1
#define PROTOCOL_CMD_MOUNT_UPLEVEL 2
#define PROTOCOL_CMD_MOUNT_TIMEREQUEST 3
#define PROTOCOL_CMD_MOUNT_TIMERIDE 4
#define PROTOCOL_CMD_MOUNT_TIMEACTIVE 5
#define PROTOCOL_CMD_SHOP_BUY 1
#define PROTOCOL_CMD_SHOP_QUERY_CHARGE_GOLD 3
#define PROTOCOL_CMD_SHOP_GET_CHARGE_GOLD 4
#define PROTOCOL_CMD_FIX_EQUIP 2
#define PROTOCOL_CMD_INSURE 1
#define PROTOCOL_CMD_INSURE_QUERY 2
#define PROTOCOL_CMD_ONLINE_GETGIFT 1
#define PROTOCOL_CMD_HORNOR_OPEN 1		// 开启荣誉祝福
#define PROTOCOL_CMD_HORNOR_UP 2		// 提升军阶等级
#define PROTOCOL_CMD_HORNOR_AWARD 3		// 领取军阶工资
#define PROTOCOL_CMD_HORNOR_EQUIP 4		// 兑换军阶装备
#define PROTOCOL_CMD_INVITE_INTO_TEAM 1   //邀请入队
#define PROTOCOL_CMD_QUIT_TEAM 2          //离队
#define PROTOCOL_CMD_APPLY_JOIN_TEAM   3  //申请
#define PROTOCOL_CMD_SET_TEAM_LEADER   4  //设置队长
#define PROTOCOL_CMD_LEADER_KICK_MEMBER 5 //踢人
#define PROTOCOL_CMD_APPLY_INTO_TEAM 10   //响应申请
#define PROTOCOL_CMD_INVITED_INTO_TEAM 11 //响应邀请
#define PROTOCOL_CMD_GET_INTO 20 //接受数据
#define PROTOCOL_CMD_TEAM_UPDATE_INTO 21 //接受数据
#define PROTOCOL_CMD_TEAM_SYNC_INTO 22   //同步数据
#define PROTOCOL_CMD_TEAM_SET_QUIT   23    //map设置退队

#define PROTOCOL_CMD_TRANSIT_TEAM_CALL_RETURN 1   //邀请入队
#define PROTOCOL_CMD_TRANSIT_TEAM_CALL_BACK 2   //邀请入队
#define PROTOCOL_CMD_TRANSTI_TEAM_CALL_SEND_POS 3


#define PROTOCOL_CMD_QUNYINGZHUJIAN_GETINFO  3

#define PROTOCOL_CMD_ACTIVENESS_BUY 1
#define PROTOCOL_CMD_ACTIVENESS_VIEW 2

#define PROTOCOL_CMD_TEAM_CALL 12
#define PROTOCOL_CMD_GUILD_INFO 1
#define PROTOCOL_CMD_GUILD_MEMS 2
#define PROTOCOL_CMD_GUILD_LIST 3
#define PROTOCOL_CMD_GUILD_CARD 4
#define PROTOCOL_CMD_GUILD_CREATE 5
#define PROTOCOL_CMD_GUILD_INVITE 7
#define PROTOCOL_CMD_GUILD_INVITE_RLT 9
#define PROTOCOL_CMD_GUILD_APPLY 10
#define PROTOCOL_CMD_GUILD_APPLY_LIST 11
#define PROTOCOL_CMD_GUILD_APPLY_RLT 12
#define PROTOCOL_CMD_GUILD_FIRE 13
#define PROTOCOL_CMD_GUILD_APPOINT 14
#define PROTOCOL_CMD_GUILD_CHANGE_LEADER 15
#define PROTOCOL_CMD_GUILD_LEAVE 16
#define PROTOCOL_CMD_GUILD_NOTICE 17
#define PROTOCOL_CMD_GUILD_BENEFITS 18
#define PROTOCOL_CMD_GUILD_EXPAND 19
#define PROTOCOL_CMD_GUILD_QQGROUP 20
#define PROTOCOL_CMD_GUILD_CALL_ONE 21
#define PROTOCOL_CMD_GUILD_CALL_RLT 22
#define PROTOCOL_CMD_GUILD_WAR 23
#define PROTOCOL_CMD_GUILD_RELATION 29
#define PROTOCOL_CMD_GUILD_CONTRIBUTE 30
#define PROTOCOL_CMD_GUILD_RELATION_RLT 31
#define PROTOCOL_CMD_GUILD_STORE_DEPOSIT 32
#define PROTOCOL_CMD_GUILD_STORE_TAKE_OUT 33
#define PROTOCOL_CMD_GUILD_STORE 34
#define PROTOCOL_CMD_GUILD_STORE_EVENT 35
#define PROTOCOL_CMD_GUILD_COMPETITON_POS 36
#define PROTOCOL_CMD_GUILD_EVENT 40
#define PROTOCOL_CMD_GUILD_TITLES 42
#define PROTOCOL_CMD_GUILD_TALK 43
#define PROTOCOL_CMD_GUILD_CALL 55
#define PROTOCOL_CMD_GUILD_TITLES_EDIT 41
#define PROTOCOL_CMD_GUILD_MONEY_UPDATE 99
#define PROTOCOL_CMD_GUILD_MIX_UPDATE 100

// 和login通信使用 对应PROTOCOL_LOGIN_ANSWER
#define PROTOCOL_CMD_GUILD_SET_GUILD_ID 1
#define PROTOCOL_CMD_GUILD_SET_CAPITAL 2
#define PROTOCOL_CMD_GUILD_CALL_ALL_ONLINE_MEMBERS 3

// scence process to login server
#define PROTOCOL_CMD_ENTER_MAP 13

#define PROTOCOL_CMD_ADD_BUFF 1
#define PROTOCOL_CMD_DEL_BUFF 2


#define  PROTOCOL_GUILD_CALL_ONE_TRANSIT 1
#define  PROTOCOL_GUILD_CALL_ONE_RESULT_TRANSIT 2
#define PROTOCOL_GUILD_SEND_CALL_ONE_POS 3


#define PROTOCOL_CMD_OTHER_VIP 10
#define PROTOCOL_CMD_OTHER_CHANGE_NAME 40
#define PROTOCOL_CMD_OTHER_RED 41
#define PROTOCOL_CMD_OTHER_QUEYR_YELLOW_VIP 45
#define PROTOCOL_CMD_OTHER_GET_YELLOW_AWARD 46
#define PROTOCOL_CMD_OTHER_GET_CARBON_TIMES 47
#define PROTOCOL_CMD_OTHER_SAVE_SYSTEM_CONFIG 30
#define PROTOCOL_CMD_PAY_AWARD 75
#define PROTOCOL_CMD_PAY_STATE 76

#define PROTOCOL_CMD_VIP_REWARD 252



#define PROTOCOL_CMD_ADD_MONEY 1
#define PROTOCOL_CMD_LOGIN_REWARD 4
#define PROTOCOL_CMD_DAYS_CHARGE_REWARD 80
#define PROTOCOL_CMD_CHARGE_REWARD 100
#define PROTOCOL_CMD_BUY_GOODS_ACTIVITY 101
#define PROTOCOL_CMD_CHANGE_ACTIVITY_TIME 102
#define PROTOCOL_CMD_QUERY_PAY_STAGE  103
#define PROTOCOL_CMD_PAY_STAGE_REWARD  104
#define PROTOCOL_CMD_QUERT_LIMIT_QUAN 120
#define PROTOCOL_CMD_LIMIT_QUAN_REWARD 121
#define PROTOCOL_CMD_DAILY_CHARGE_REWARD 125
#define PROTOCOL_CMD_QUERY_DAILY_CHARGE  126
#define PROTOCOL_CMD_NEW_SRV_CHARGE_REWARD 150
#define PROTOCOL_CMD_QUERY_MERGE_SRV_COMPENSATE 130
#define PROTOCOL_CMD_MERGE_SRV_COMPENSATE_REWARD 131
#define PROTOCOL_CMD_MERGE_SRV_CHARGE_REWARD 140
#define PROTOCOL_CMD_MERGE_SRV_QUERY_CHARGE  141
#define PROTOCOL_CMD_STAGE_CONSUME_QUERY  1
#define PROTOCOL_CMD_STAGE_CONSUME_REWARD 2
#define PROTOCOL_CMD_ADD_BLACK 2
#define PROTOCOL_CMD_ADD_EQUIP 3
#define PROTOCOL_CMD_KICK_BLACK 4
#define PROTOCOL_CMD_ADD_QUEST 10
#define PROTOCOL_CMD_ADD_WHITE 11
#define PROTOCOL_CMD_ADD_CIRCLE 13
#define PROTOCOL_CMD_ADD_LEVEL 14
#define PROTOCOL_CMD_ADD_EXP   15
#define PROTOCOL_CMD_RANK_LIST 20
#define PROTOCOL_CMD_LIMIT_SPEAK 21
#define PROTOCOL_CMD_REMOVE_WHITE 12
#define PROTOCOL_CMD_ADD_TITLE 16
#define PROTOCOL_CMD_TOOL_CONFRELOAD 30
#define PROTOCOL_CMD_UP_PROPS	17
#define PROTOCOL_CMD_TRADE_REQ 1
#define PROTOCOL_CMD_TRADE_ACK 2
#define PROTOCOL_CMD_TRADE_ADD 3
#define PROTOCOL_CMD_TRADE_MONEY 4
#define PROTOCOL_CMD_TRADE_LOCK 5
#define PROTOCOL_CMD_TRADE_CANCEL 6
#define PROTOCOL_CMD_TRADE_ON 7
#define PROTOCOL_CMD_PET_CMD 1
#define PROTOCOL_CMD_PET_TRANS 2
#define PROTOCOL_CMD_SHABAK_SIGNUP 1
#define PROTOCOL_CMD_SHABAK_SIGNUPMEMS 2
#define PROTOCOL_CMD_SHABAK_INFO 7
#define PROTOCOL_CMD_SHABAK_REWARD 9
#define PROTOCOL_CMD_SHABAK_SETPOSITION 8
#define PROTOCOL_CMD_SHABAK_CROSS_INFO 10
#define PROTOCOL_CMD_SHABAK_CROSS_SETPOSITION 11
#define PROTOCOL_CMD_SHABAK_CROSS_ENTER 12
#define PROTOCOL_CMD_SHABAK_CROSS_SIGN 13


#define PROTOCOL_TYPE_MYSTERY 157
#define PROTOCOL_CMD_MYSTERY_INFO 1
#define PROTOCOL_CMD_MYSTERY_PUBLIC_INFO 2
#define PROTOCOL_CMD_MYSTERY_BUY 3
#define PROTOCOL_CMD_MYSTERY_REFRESH 4


#define PROTOCOL_CMD_SHABAK_WINNER_INFO 10
#define PROTOCOL_CMD_SHABAK_RESET_INFO 11
#define PROTOCOL_CMD_SHABAK_UPDATE_ATTACK 12
#define PROTOCOL_CMD_SHABAK_UPDATE_KILL 13
#define PROTOCOL_CMD_SHABAK_GET_SIGNUP 14
#define PROTOCOL_CMD_SHABAK_UPDATE_WINNERINFO 15
#define PROTOCOL_CMD_SHABAK_GET_MEMBER 16
#define PROTOCOL_CMD_SHABAK_COMMONREWARD_FLAG 17
#define PROTOCOL_CMD_SHABAK_SPEREWARD_FLAG 18

#define PROTOCOL_CMD_SEVENDAYS_GETINFO 1
#define PROTOCOL_CMD_SEVENDAYS_GETREWARD 2
#define PROTOCOL_CMD_SEVENDAYS_MERGE 3

#define PROTOCOL_CMD_STONE_IN 1
#define PROTOCOL_CMD_STONE_OUT 2
#define PROTOCOL_CMD_STONE_INFO 3
#define PROTOCOL_CMD_STONE_UPGRADE 4
#define PROTOCOL_CMD_STONE_OTHER_INFO 5
#define PROTOCOL_CMD_SEVENDAYS_UPDATE_EXP 10
#define PROTOCOL_CMD_SEVENDAYS_UPDATE_LEVEL 11
#define PROTOCOL_CMD_SEVENDAYS_UPDATE_WINGS 12
#define PROTOCOL_CMD_SEVENDAYS_UPDATE_SHABAK 13
#define PROTOCOL_CMD_SEVENDAYS_UPDATE_HORSE 14
#define PROTOCOL_CMD_SEVENDAYS_UPDATE_COST 15
#define PROTOCOL_CMD_SEVENDAYS_UPDATE_IDEN 16
#define PROTOCOL_CMD_SEVENDAYS_UPDATE_COMBAT 17

#define PROTOCOL_CMD_MERGE_UPDATE_EXP 20
#define PROTOCOL_CMD_MERGE_UPDATE_SHABAK 23
#define PROTOCOL_CMD_MERGE_UPDATE_COMBAT 27

#define PROTOCOL_RSPCMD_MERGE_RSP_DATA 51
// activity
#define PTROTOCOL_CMD_WORLDBOSS_APPEAR 1
#define PTROTOCOL_CMD_WORLDBOSS_DISAPPEAR 2
#define PTROTOCOL_CMD_WORLDBOSS_NOTICE 3
#define PTROTOCOL_CMD_WORLDBOSS_RANK 4
#define PTROTOCOL_CMD_WORLDBOSS_HURT 5
#define PTROTOCOL_CMD_WORLDBOSS_DIE 6
#define PTROTOCOL_CMD_WORLD_BOSS_HURT_RANK_REWARD 7
#define PTROTOCOL_CMD_WORLD_BOSS_HURT_RANK_REWARD_TRANSIT 8
#define PTROTOCOL_CMD_WORLDBOSS_TOTAL_RANK 9

#define PROTOCOL_CMD_CROSS_TEAM_BATTLE_BEGIN 1

#define PTROTOCOL_CMD_ADD_SOUL_TIMES 9
#define PTROTOCOL_CMD_WORLDBOSS_REFRESH 10
#define PROTOCOL_CMD_GET_REWARD_RANK_INFO 11
#define PROTOCOL_CMD_SEND_REWARD_RANK_INFO 12
#define PROTOCOL_CMD_SET_RANK_REWARD 13
#define PROTOTOL_CMD_GET_TOTAL_HURT_RANK 14

#define PROTOCOL_CMD_QUERY_PAY_POINTS 1
#define PROTOCOL_CMD_REWARD_RANK_PAY_POINTS 2
#define PROTOCOL_CMD_PAY_POINTS_BUY_GOODS 3
#define PROTOCOL_CMD_PAY_POINTS	4

#define PROTOCOL_CMD_ALLEXP_OPEN 1

#define PTROTOCOL_CMD_DRUMSARENA_BEGIN 1
#define PTROTOCOL_CMD_DRUMSARENA_END 2
#define PTROTOCOL_CMD_DRUMSARENA_BROADCAST 3

#define PTROTOCOL_CMD_DEMONINVATE_OPEN 1
#define PTROTOCOL_CMD_DEMONINVATE_STOP 2

#define PROTOCOL_CMD_GET_YELLOW_VIP_DAILY_AWARD 1
#define PROTOCOL_CMD_GET_YELLOW_VIP_NEW_AWARD 2

#define PROTOCOL_CMD_TITLE_LIST    1
#define PROTOCOL_CMD_WEAR_TITLE    4
#define PROTOCOL_CMD_REMOVE_TITLE  2
#define PROTOCOL_CMD_GET_OFF_TITLE 3
#define PROTOCOL_CMD_LOOK_TITLE_CONDITION 5

#define PROTOCOL_CMD_TITLE_ON_KILL_BOSS    1
#define PROTOCOL_CMD_DRUMS_ARENA_WINNER_CHANGE  2
#define PROTOCOL_CMD_CASTERAN_CHANGE      3

#define PROTOCOL_CMD_HOLIDAY_QUERYACTIV		1
#define PROTOCOL_CMD_HOLIDAY_EXCHANGE		2
#define PROTOCOL_RSPCMD_HOLIDAY_EXCHANGE	1

//social
#define PROTOCOL_CMD_SOCIAL_FRIEND_ADD_OR_DEL  1
#define PROTOCOL_CMD_SOCIAL_FRIEND_ADD_VERIFY  2
#define PROTOCOL_CMD_SOCIAL_FRIEND_ASK_LIST    3
#define PROTOCOL_CMD_SOCIAL_FRIEND_TRACK       5
#define PROTOCOL_CMD_SOCIAL_FRIEND_ALTER_MOOD  7
#define PROTOCOL_CMD_SOCIAL_FRIEND_SEND_MSG  9
#define PROTOCOL_CMD_SOCIAL_FRIEND_ADD_ASK_BACK 1

// social 通知login 杀人信息
#define PROTOCOL_CMD_SOCIAL_KILL_HUMAN 10

// bless
#define PROTOCOL_CMD_BLESS_BLESS 1
#define PROTOCOL_CMD_BLESS_DONATE 2
#define PROTOCOL_CMD_BLESS_WORLD_DRANK 3
#define PROTOCOL_CMD_BLESS_LOOK_WORLD_DRANK 4
#define PROTOCOL_CMD_BLESS_CIVILIZATION_LEVEL 5
#define PROTOCOL_CMD_BLESS_LOOK_BLESS_RANK 6
#define PROTOCOL_CMD_BLESS_GUILD_MEM 7

#define PROTOCOL_RSPCMD_BLESS_WORLD_DRANK 3
#define PROTOCOL_RSPCMD_BLESS_LOOK_WORLD_DRANK 4
#define PROTOCOL_RSPCMD_BLESS_CIVILIZATION_LEVEL 5
#define PROTOCOL_RSPCMD_BLESS_LOOK_BLESS_RANK 6
#define PROTOCOL_RSPCMD_BLESS_GUILD_MEM 7

//circle
#define PROTOCOL_CMD_CIRCLE_NPC_INFO 1

//Luck draw
#define PROTOCOL_CMD_LUCK_DRAW 1

//hit jar
#define PROTOCOL_CMD_HIT_JAR_WIN 1
#define PROTOCOL_CMD_HIT_JAR_GET_AWARD 2
#define PROTOCOL_CMD_HIT_JAR_HIT 3
#define PROTOCOL_CMD_HIT_JAR_SET_RANK_AWARD 4
#define PROTOCOL_CMD_HIT_JAR_BROADCAST 5
#define PROTOCOL_CMD_HIT_JAR_GET_BROADCAST 6

//invest plan
#define PROTOCOL_CMD_INVEST_PLAN_QUERY 1
#define PROTOCOL_CMD_INVEST_PLAN_INVEST 2
#define PROTOCOL_CMD_INVEST_PLAN_REWARD 3

// group buy
#define PROTOCOL_CMD_GROUPBUY_QUERY 1
#define PROTOCOL_CMD_GROUPBUY_REWARD 2
// treasure box
#define PROTOCOL_CMD_TREASUREBOX_QUERY	1
#define PROTOCOL_CMD_TREASUREBOX_OPEN	2
#define PROTOCOL_CMD_TREASUREBOX_RESET	3
#define PROTOCOL_CMD_TREASUREBOX_ACCEPTPRIZE	4
#define PROTOCOL_RSPCMD_TREASUREBOX_BOXINFO		1
#define PROTOCOL_RSPCMD_TREASUREBOX_ACTIVON		2
#define PROTOCOL_RSPCMD_TREASUREBOX_BROADCAST	3

#define PROTOCOL_CMD_CROSS_LOGIN 1
#define PROTOCOL_CMD_KICK_CROSS_USER 2

#define PROTOCOL_RSPCMD_ENTERGAME 1
#define PROTOCOL_RSPCMD_APPEAR 2
#define PROTOCOL_RSPCMD_SPECIAL_ENTITY_APPEAR 53
#define PROTOCOL_RSPCMD_CHANGEMAP 13

#define PROTOCOL_RSPCMD_CRTMAINACTOR 3
#define PROTOCOL_RSPCMD_CRTOTHACTOR 4
#define PROTOCOL_RSPCMD_WALK 9
#define PROTOCOL_RSPCMD_RUN 15
#define PROTOCOL_RSPCMD_DISAPPEAR 5
#define PROTOCOL_RSPCMD_TRANSPORT 14
#define PROTOCOL_RSPCMD_MA_TRANSPORT 13
#define PROTOCOL_RSPCMD_MA_SETPOS 8
#define PROTOCOL_RSPCMD_SVRTIME 8
#define PROTOCOL_RSPCMD_CONFIRM 24
#define PROTOCOL_RSPCMD_CHANGENAME 40
#define PROTOCOL_RSPCMD_ENTITY_PROPCHANGE 6
#define PROTOCOL_RSPCMD_MAINACTOR_PROPCHANGE 7
#define PROTOCOL_RSPCMD_MY_EQUIP 3
#define PROTOCOL_RSPCMD_OTHER_EQUIP 5
#define PROTOCOL_RSPCMD_RANK_EQUIP  7
#define PROTOCOL_RSPCMD_QUERY_ITEM 4
#define PROTOCOL_RSPCMD_ADD_BUFF 1
#define PROTOCOL_RSPCMD_DEL_BUFF 2
#define PROTOCOL_RSPCMD_DEL_BUFF_BY_TYPE 3
#define PROTOCOL_RSPCMD_OPEN_SYSTEM_WIN 12
#define PROTOCOL_RSPCMD_DROP_ITEM_APPEAR 10
#define PROTOCOL_RSPCMD_DROP_ITEM_DISAPPEAR 11
#define PROTOCOL_RSPCMD_ACT_RESULT 24
#define PROTOCOL_RSPCMD_SKILL_UNDER_ATTACK 6
#define PROTOCOL_RSPCMD_SKILL_HIT_TARGET 7
#define PROTOCOL_RSPCMD_ACTOR_DIE 35
#define PROTOCOL_RSPCMD_NEW_ITEM 16
#define PROTOCOL_RSPCMD_NEW_EQUIP 13
#define PROTOCOL_RSPCMD_ITEM_COUNT_CHANGE 3
#define PROTOCOL_RSPCMD_SHORTCUT_GET_ALL 2

#define PROTOCOL_RSPCMD_ACTIVENESS 1
#define PROTOCOL_RSPCMD_ACTIVENESS_REWARD 2

#define PROTOCOL_RSPCMD_START_DAY 28
#define PROTOCOL_RSPCMD_CHAT_GET_SYSTEM_TIP 2
#define PROTOCOL_RSPCMD_STORE_QUERY 1
#define PROTOCOL_RSPCMD_STORE_ADD 2
#define PROTOCOL_RSPCMD_STORE_DEL 3
#define PROTOCOL_RSPCMD_STORE_ITEM_CHANGE 6
#define PROTOCOL_RSPCMD_PROMPT_BAG_CLEAR  22
#define PROTOCOL_RSPCMD_NORMAL_ATTACK  26
#define PROTOCOL_RSPCMD_EQUIP_WEAR 1
#define PROTOCOL_RSPCMD_EQUIP_UNWEAR 2
#define PROTOCOL_RSPCMD_EQUIP_DURA 4
#define PROTOCOL_PSPCMD_NPCDEAL_SELL 4
#define PROTOCOL_RSPCMD_NPCDEAL_REBUY 5
#define PROTOCOL_RSPCMD_TRAFFIC_ON 1
#define PROTOCOL_RSPCMD_TRAFFIC_OFF 2
#define PROTOCOL_RSPCMD_TRAFFIC_MOVE 3
#define PROTOCOL_RSPCMD_PK_SET_MODE 3
#define PROTOCOL_RSPCMD_MARKET_ENABLE 9
#define PROTOCOL_RSPCMD_MARKET_TALK 2
#define PROTOCOL_RSPCMD_MARKET_DOBUY 3
#define PROTOCOL_RSPCMD_MARKET_REFRESH 6
#define PROTOCOL_RSPCMD_MARKET_BUYED 8
#define PROTOCOL_RSPCMD_MARKET_DOCHECK 1
#define PROTOCOL_RSPCMD_MARKET_RESULT 5
#define PROTOCOL_RSPCMD_MARKET_CHANGE 7
#define PROTOCOL_RSPCMD_MARKET_CHECK 10

#define PROTOCOL_RSPCMD_CHARGE		100
#define PROTOCOL_RSPCMD_TIME_ACTIVITY 101
#define PROTOCOL_RSPCMD_LIMIT_PAY	102
#define PROTOCOL_RSPCMD_OTHER_GET_SYSTEM_CONFIG 31

#define PROTOCOL_RSPCMD_ADD_ACTOR_EFFECT 19
#define PROTOCOL_RSPCMD_ADD_SCENCE_EFFECT 32

#define PROTOCOL_RSPCMD_SHABAK_SIGNUP_INFO 2
#define PROTOCOL_RSPCMD_SHABAK_INFO 3

#define PROTOCOL_RSPCMD_MOUNT_UPDATE_TIME 5
#define PROTOCOL_RSPCMD_MOUNT_TIME_LIST 4
#define PROTOCOL_RSPCMD_MOUNT_UP_LEVEL 2
#define PROTOCOL_RSPCMD_MOUNT_UP_BATCH 3
#define PROTOCOL_RSPCMD_NAME_COLOR_CHANGE 37
#define PROTOCOL_RSPCMD_REMOVE_EFFECT 39
#define PROTOCOL_RSPCMD_LOGIC_MAP_AREA_STATE_CHANGE  41
#define PROTOCOL_RSPCMD_BAG_DELETE_ITEM 1
#define PROTOCOL_RSPCMD_BAG_ADD_ITEM 2
#define PROTOCOL_RSPCMD_BAG_EXT_PRICE 5
#define PROTOCOL_RSPCMD_BAG_STRENGTH_RESULT 8
#define PROTOCOL_RSPCMD_BAG_CHANGE 9
#define PROTOCOL_RSPCMD_BAG_TIMEUP 14
#define PROTOCOL_RSPCMD_BAG_STRENGTH_NEEDS 15
#define PROTOCOL_RSPCMD_BAG_DECOMPOSE_PREVIEW 30
#define PROTOCOL_RSPCMD_BAG_DECOMPOSE 18
#define PROTOCOL_RSPCMD_BAG_UPGRADES 19
#define PROTOCOL_RSPCMD_BAG_SEND_RESOLVE_BACK 20
#define PROTOCOL_RSPCMD_BAG_SEND_COMPOSE_NEED_ITEMS 31
#define PROTOCOL_RSPCMD_BAG_COMPSE_SUCESS 32
#define PROTOCOL_RSPCMD_ONLINE_GIFT 1
#define PROTOCOL_RSPCMD_ENTITY_MOVE 9
#define PROTOCOL_RSPCMD_ENTITY_POS 56
#define PROTOCOL_RSPCMD_TEAM_INVITELIST 4
#define PROTOCOL_RSPCMD_INVITE_INTO_TEAM 10
#define PROTOCOL_RSPCMD_QUIT_TEAM 3
#define PROTOCOL_RSPCMD_TEAM_ADD_MEMBER 2
#define PROTOCOL_RSPCMD_TEAM_INIT_MEMBER 1
#define PROTOCOL_RSPCMD_TEAM_MEMBER_OFFLINE 7
#define PROTOCAL_RSPCMD_APPLY_JOIN_TEAM 9
#define PROTOCAL_RSPCMD_TEAM_LEADER_CHANGE 4
#define PROTOCOL_RSPCMD_TEAM_PRO_CHANGE 8
#define PROTOCOL_RSPCMD_TEAM_POS_CHANGE 12
#define PROTOCOL_RSPCMD_GUILD_INFO 1
#define PROTOCOL_RSPCMD_GUILD_MEMS 2
#define PROTOCOL_RSPCMD_GUILD_LIST 3
#define PROTOCOL_RSPCMD_GUILD_CARD 4
#define PROTOCOL_RSPCMD_GUILD_CREATE 5
#define PROTOCOL_RSPCMD_GUILD_INVITE 7
#define PROTOCOL_RSPCMD_GUILD_APPLYLIST 11
#define PROTOCOL_RSPCMD_GUILD_STORE_DEPOSIT 32
#define PROTOCOL_RSPCMD_GUILD_STORE_TAKE_OUT 33
#define PROTOCOL_RSPCMD_GUILD_STORE 34
#define PROTOCOL_RSPCMD_GUILD_CALL_ONE 21
#define PROTOCOL_RSPCMD_GUILD_CALL 55
#define PROTOCOL_RSPCMD_GUILD_STORE_EVENT 35
#define PROTOCOL_RSPCMD_GUILD_COMPETITON_POS 36
#define PROTOCOL_RSPCMD_GUILD_EVENT 38
#define PROTOCOL_RSPCMD_GUILD_TITLE 41
#define PROTOCOL_RSPCMD_GUILD_TITLE_EDIT 42
#define PROTOCOL_RSPCMD_GUILD_MEMBERS 44
#define PROTOCOL_RSPCMD_GUILD_EXPAND 45
#define PROTOCOL_RSPCMD_GUILD_NPC 52
#define PROTOCOL_RSPCMD_FIX 2

#define PROTOCOL_RSPCMD_CHARGE		100
#define PROTOCOL_RSPCMD_TIME_ACTIVITY 101
#define PROTOCOL_RSPCMD_LIMIT_PAY	102
#define PROTOCOL_RSPCMD_PAY_STAGE	103
#define PROTOCOL_RSPCMD_OPEN_INTERFACE 		110
#define PROTOCOL_RSPCMD_LIMIT_QUAN_LOGIN  121
#define PROTOCOL_RSPCMD_LIMIT_QUAN_GIFT	  120
#define PROTOCOL_RSPCMD_DAILY_CHARGE	125
#define PROTOCOL_RSPCMD_DAILY_CHARGE_OPEN 126
#define PROTOCOL_RSPCMD_MERGE_SRV_CHARGE	130
#define PROTOCOL_RSPCMD_NEW_SRV_CHARGE 	150
#define PROTOCOL_RSPCMD_STAGE_CONSUME_OPEN 1
#define PROTOCOL_RSPCMD_STAGE_CONSUME 2
#define PROTOCOL_RSPCMD_TRACE_REQ 1
#define PROTOCOL_RSPCMD_TRACE_REFUSE 2
#define PROTOCOL_RSPCMD_TRACE_BEGIN 3
#define PROTOCOL_RSPCMD_TRADE_ADDRLT 4
#define PROTOCOL_RSPCMD_TRADE_ADDPEER 5
#define PROTOCOL_RSPCMD_TRADE_SELF_MONEY 6
#define PROTOCOL_RSPCMD_TRADE_PEER_MONEY 7
#define PROTOCOL_RSPCMD_TRADE_LOCK 8
#define PROTOCOL_RSPCMD_TRADE_CANCEL 9
#define PROTOCOL_RSPCMD_TRADE_DONE 11
#define PROTOCOL_RSPCMD_ENTITY_SPECIAL_MOVE 54
#define PROTOCOL_RSPCMD_ENTITY_SPECIAL_MOVE_BACK  55
#define PROTOCOL_RSPCMD_ENTITY_PRE_SPECIAL_MOVE 30
#define PROTOCOL_RSPCMD_NPC_QUEST_STATE 33
#define PROTOCOL_RSPCMD_OTHER_GUIDE_MOVIE 9		//副本引导动画
#define PROTOCOL_RSPCMD_OTHER_INIT_ACTIVE 21	//副本面板初始化
#define PROTOCOL_RSPCMD_OTHER_CHANGE_ACTIVE_PROCESS 22 //副本进度变化
#define PROTOCOL_RSPCMD_OTHER_GET_CARBON_TIMES 47
#define PROTOCOL_RSPCMD_OTHER_CHANGE_NAME 50
#define PROTOCOL_RSPCMD_MAP_AREA_STATE_CHANG 41	//地图中某区域状态改变
#define PROTOCOL_RSPCMD_SERVE_CONTROL_BOX 22	//后台给出多个选项选择
#define PROTOCOL_RSPCMD_GET_YELLOW_VIP 1
#define PROTOCOL_RSPCMD_TITLE_LIST 1
#define PROTOCOL_RSPCMD_ADD_TITLE 2
#define PROTOCOL_RSPCMD_TITLE_CONDITION 5
#define PROTOCOL_RSPCMD_FRIEND_ADD_ASK_BACK 1
#define PROTOCOL_RSPCMD_FRIEND_ADD_OR_DEL_BACK 2
#define PROTOCOL_RSPCMD_FRIEND_LIST_BACK 3
#define PROTOCOL_RSPCMD_FRIEND_TRACK_BACK 5
#define PROTOCOL_RSPCMD_FRIEND_MSG_BACK 9
#define PROTOCOL_RSPCMD_FRIEND_SMITH 13
#define PROTOCOL_RSPCMD_OTHER_RAIN 19
#define PROTOCOL_RSPCMD_OTHER_EXP_CHANGE 20
#define PROTOCOL_RSPCMD_CONVOY_INFO_BACK 3
#define PROTOCOL_RSPCMD_CONVOY_OPEN_WIN 4
#define PROTOCOL_RSPCMD_CONVOY_FLESH_BACK 6
#define PROTOCOL_RSPCMD_CONVOY_LAST_COUNT 8
#define PROTOCOL_RSPCMD_CONVOY_BUY_VIP 9
#define PROTOCOL_RSPCMD_OTHER_ENTITY 15
#define PROTOCOL_RSPCMD_CONVOY_FINISH 7
#define PROTOCOL_RSPCMD_CONVOY_LAST_COUNT_WIN 22
#define PROTOCOL_RSPCMD_SEVENDAYS_INFO 1
#define PROTOCOL_RSPCMD_STONE_IN 1
#define PROTOCOL_RSPCMD_STONE_OUT 2
#define PROTOCOL_RSPCMD_STONE_INFO 3
#define PROTOCOL_RSPCMD_STONE_UPGRADE 4
#define PROTOCOL_RSPCMD_STONE_OTHER_INFO 5
#define PROTOCOL_RSPCMD_LUCK_DRAW_BACK 1
#define PROTOCOL_RSPCMD_LUCK_DRAW_OPEN 2
#define PROTOCOL_RSPCMD_LUCK_DRAW_STOP 3
#define PROTOCOL_RSPCMD_LUCK_DRAW_FAIL 4
#define PROTOCOL_RSPCMD_LUCK_DRAW_COUNT 5

#define PROTOCOL_CMD_ACTIVITY_CROSS_WORLD_BOSS_RANK 1
//hit jar
#define PROTOCOL_RSPCMD_HIT_JAR_WIN_BACK 1
#define PROTOCOL_RSPCMD_HIT_JAR_ITEM 2
#define PROTOCOL_RSPCMD_HIT_JAR_TIME 3
#define PROTOCOL_RSPCMD_HIT_JAR_AWARD 4
#define PROTOCOL_RSPCMD_HIT_JAR_BROADCAST 5

#define PROTOCOL_RSPCMD_PAY_POINTS	2

#define PROTOCOL_RSPCMD_INVEST_PLAN      1
#define PROTOCOL_RSPCMD_INVEST_PLAN_TIME 2


#define GUILD_TITLE_LENGTH 7

//购买物品返回
#define PAYITEM_ERROR 4


//协议包结构
//WORD Head 52462
//WORD PacketLength	包体长度，不包含包头部分
//WORD Cmd 命令字 1 转包，2转包应答  3 心跳  4 用户离线
//DWORD fd socketfd
//DWORD time 连接时间，秒
//DWORD microtime 连接时间，毫秒
//BYTE[PacketLength]	Body	包体


//#pragma pack(1)
//typedef struct{
//	uint16_t head;
//	uint16_t bodyLen;
//	uint16_t cmd;
//	uint32_t fd;
//	uint32_t time;
//	uint32_t microTime;
//  uint32_t clientIp;
//}PacketHead;
//#pragma pack()


// 协议包头数据
class CFirePacket :
	public IPacket,
	public IEncodable,
	public IDecodable
{

public:

	int ChannelId;	//通道ID

	uint16_t head;
	uint16_t bodyLen;
	uint16_t cmd;
	uint32_t fd;
	uint32_t time;
	uint32_t microTime;
	uint32_t clientIp;	//原始客户端的ip

	byte protocolType;
	byte command;

	uint32_t uid;
	uint32_t rid;


	CStaticBuffer<MAX_PROTOCOL_BODY_SIZE> body;	//包体

public:

	CFirePacket();

	virtual bool Encode(IBuffer *pBuffer);
	virtual bool Decode(IBuffer *pBuffer);
	bool SetBody(IBuffer* pBuf);

	uint32_t GetDecodeSize(){return m_decodeSize;}

	IMPLEMENT_TO_STRING("cid=%d&len=%u&cmd=%u&fd=%u&time=%u&microTime=%u&protocolType=%d&command=%d",ChannelId, bodyLen,cmd,fd,time,microTime,protocolType,command);

private:
	uint32_t m_decodeSize;

};

#endif /* PACKET_H_ */
