// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: ProtoFriend.proto

#ifndef PROTOBUF_ProtoFriend_2eproto__INCLUDED
#define PROTOBUF_ProtoFriend_2eproto__INCLUDED

#include <string>

#include <google/protobuf/stubs/common.h>

#if GOOGLE_PROTOBUF_VERSION < 2004000
#error This file was generated by a newer version of protoc which is
#error incompatible with your Protocol Buffer headers.  Please update
#error your headers.
#endif
#if 2004001 < GOOGLE_PROTOBUF_MIN_PROTOC_VERSION
#error This file was generated by an older version of protoc which is
#error incompatible with your Protocol Buffer headers.  Please
#error regenerate this file with a newer version of protoc.
#endif

#include <google/protobuf/generated_message_util.h>
#include <google/protobuf/repeated_field.h>
#include <google/protobuf/extension_set.h>
#include <google/protobuf/generated_message_reflection.h>
#include "DataCommon.pb.h"
// @@protoc_insertion_point(includes)

namespace ProtoFriend {

// Internal implementation detail -- do not call these.
void  protobuf_AddDesc_ProtoFriend_2eproto();
void protobuf_AssignDesc_ProtoFriend_2eproto();
void protobuf_ShutdownFile_ProtoFriend_2eproto();

class RecommendInfo;
class ProtoRecommendUserReq;
class ProtoRecommendUserResp;
class ProtoGetFriendsReq;
class ProtoGetFriendsResp;
class ProtoCSGetFriendsReq;
class ProtoCSGetFriendsResp;
class ProtoConcernReq;
class ProtoConcernResp;
class ProtoCSConcernReq;
class ProtoCSConcernResp;
class ProtoCancelConcernReq;
class ProtoDonatePowerReq;
class ProtoDonatePowerResp;
class ProtoCSDonatePowerReq;

// ===================================================================

class RecommendInfo : public ::google::protobuf::Message {
 public:
  RecommendInfo();
  virtual ~RecommendInfo();
  
  RecommendInfo(const RecommendInfo& from);
  
  inline RecommendInfo& operator=(const RecommendInfo& from) {
    CopyFrom(from);
    return *this;
  }
  
  inline const ::google::protobuf::UnknownFieldSet& unknown_fields() const {
    return _unknown_fields_;
  }
  
  inline ::google::protobuf::UnknownFieldSet* mutable_unknown_fields() {
    return &_unknown_fields_;
  }
  
  static const ::google::protobuf::Descriptor* descriptor();
  static const RecommendInfo& default_instance();
  
  void Swap(RecommendInfo* other);
  
  // implements Message ----------------------------------------------
  
  RecommendInfo* New() const;
  void CopyFrom(const ::google::protobuf::Message& from);
  void MergeFrom(const ::google::protobuf::Message& from);
  void CopyFrom(const RecommendInfo& from);
  void MergeFrom(const RecommendInfo& from);
  void Clear();
  bool IsInitialized() const;
  
  int ByteSize() const;
  bool MergePartialFromCodedStream(
      ::google::protobuf::io::CodedInputStream* input);
  void SerializeWithCachedSizes(
      ::google::protobuf::io::CodedOutputStream* output) const;
  ::google::protobuf::uint8* SerializeWithCachedSizesToArray(::google::protobuf::uint8* output) const;
  int GetCachedSize() const { return _cached_size_; }
  private:
  void SharedCtor();
  void SharedDtor();
  void SetCachedSize(int size) const;
  public:
  
  ::google::protobuf::Metadata GetMetadata() const;
  
  // nested types ----------------------------------------------------
  
  // accessors -------------------------------------------------------
  
  // required uint32 uid = 1;
  inline bool has_uid() const;
  inline void clear_uid();
  static const int kUidFieldNumber = 1;
  inline ::google::protobuf::uint32 uid() const;
  inline void set_uid(::google::protobuf::uint32 value);
  
  // required string name = 2;
  inline bool has_name() const;
  inline void clear_name();
  static const int kNameFieldNumber = 2;
  inline const ::std::string& name() const;
  inline void set_name(const ::std::string& value);
  inline void set_name(const char* value);
  inline void set_name(const char* value, size_t size);
  inline ::std::string* mutable_name();
  inline ::std::string* release_name();
  
  // required string fig = 3;
  inline bool has_fig() const;
  inline void clear_fig();
  static const int kFigFieldNumber = 3;
  inline const ::std::string& fig() const;
  inline void set_fig(const ::std::string& value);
  inline void set_fig(const char* value);
  inline void set_fig(const char* value, size_t size);
  inline ::std::string* mutable_fig();
  inline ::std::string* release_fig();
  
  // required uint32 level = 4;
  inline bool has_level() const;
  inline void clear_level();
  static const int kLevelFieldNumber = 4;
  inline ::google::protobuf::uint32 level() const;
  inline void set_level(::google::protobuf::uint32 value);
  
  // required uint32 grade = 5;
  inline bool has_grade() const;
  inline void clear_grade();
  static const int kGradeFieldNumber = 5;
  inline ::google::protobuf::uint32 grade() const;
  inline void set_grade(::google::protobuf::uint32 value);
  
  // optional uint32 onlineTs = 6;
  inline bool has_onlinets() const;
  inline void clear_onlinets();
  static const int kOnlineTsFieldNumber = 6;
  inline ::google::protobuf::uint32 onlinets() const;
  inline void set_onlinets(::google::protobuf::uint32 value);
  
  // optional uint32 donationTs = 7;
  inline bool has_donationts() const;
  inline void clear_donationts();
  static const int kDonationTsFieldNumber = 7;
  inline ::google::protobuf::uint32 donationts() const;
  inline void set_donationts(::google::protobuf::uint32 value);
  
  // optional uint32 battleTs = 8;
  inline bool has_battlets() const;
  inline void clear_battlets();
  static const int kBattleTsFieldNumber = 8;
  inline ::google::protobuf::uint32 battlets() const;
  inline void set_battlets(::google::protobuf::uint32 value);
  
  // optional uint32 battle = 9;
  inline bool has_battle() const;
  inline void clear_battle();
  static const int kBattleFieldNumber = 9;
  inline ::google::protobuf::uint32 battle() const;
  inline void set_battle(::google::protobuf::uint32 value);
  
  // repeated uint32 heroId = 10;
  inline int heroid_size() const;
  inline void clear_heroid();
  static const int kHeroIdFieldNumber = 10;
  inline ::google::protobuf::uint32 heroid(int index) const;
  inline void set_heroid(int index, ::google::protobuf::uint32 value);
  inline void add_heroid(::google::protobuf::uint32 value);
  inline const ::google::protobuf::RepeatedField< ::google::protobuf::uint32 >&
      heroid() const;
  inline ::google::protobuf::RepeatedField< ::google::protobuf::uint32 >*
      mutable_heroid();
  
  // @@protoc_insertion_point(class_scope:ProtoFriend.RecommendInfo)
 private:
  inline void set_has_uid();
  inline void clear_has_uid();
  inline void set_has_name();
  inline void clear_has_name();
  inline void set_has_fig();
  inline void clear_has_fig();
  inline void set_has_level();
  inline void clear_has_level();
  inline void set_has_grade();
  inline void clear_has_grade();
  inline void set_has_onlinets();
  inline void clear_has_onlinets();
  inline void set_has_donationts();
  inline void clear_has_donationts();
  inline void set_has_battlets();
  inline void clear_has_battlets();
  inline void set_has_battle();
  inline void clear_has_battle();
  
  ::google::protobuf::UnknownFieldSet _unknown_fields_;
  
  ::std::string* name_;
  ::google::protobuf::uint32 uid_;
  ::google::protobuf::uint32 level_;
  ::std::string* fig_;
  ::google::protobuf::uint32 grade_;
  ::google::protobuf::uint32 onlinets_;
  ::google::protobuf::uint32 donationts_;
  ::google::protobuf::uint32 battlets_;
  ::google::protobuf::RepeatedField< ::google::protobuf::uint32 > heroid_;
  ::google::protobuf::uint32 battle_;
  
  mutable int _cached_size_;
  ::google::protobuf::uint32 _has_bits_[(10 + 31) / 32];
  
  friend void  protobuf_AddDesc_ProtoFriend_2eproto();
  friend void protobuf_AssignDesc_ProtoFriend_2eproto();
  friend void protobuf_ShutdownFile_ProtoFriend_2eproto();
  
  void InitAsDefaultInstance();
  static RecommendInfo* default_instance_;
};
// -------------------------------------------------------------------

class ProtoRecommendUserReq : public ::google::protobuf::Message {
 public:
  ProtoRecommendUserReq();
  virtual ~ProtoRecommendUserReq();
  
  ProtoRecommendUserReq(const ProtoRecommendUserReq& from);
  
  inline ProtoRecommendUserReq& operator=(const ProtoRecommendUserReq& from) {
    CopyFrom(from);
    return *this;
  }
  
  inline const ::google::protobuf::UnknownFieldSet& unknown_fields() const {
    return _unknown_fields_;
  }
  
  inline ::google::protobuf::UnknownFieldSet* mutable_unknown_fields() {
    return &_unknown_fields_;
  }
  
  static const ::google::protobuf::Descriptor* descriptor();
  static const ProtoRecommendUserReq& default_instance();
  
  void Swap(ProtoRecommendUserReq* other);
  
  // implements Message ----------------------------------------------
  
  ProtoRecommendUserReq* New() const;
  void CopyFrom(const ::google::protobuf::Message& from);
  void MergeFrom(const ::google::protobuf::Message& from);
  void CopyFrom(const ProtoRecommendUserReq& from);
  void MergeFrom(const ProtoRecommendUserReq& from);
  void Clear();
  bool IsInitialized() const;
  
  int ByteSize() const;
  bool MergePartialFromCodedStream(
      ::google::protobuf::io::CodedInputStream* input);
  void SerializeWithCachedSizes(
      ::google::protobuf::io::CodedOutputStream* output) const;
  ::google::protobuf::uint8* SerializeWithCachedSizesToArray(::google::protobuf::uint8* output) const;
  int GetCachedSize() const { return _cached_size_; }
  private:
  void SharedCtor();
  void SharedDtor();
  void SetCachedSize(int size) const;
  public:
  
  ::google::protobuf::Metadata GetMetadata() const;
  
  // nested types ----------------------------------------------------
  
  // accessors -------------------------------------------------------
  
  // @@protoc_insertion_point(class_scope:ProtoFriend.ProtoRecommendUserReq)
 private:
  
  ::google::protobuf::UnknownFieldSet _unknown_fields_;
  
  
  mutable int _cached_size_;
  ::google::protobuf::uint32 _has_bits_[1];
  
  friend void  protobuf_AddDesc_ProtoFriend_2eproto();
  friend void protobuf_AssignDesc_ProtoFriend_2eproto();
  friend void protobuf_ShutdownFile_ProtoFriend_2eproto();
  
  void InitAsDefaultInstance();
  static ProtoRecommendUserReq* default_instance_;
};
// -------------------------------------------------------------------

class ProtoRecommendUserResp : public ::google::protobuf::Message {
 public:
  ProtoRecommendUserResp();
  virtual ~ProtoRecommendUserResp();
  
  ProtoRecommendUserResp(const ProtoRecommendUserResp& from);
  
  inline ProtoRecommendUserResp& operator=(const ProtoRecommendUserResp& from) {
    CopyFrom(from);
    return *this;
  }
  
  inline const ::google::protobuf::UnknownFieldSet& unknown_fields() const {
    return _unknown_fields_;
  }
  
  inline ::google::protobuf::UnknownFieldSet* mutable_unknown_fields() {
    return &_unknown_fields_;
  }
  
  static const ::google::protobuf::Descriptor* descriptor();
  static const ProtoRecommendUserResp& default_instance();
  
  void Swap(ProtoRecommendUserResp* other);
  
  // implements Message ----------------------------------------------
  
  ProtoRecommendUserResp* New() const;
  void CopyFrom(const ::google::protobuf::Message& from);
  void MergeFrom(const ::google::protobuf::Message& from);
  void CopyFrom(const ProtoRecommendUserResp& from);
  void MergeFrom(const ProtoRecommendUserResp& from);
  void Clear();
  bool IsInitialized() const;
  
  int ByteSize() const;
  bool MergePartialFromCodedStream(
      ::google::protobuf::io::CodedInputStream* input);
  void SerializeWithCachedSizes(
      ::google::protobuf::io::CodedOutputStream* output) const;
  ::google::protobuf::uint8* SerializeWithCachedSizesToArray(::google::protobuf::uint8* output) const;
  int GetCachedSize() const { return _cached_size_; }
  private:
  void SharedCtor();
  void SharedDtor();
  void SetCachedSize(int size) const;
  public:
  
  ::google::protobuf::Metadata GetMetadata() const;
  
  // nested types ----------------------------------------------------
  
  // accessors -------------------------------------------------------
  
  // repeated .ProtoFriend.RecommendInfo user = 1;
  inline int user_size() const;
  inline void clear_user();
  static const int kUserFieldNumber = 1;
  inline const ::ProtoFriend::RecommendInfo& user(int index) const;
  inline ::ProtoFriend::RecommendInfo* mutable_user(int index);
  inline ::ProtoFriend::RecommendInfo* add_user();
  inline const ::google::protobuf::RepeatedPtrField< ::ProtoFriend::RecommendInfo >&
      user() const;
  inline ::google::protobuf::RepeatedPtrField< ::ProtoFriend::RecommendInfo >*
      mutable_user();
  
  // @@protoc_insertion_point(class_scope:ProtoFriend.ProtoRecommendUserResp)
 private:
  
  ::google::protobuf::UnknownFieldSet _unknown_fields_;
  
  ::google::protobuf::RepeatedPtrField< ::ProtoFriend::RecommendInfo > user_;
  
  mutable int _cached_size_;
  ::google::protobuf::uint32 _has_bits_[(1 + 31) / 32];
  
  friend void  protobuf_AddDesc_ProtoFriend_2eproto();
  friend void protobuf_AssignDesc_ProtoFriend_2eproto();
  friend void protobuf_ShutdownFile_ProtoFriend_2eproto();
  
  void InitAsDefaultInstance();
  static ProtoRecommendUserResp* default_instance_;
};
// -------------------------------------------------------------------

class ProtoGetFriendsReq : public ::google::protobuf::Message {
 public:
  ProtoGetFriendsReq();
  virtual ~ProtoGetFriendsReq();
  
  ProtoGetFriendsReq(const ProtoGetFriendsReq& from);
  
  inline ProtoGetFriendsReq& operator=(const ProtoGetFriendsReq& from) {
    CopyFrom(from);
    return *this;
  }
  
  inline const ::google::protobuf::UnknownFieldSet& unknown_fields() const {
    return _unknown_fields_;
  }
  
  inline ::google::protobuf::UnknownFieldSet* mutable_unknown_fields() {
    return &_unknown_fields_;
  }
  
  static const ::google::protobuf::Descriptor* descriptor();
  static const ProtoGetFriendsReq& default_instance();
  
  void Swap(ProtoGetFriendsReq* other);
  
  // implements Message ----------------------------------------------
  
  ProtoGetFriendsReq* New() const;
  void CopyFrom(const ::google::protobuf::Message& from);
  void MergeFrom(const ::google::protobuf::Message& from);
  void CopyFrom(const ProtoGetFriendsReq& from);
  void MergeFrom(const ProtoGetFriendsReq& from);
  void Clear();
  bool IsInitialized() const;
  
  int ByteSize() const;
  bool MergePartialFromCodedStream(
      ::google::protobuf::io::CodedInputStream* input);
  void SerializeWithCachedSizes(
      ::google::protobuf::io::CodedOutputStream* output) const;
  ::google::protobuf::uint8* SerializeWithCachedSizesToArray(::google::protobuf::uint8* output) const;
  int GetCachedSize() const { return _cached_size_; }
  private:
  void SharedCtor();
  void SharedDtor();
  void SetCachedSize(int size) const;
  public:
  
  ::google::protobuf::Metadata GetMetadata() const;
  
  // nested types ----------------------------------------------------
  
  // accessors -------------------------------------------------------
  
  // @@protoc_insertion_point(class_scope:ProtoFriend.ProtoGetFriendsReq)
 private:
  
  ::google::protobuf::UnknownFieldSet _unknown_fields_;
  
  
  mutable int _cached_size_;
  ::google::protobuf::uint32 _has_bits_[1];
  
  friend void  protobuf_AddDesc_ProtoFriend_2eproto();
  friend void protobuf_AssignDesc_ProtoFriend_2eproto();
  friend void protobuf_ShutdownFile_ProtoFriend_2eproto();
  
  void InitAsDefaultInstance();
  static ProtoGetFriendsReq* default_instance_;
};
// -------------------------------------------------------------------

class ProtoGetFriendsResp : public ::google::protobuf::Message {
 public:
  ProtoGetFriendsResp();
  virtual ~ProtoGetFriendsResp();
  
  ProtoGetFriendsResp(const ProtoGetFriendsResp& from);
  
  inline ProtoGetFriendsResp& operator=(const ProtoGetFriendsResp& from) {
    CopyFrom(from);
    return *this;
  }
  
  inline const ::google::protobuf::UnknownFieldSet& unknown_fields() const {
    return _unknown_fields_;
  }
  
  inline ::google::protobuf::UnknownFieldSet* mutable_unknown_fields() {
    return &_unknown_fields_;
  }
  
  static const ::google::protobuf::Descriptor* descriptor();
  static const ProtoGetFriendsResp& default_instance();
  
  void Swap(ProtoGetFriendsResp* other);
  
  // implements Message ----------------------------------------------
  
  ProtoGetFriendsResp* New() const;
  void CopyFrom(const ::google::protobuf::Message& from);
  void MergeFrom(const ::google::protobuf::Message& from);
  void CopyFrom(const ProtoGetFriendsResp& from);
  void MergeFrom(const ProtoGetFriendsResp& from);
  void Clear();
  bool IsInitialized() const;
  
  int ByteSize() const;
  bool MergePartialFromCodedStream(
      ::google::protobuf::io::CodedInputStream* input);
  void SerializeWithCachedSizes(
      ::google::protobuf::io::CodedOutputStream* output) const;
  ::google::protobuf::uint8* SerializeWithCachedSizesToArray(::google::protobuf::uint8* output) const;
  int GetCachedSize() const { return _cached_size_; }
  private:
  void SharedCtor();
  void SharedDtor();
  void SetCachedSize(int size) const;
  public:
  
  ::google::protobuf::Metadata GetMetadata() const;
  
  // nested types ----------------------------------------------------
  
  // accessors -------------------------------------------------------
  
  // repeated .ProtoFriend.RecommendInfo user = 1;
  inline int user_size() const;
  inline void clear_user();
  static const int kUserFieldNumber = 1;
  inline const ::ProtoFriend::RecommendInfo& user(int index) const;
  inline ::ProtoFriend::RecommendInfo* mutable_user(int index);
  inline ::ProtoFriend::RecommendInfo* add_user();
  inline const ::google::protobuf::RepeatedPtrField< ::ProtoFriend::RecommendInfo >&
      user() const;
  inline ::google::protobuf::RepeatedPtrField< ::ProtoFriend::RecommendInfo >*
      mutable_user();
  
  // @@protoc_insertion_point(class_scope:ProtoFriend.ProtoGetFriendsResp)
 private:
  
  ::google::protobuf::UnknownFieldSet _unknown_fields_;
  
  ::google::protobuf::RepeatedPtrField< ::ProtoFriend::RecommendInfo > user_;
  
  mutable int _cached_size_;
  ::google::protobuf::uint32 _has_bits_[(1 + 31) / 32];
  
  friend void  protobuf_AddDesc_ProtoFriend_2eproto();
  friend void protobuf_AssignDesc_ProtoFriend_2eproto();
  friend void protobuf_ShutdownFile_ProtoFriend_2eproto();
  
  void InitAsDefaultInstance();
  static ProtoGetFriendsResp* default_instance_;
};
// -------------------------------------------------------------------

class ProtoCSGetFriendsReq : public ::google::protobuf::Message {
 public:
  ProtoCSGetFriendsReq();
  virtual ~ProtoCSGetFriendsReq();
  
  ProtoCSGetFriendsReq(const ProtoCSGetFriendsReq& from);
  
  inline ProtoCSGetFriendsReq& operator=(const ProtoCSGetFriendsReq& from) {
    CopyFrom(from);
    return *this;
  }
  
  inline const ::google::protobuf::UnknownFieldSet& unknown_fields() const {
    return _unknown_fields_;
  }
  
  inline ::google::protobuf::UnknownFieldSet* mutable_unknown_fields() {
    return &_unknown_fields_;
  }
  
  static const ::google::protobuf::Descriptor* descriptor();
  static const ProtoCSGetFriendsReq& default_instance();
  
  void Swap(ProtoCSGetFriendsReq* other);
  
  // implements Message ----------------------------------------------
  
  ProtoCSGetFriendsReq* New() const;
  void CopyFrom(const ::google::protobuf::Message& from);
  void MergeFrom(const ::google::protobuf::Message& from);
  void CopyFrom(const ProtoCSGetFriendsReq& from);
  void MergeFrom(const ProtoCSGetFriendsReq& from);
  void Clear();
  bool IsInitialized() const;
  
  int ByteSize() const;
  bool MergePartialFromCodedStream(
      ::google::protobuf::io::CodedInputStream* input);
  void SerializeWithCachedSizes(
      ::google::protobuf::io::CodedOutputStream* output) const;
  ::google::protobuf::uint8* SerializeWithCachedSizesToArray(::google::protobuf::uint8* output) const;
  int GetCachedSize() const { return _cached_size_; }
  private:
  void SharedCtor();
  void SharedDtor();
  void SetCachedSize(int size) const;
  public:
  
  ::google::protobuf::Metadata GetMetadata() const;
  
  // nested types ----------------------------------------------------
  
  // accessors -------------------------------------------------------
  
  // required uint32 myuid = 1;
  inline bool has_myuid() const;
  inline void clear_myuid();
  static const int kMyuidFieldNumber = 1;
  inline ::google::protobuf::uint32 myuid() const;
  inline void set_myuid(::google::protobuf::uint32 value);
  
  // repeated uint32 othuid = 2;
  inline int othuid_size() const;
  inline void clear_othuid();
  static const int kOthuidFieldNumber = 2;
  inline ::google::protobuf::uint32 othuid(int index) const;
  inline void set_othuid(int index, ::google::protobuf::uint32 value);
  inline void add_othuid(::google::protobuf::uint32 value);
  inline const ::google::protobuf::RepeatedField< ::google::protobuf::uint32 >&
      othuid() const;
  inline ::google::protobuf::RepeatedField< ::google::protobuf::uint32 >*
      mutable_othuid();
  
  // @@protoc_insertion_point(class_scope:ProtoFriend.ProtoCSGetFriendsReq)
 private:
  inline void set_has_myuid();
  inline void clear_has_myuid();
  
  ::google::protobuf::UnknownFieldSet _unknown_fields_;
  
  ::google::protobuf::RepeatedField< ::google::protobuf::uint32 > othuid_;
  ::google::protobuf::uint32 myuid_;
  
  mutable int _cached_size_;
  ::google::protobuf::uint32 _has_bits_[(2 + 31) / 32];
  
  friend void  protobuf_AddDesc_ProtoFriend_2eproto();
  friend void protobuf_AssignDesc_ProtoFriend_2eproto();
  friend void protobuf_ShutdownFile_ProtoFriend_2eproto();
  
  void InitAsDefaultInstance();
  static ProtoCSGetFriendsReq* default_instance_;
};
// -------------------------------------------------------------------

class ProtoCSGetFriendsResp : public ::google::protobuf::Message {
 public:
  ProtoCSGetFriendsResp();
  virtual ~ProtoCSGetFriendsResp();
  
  ProtoCSGetFriendsResp(const ProtoCSGetFriendsResp& from);
  
  inline ProtoCSGetFriendsResp& operator=(const ProtoCSGetFriendsResp& from) {
    CopyFrom(from);
    return *this;
  }
  
  inline const ::google::protobuf::UnknownFieldSet& unknown_fields() const {
    return _unknown_fields_;
  }
  
  inline ::google::protobuf::UnknownFieldSet* mutable_unknown_fields() {
    return &_unknown_fields_;
  }
  
  static const ::google::protobuf::Descriptor* descriptor();
  static const ProtoCSGetFriendsResp& default_instance();
  
  void Swap(ProtoCSGetFriendsResp* other);
  
  // implements Message ----------------------------------------------
  
  ProtoCSGetFriendsResp* New() const;
  void CopyFrom(const ::google::protobuf::Message& from);
  void MergeFrom(const ::google::protobuf::Message& from);
  void CopyFrom(const ProtoCSGetFriendsResp& from);
  void MergeFrom(const ProtoCSGetFriendsResp& from);
  void Clear();
  bool IsInitialized() const;
  
  int ByteSize() const;
  bool MergePartialFromCodedStream(
      ::google::protobuf::io::CodedInputStream* input);
  void SerializeWithCachedSizes(
      ::google::protobuf::io::CodedOutputStream* output) const;
  ::google::protobuf::uint8* SerializeWithCachedSizesToArray(::google::protobuf::uint8* output) const;
  int GetCachedSize() const { return _cached_size_; }
  private:
  void SharedCtor();
  void SharedDtor();
  void SetCachedSize(int size) const;
  public:
  
  ::google::protobuf::Metadata GetMetadata() const;
  
  // nested types ----------------------------------------------------
  
  // accessors -------------------------------------------------------
  
  // required uint32 myuid = 1;
  inline bool has_myuid() const;
  inline void clear_myuid();
  static const int kMyuidFieldNumber = 1;
  inline ::google::protobuf::uint32 myuid() const;
  inline void set_myuid(::google::protobuf::uint32 value);
  
  // repeated .ProtoFriend.RecommendInfo info = 2;
  inline int info_size() const;
  inline void clear_info();
  static const int kInfoFieldNumber = 2;
  inline const ::ProtoFriend::RecommendInfo& info(int index) const;
  inline ::ProtoFriend::RecommendInfo* mutable_info(int index);
  inline ::ProtoFriend::RecommendInfo* add_info();
  inline const ::google::protobuf::RepeatedPtrField< ::ProtoFriend::RecommendInfo >&
      info() const;
  inline ::google::protobuf::RepeatedPtrField< ::ProtoFriend::RecommendInfo >*
      mutable_info();
  
  // @@protoc_insertion_point(class_scope:ProtoFriend.ProtoCSGetFriendsResp)
 private:
  inline void set_has_myuid();
  inline void clear_has_myuid();
  
  ::google::protobuf::UnknownFieldSet _unknown_fields_;
  
  ::google::protobuf::RepeatedPtrField< ::ProtoFriend::RecommendInfo > info_;
  ::google::protobuf::uint32 myuid_;
  
  mutable int _cached_size_;
  ::google::protobuf::uint32 _has_bits_[(2 + 31) / 32];
  
  friend void  protobuf_AddDesc_ProtoFriend_2eproto();
  friend void protobuf_AssignDesc_ProtoFriend_2eproto();
  friend void protobuf_ShutdownFile_ProtoFriend_2eproto();
  
  void InitAsDefaultInstance();
  static ProtoCSGetFriendsResp* default_instance_;
};
// -------------------------------------------------------------------

class ProtoConcernReq : public ::google::protobuf::Message {
 public:
  ProtoConcernReq();
  virtual ~ProtoConcernReq();
  
  ProtoConcernReq(const ProtoConcernReq& from);
  
  inline ProtoConcernReq& operator=(const ProtoConcernReq& from) {
    CopyFrom(from);
    return *this;
  }
  
  inline const ::google::protobuf::UnknownFieldSet& unknown_fields() const {
    return _unknown_fields_;
  }
  
  inline ::google::protobuf::UnknownFieldSet* mutable_unknown_fields() {
    return &_unknown_fields_;
  }
  
  static const ::google::protobuf::Descriptor* descriptor();
  static const ProtoConcernReq& default_instance();
  
  void Swap(ProtoConcernReq* other);
  
  // implements Message ----------------------------------------------
  
  ProtoConcernReq* New() const;
  void CopyFrom(const ::google::protobuf::Message& from);
  void MergeFrom(const ::google::protobuf::Message& from);
  void CopyFrom(const ProtoConcernReq& from);
  void MergeFrom(const ProtoConcernReq& from);
  void Clear();
  bool IsInitialized() const;
  
  int ByteSize() const;
  bool MergePartialFromCodedStream(
      ::google::protobuf::io::CodedInputStream* input);
  void SerializeWithCachedSizes(
      ::google::protobuf::io::CodedOutputStream* output) const;
  ::google::protobuf::uint8* SerializeWithCachedSizesToArray(::google::protobuf::uint8* output) const;
  int GetCachedSize() const { return _cached_size_; }
  private:
  void SharedCtor();
  void SharedDtor();
  void SetCachedSize(int size) const;
  public:
  
  ::google::protobuf::Metadata GetMetadata() const;
  
  // nested types ----------------------------------------------------
  
  // accessors -------------------------------------------------------
  
  // required uint32 otherId = 1;
  inline bool has_otherid() const;
  inline void clear_otherid();
  static const int kOtherIdFieldNumber = 1;
  inline ::google::protobuf::uint32 otherid() const;
  inline void set_otherid(::google::protobuf::uint32 value);
  
  // @@protoc_insertion_point(class_scope:ProtoFriend.ProtoConcernReq)
 private:
  inline void set_has_otherid();
  inline void clear_has_otherid();
  
  ::google::protobuf::UnknownFieldSet _unknown_fields_;
  
  ::google::protobuf::uint32 otherid_;
  
  mutable int _cached_size_;
  ::google::protobuf::uint32 _has_bits_[(1 + 31) / 32];
  
  friend void  protobuf_AddDesc_ProtoFriend_2eproto();
  friend void protobuf_AssignDesc_ProtoFriend_2eproto();
  friend void protobuf_ShutdownFile_ProtoFriend_2eproto();
  
  void InitAsDefaultInstance();
  static ProtoConcernReq* default_instance_;
};
// -------------------------------------------------------------------

class ProtoConcernResp : public ::google::protobuf::Message {
 public:
  ProtoConcernResp();
  virtual ~ProtoConcernResp();
  
  ProtoConcernResp(const ProtoConcernResp& from);
  
  inline ProtoConcernResp& operator=(const ProtoConcernResp& from) {
    CopyFrom(from);
    return *this;
  }
  
  inline const ::google::protobuf::UnknownFieldSet& unknown_fields() const {
    return _unknown_fields_;
  }
  
  inline ::google::protobuf::UnknownFieldSet* mutable_unknown_fields() {
    return &_unknown_fields_;
  }
  
  static const ::google::protobuf::Descriptor* descriptor();
  static const ProtoConcernResp& default_instance();
  
  void Swap(ProtoConcernResp* other);
  
  // implements Message ----------------------------------------------
  
  ProtoConcernResp* New() const;
  void CopyFrom(const ::google::protobuf::Message& from);
  void MergeFrom(const ::google::protobuf::Message& from);
  void CopyFrom(const ProtoConcernResp& from);
  void MergeFrom(const ProtoConcernResp& from);
  void Clear();
  bool IsInitialized() const;
  
  int ByteSize() const;
  bool MergePartialFromCodedStream(
      ::google::protobuf::io::CodedInputStream* input);
  void SerializeWithCachedSizes(
      ::google::protobuf::io::CodedOutputStream* output) const;
  ::google::protobuf::uint8* SerializeWithCachedSizesToArray(::google::protobuf::uint8* output) const;
  int GetCachedSize() const { return _cached_size_; }
  private:
  void SharedCtor();
  void SharedDtor();
  void SetCachedSize(int size) const;
  public:
  
  ::google::protobuf::Metadata GetMetadata() const;
  
  // nested types ----------------------------------------------------
  
  // accessors -------------------------------------------------------
  
  // optional .ProtoFriend.RecommendInfo info = 1;
  inline bool has_info() const;
  inline void clear_info();
  static const int kInfoFieldNumber = 1;
  inline const ::ProtoFriend::RecommendInfo& info() const;
  inline ::ProtoFriend::RecommendInfo* mutable_info();
  inline ::ProtoFriend::RecommendInfo* release_info();
  
  // @@protoc_insertion_point(class_scope:ProtoFriend.ProtoConcernResp)
 private:
  inline void set_has_info();
  inline void clear_has_info();
  
  ::google::protobuf::UnknownFieldSet _unknown_fields_;
  
  ::ProtoFriend::RecommendInfo* info_;
  
  mutable int _cached_size_;
  ::google::protobuf::uint32 _has_bits_[(1 + 31) / 32];
  
  friend void  protobuf_AddDesc_ProtoFriend_2eproto();
  friend void protobuf_AssignDesc_ProtoFriend_2eproto();
  friend void protobuf_ShutdownFile_ProtoFriend_2eproto();
  
  void InitAsDefaultInstance();
  static ProtoConcernResp* default_instance_;
};
// -------------------------------------------------------------------

class ProtoCSConcernReq : public ::google::protobuf::Message {
 public:
  ProtoCSConcernReq();
  virtual ~ProtoCSConcernReq();
  
  ProtoCSConcernReq(const ProtoCSConcernReq& from);
  
  inline ProtoCSConcernReq& operator=(const ProtoCSConcernReq& from) {
    CopyFrom(from);
    return *this;
  }
  
  inline const ::google::protobuf::UnknownFieldSet& unknown_fields() const {
    return _unknown_fields_;
  }
  
  inline ::google::protobuf::UnknownFieldSet* mutable_unknown_fields() {
    return &_unknown_fields_;
  }
  
  static const ::google::protobuf::Descriptor* descriptor();
  static const ProtoCSConcernReq& default_instance();
  
  void Swap(ProtoCSConcernReq* other);
  
  // implements Message ----------------------------------------------
  
  ProtoCSConcernReq* New() const;
  void CopyFrom(const ::google::protobuf::Message& from);
  void MergeFrom(const ::google::protobuf::Message& from);
  void CopyFrom(const ProtoCSConcernReq& from);
  void MergeFrom(const ProtoCSConcernReq& from);
  void Clear();
  bool IsInitialized() const;
  
  int ByteSize() const;
  bool MergePartialFromCodedStream(
      ::google::protobuf::io::CodedInputStream* input);
  void SerializeWithCachedSizes(
      ::google::protobuf::io::CodedOutputStream* output) const;
  ::google::protobuf::uint8* SerializeWithCachedSizesToArray(::google::protobuf::uint8* output) const;
  int GetCachedSize() const { return _cached_size_; }
  private:
  void SharedCtor();
  void SharedDtor();
  void SetCachedSize(int size) const;
  public:
  
  ::google::protobuf::Metadata GetMetadata() const;
  
  // nested types ----------------------------------------------------
  
  // accessors -------------------------------------------------------
  
  // required uint32 myuid = 1;
  inline bool has_myuid() const;
  inline void clear_myuid();
  static const int kMyuidFieldNumber = 1;
  inline ::google::protobuf::uint32 myuid() const;
  inline void set_myuid(::google::protobuf::uint32 value);
  
  // required uint32 othuid = 2;
  inline bool has_othuid() const;
  inline void clear_othuid();
  static const int kOthuidFieldNumber = 2;
  inline ::google::protobuf::uint32 othuid() const;
  inline void set_othuid(::google::protobuf::uint32 value);
  
  // @@protoc_insertion_point(class_scope:ProtoFriend.ProtoCSConcernReq)
 private:
  inline void set_has_myuid();
  inline void clear_has_myuid();
  inline void set_has_othuid();
  inline void clear_has_othuid();
  
  ::google::protobuf::UnknownFieldSet _unknown_fields_;
  
  ::google::protobuf::uint32 myuid_;
  ::google::protobuf::uint32 othuid_;
  
  mutable int _cached_size_;
  ::google::protobuf::uint32 _has_bits_[(2 + 31) / 32];
  
  friend void  protobuf_AddDesc_ProtoFriend_2eproto();
  friend void protobuf_AssignDesc_ProtoFriend_2eproto();
  friend void protobuf_ShutdownFile_ProtoFriend_2eproto();
  
  void InitAsDefaultInstance();
  static ProtoCSConcernReq* default_instance_;
};
// -------------------------------------------------------------------

class ProtoCSConcernResp : public ::google::protobuf::Message {
 public:
  ProtoCSConcernResp();
  virtual ~ProtoCSConcernResp();
  
  ProtoCSConcernResp(const ProtoCSConcernResp& from);
  
  inline ProtoCSConcernResp& operator=(const ProtoCSConcernResp& from) {
    CopyFrom(from);
    return *this;
  }
  
  inline const ::google::protobuf::UnknownFieldSet& unknown_fields() const {
    return _unknown_fields_;
  }
  
  inline ::google::protobuf::UnknownFieldSet* mutable_unknown_fields() {
    return &_unknown_fields_;
  }
  
  static const ::google::protobuf::Descriptor* descriptor();
  static const ProtoCSConcernResp& default_instance();
  
  void Swap(ProtoCSConcernResp* other);
  
  // implements Message ----------------------------------------------
  
  ProtoCSConcernResp* New() const;
  void CopyFrom(const ::google::protobuf::Message& from);
  void MergeFrom(const ::google::protobuf::Message& from);
  void CopyFrom(const ProtoCSConcernResp& from);
  void MergeFrom(const ProtoCSConcernResp& from);
  void Clear();
  bool IsInitialized() const;
  
  int ByteSize() const;
  bool MergePartialFromCodedStream(
      ::google::protobuf::io::CodedInputStream* input);
  void SerializeWithCachedSizes(
      ::google::protobuf::io::CodedOutputStream* output) const;
  ::google::protobuf::uint8* SerializeWithCachedSizesToArray(::google::protobuf::uint8* output) const;
  int GetCachedSize() const { return _cached_size_; }
  private:
  void SharedCtor();
  void SharedDtor();
  void SetCachedSize(int size) const;
  public:
  
  ::google::protobuf::Metadata GetMetadata() const;
  
  // nested types ----------------------------------------------------
  
  // accessors -------------------------------------------------------
  
  // required uint32 myuid = 1;
  inline bool has_myuid() const;
  inline void clear_myuid();
  static const int kMyuidFieldNumber = 1;
  inline ::google::protobuf::uint32 myuid() const;
  inline void set_myuid(::google::protobuf::uint32 value);
  
  // required .ProtoFriend.RecommendInfo info = 2;
  inline bool has_info() const;
  inline void clear_info();
  static const int kInfoFieldNumber = 2;
  inline const ::ProtoFriend::RecommendInfo& info() const;
  inline ::ProtoFriend::RecommendInfo* mutable_info();
  inline ::ProtoFriend::RecommendInfo* release_info();
  
  // @@protoc_insertion_point(class_scope:ProtoFriend.ProtoCSConcernResp)
 private:
  inline void set_has_myuid();
  inline void clear_has_myuid();
  inline void set_has_info();
  inline void clear_has_info();
  
  ::google::protobuf::UnknownFieldSet _unknown_fields_;
  
  ::ProtoFriend::RecommendInfo* info_;
  ::google::protobuf::uint32 myuid_;
  
  mutable int _cached_size_;
  ::google::protobuf::uint32 _has_bits_[(2 + 31) / 32];
  
  friend void  protobuf_AddDesc_ProtoFriend_2eproto();
  friend void protobuf_AssignDesc_ProtoFriend_2eproto();
  friend void protobuf_ShutdownFile_ProtoFriend_2eproto();
  
  void InitAsDefaultInstance();
  static ProtoCSConcernResp* default_instance_;
};
// -------------------------------------------------------------------

class ProtoCancelConcernReq : public ::google::protobuf::Message {
 public:
  ProtoCancelConcernReq();
  virtual ~ProtoCancelConcernReq();
  
  ProtoCancelConcernReq(const ProtoCancelConcernReq& from);
  
  inline ProtoCancelConcernReq& operator=(const ProtoCancelConcernReq& from) {
    CopyFrom(from);
    return *this;
  }
  
  inline const ::google::protobuf::UnknownFieldSet& unknown_fields() const {
    return _unknown_fields_;
  }
  
  inline ::google::protobuf::UnknownFieldSet* mutable_unknown_fields() {
    return &_unknown_fields_;
  }
  
  static const ::google::protobuf::Descriptor* descriptor();
  static const ProtoCancelConcernReq& default_instance();
  
  void Swap(ProtoCancelConcernReq* other);
  
  // implements Message ----------------------------------------------
  
  ProtoCancelConcernReq* New() const;
  void CopyFrom(const ::google::protobuf::Message& from);
  void MergeFrom(const ::google::protobuf::Message& from);
  void CopyFrom(const ProtoCancelConcernReq& from);
  void MergeFrom(const ProtoCancelConcernReq& from);
  void Clear();
  bool IsInitialized() const;
  
  int ByteSize() const;
  bool MergePartialFromCodedStream(
      ::google::protobuf::io::CodedInputStream* input);
  void SerializeWithCachedSizes(
      ::google::protobuf::io::CodedOutputStream* output) const;
  ::google::protobuf::uint8* SerializeWithCachedSizesToArray(::google::protobuf::uint8* output) const;
  int GetCachedSize() const { return _cached_size_; }
  private:
  void SharedCtor();
  void SharedDtor();
  void SetCachedSize(int size) const;
  public:
  
  ::google::protobuf::Metadata GetMetadata() const;
  
  // nested types ----------------------------------------------------
  
  // accessors -------------------------------------------------------
  
  // required uint32 otherId = 1;
  inline bool has_otherid() const;
  inline void clear_otherid();
  static const int kOtherIdFieldNumber = 1;
  inline ::google::protobuf::uint32 otherid() const;
  inline void set_otherid(::google::protobuf::uint32 value);
  
  // @@protoc_insertion_point(class_scope:ProtoFriend.ProtoCancelConcernReq)
 private:
  inline void set_has_otherid();
  inline void clear_has_otherid();
  
  ::google::protobuf::UnknownFieldSet _unknown_fields_;
  
  ::google::protobuf::uint32 otherid_;
  
  mutable int _cached_size_;
  ::google::protobuf::uint32 _has_bits_[(1 + 31) / 32];
  
  friend void  protobuf_AddDesc_ProtoFriend_2eproto();
  friend void protobuf_AssignDesc_ProtoFriend_2eproto();
  friend void protobuf_ShutdownFile_ProtoFriend_2eproto();
  
  void InitAsDefaultInstance();
  static ProtoCancelConcernReq* default_instance_;
};
// -------------------------------------------------------------------

class ProtoDonatePowerReq : public ::google::protobuf::Message {
 public:
  ProtoDonatePowerReq();
  virtual ~ProtoDonatePowerReq();
  
  ProtoDonatePowerReq(const ProtoDonatePowerReq& from);
  
  inline ProtoDonatePowerReq& operator=(const ProtoDonatePowerReq& from) {
    CopyFrom(from);
    return *this;
  }
  
  inline const ::google::protobuf::UnknownFieldSet& unknown_fields() const {
    return _unknown_fields_;
  }
  
  inline ::google::protobuf::UnknownFieldSet* mutable_unknown_fields() {
    return &_unknown_fields_;
  }
  
  static const ::google::protobuf::Descriptor* descriptor();
  static const ProtoDonatePowerReq& default_instance();
  
  void Swap(ProtoDonatePowerReq* other);
  
  // implements Message ----------------------------------------------
  
  ProtoDonatePowerReq* New() const;
  void CopyFrom(const ::google::protobuf::Message& from);
  void MergeFrom(const ::google::protobuf::Message& from);
  void CopyFrom(const ProtoDonatePowerReq& from);
  void MergeFrom(const ProtoDonatePowerReq& from);
  void Clear();
  bool IsInitialized() const;
  
  int ByteSize() const;
  bool MergePartialFromCodedStream(
      ::google::protobuf::io::CodedInputStream* input);
  void SerializeWithCachedSizes(
      ::google::protobuf::io::CodedOutputStream* output) const;
  ::google::protobuf::uint8* SerializeWithCachedSizesToArray(::google::protobuf::uint8* output) const;
  int GetCachedSize() const { return _cached_size_; }
  private:
  void SharedCtor();
  void SharedDtor();
  void SetCachedSize(int size) const;
  public:
  
  ::google::protobuf::Metadata GetMetadata() const;
  
  // nested types ----------------------------------------------------
  
  // accessors -------------------------------------------------------
  
  // required uint32 ts = 1;
  inline bool has_ts() const;
  inline void clear_ts();
  static const int kTsFieldNumber = 1;
  inline ::google::protobuf::uint32 ts() const;
  inline void set_ts(::google::protobuf::uint32 value);
  
  // required uint32 otherId = 2;
  inline bool has_otherid() const;
  inline void clear_otherid();
  static const int kOtherIdFieldNumber = 2;
  inline ::google::protobuf::uint32 otherid() const;
  inline void set_otherid(::google::protobuf::uint32 value);
  
  // @@protoc_insertion_point(class_scope:ProtoFriend.ProtoDonatePowerReq)
 private:
  inline void set_has_ts();
  inline void clear_has_ts();
  inline void set_has_otherid();
  inline void clear_has_otherid();
  
  ::google::protobuf::UnknownFieldSet _unknown_fields_;
  
  ::google::protobuf::uint32 ts_;
  ::google::protobuf::uint32 otherid_;
  
  mutable int _cached_size_;
  ::google::protobuf::uint32 _has_bits_[(2 + 31) / 32];
  
  friend void  protobuf_AddDesc_ProtoFriend_2eproto();
  friend void protobuf_AssignDesc_ProtoFriend_2eproto();
  friend void protobuf_ShutdownFile_ProtoFriend_2eproto();
  
  void InitAsDefaultInstance();
  static ProtoDonatePowerReq* default_instance_;
};
// -------------------------------------------------------------------

class ProtoDonatePowerResp : public ::google::protobuf::Message {
 public:
  ProtoDonatePowerResp();
  virtual ~ProtoDonatePowerResp();
  
  ProtoDonatePowerResp(const ProtoDonatePowerResp& from);
  
  inline ProtoDonatePowerResp& operator=(const ProtoDonatePowerResp& from) {
    CopyFrom(from);
    return *this;
  }
  
  inline const ::google::protobuf::UnknownFieldSet& unknown_fields() const {
    return _unknown_fields_;
  }
  
  inline ::google::protobuf::UnknownFieldSet* mutable_unknown_fields() {
    return &_unknown_fields_;
  }
  
  static const ::google::protobuf::Descriptor* descriptor();
  static const ProtoDonatePowerResp& default_instance();
  
  void Swap(ProtoDonatePowerResp* other);
  
  // implements Message ----------------------------------------------
  
  ProtoDonatePowerResp* New() const;
  void CopyFrom(const ::google::protobuf::Message& from);
  void MergeFrom(const ::google::protobuf::Message& from);
  void CopyFrom(const ProtoDonatePowerResp& from);
  void MergeFrom(const ProtoDonatePowerResp& from);
  void Clear();
  bool IsInitialized() const;
  
  int ByteSize() const;
  bool MergePartialFromCodedStream(
      ::google::protobuf::io::CodedInputStream* input);
  void SerializeWithCachedSizes(
      ::google::protobuf::io::CodedOutputStream* output) const;
  ::google::protobuf::uint8* SerializeWithCachedSizesToArray(::google::protobuf::uint8* output) const;
  int GetCachedSize() const { return _cached_size_; }
  private:
  void SharedCtor();
  void SharedDtor();
  void SetCachedSize(int size) const;
  public:
  
  ::google::protobuf::Metadata GetMetadata() const;
  
  // nested types ----------------------------------------------------
  
  // accessors -------------------------------------------------------
  
  // optional .DataCommon.CommonItemsCPP commons = 1;
  inline bool has_commons() const;
  inline void clear_commons();
  static const int kCommonsFieldNumber = 1;
  inline const ::DataCommon::CommonItemsCPP& commons() const;
  inline ::DataCommon::CommonItemsCPP* mutable_commons();
  inline ::DataCommon::CommonItemsCPP* release_commons();
  
  // @@protoc_insertion_point(class_scope:ProtoFriend.ProtoDonatePowerResp)
 private:
  inline void set_has_commons();
  inline void clear_has_commons();
  
  ::google::protobuf::UnknownFieldSet _unknown_fields_;
  
  ::DataCommon::CommonItemsCPP* commons_;
  
  mutable int _cached_size_;
  ::google::protobuf::uint32 _has_bits_[(1 + 31) / 32];
  
  friend void  protobuf_AddDesc_ProtoFriend_2eproto();
  friend void protobuf_AssignDesc_ProtoFriend_2eproto();
  friend void protobuf_ShutdownFile_ProtoFriend_2eproto();
  
  void InitAsDefaultInstance();
  static ProtoDonatePowerResp* default_instance_;
};
// -------------------------------------------------------------------

class ProtoCSDonatePowerReq : public ::google::protobuf::Message {
 public:
  ProtoCSDonatePowerReq();
  virtual ~ProtoCSDonatePowerReq();
  
  ProtoCSDonatePowerReq(const ProtoCSDonatePowerReq& from);
  
  inline ProtoCSDonatePowerReq& operator=(const ProtoCSDonatePowerReq& from) {
    CopyFrom(from);
    return *this;
  }
  
  inline const ::google::protobuf::UnknownFieldSet& unknown_fields() const {
    return _unknown_fields_;
  }
  
  inline ::google::protobuf::UnknownFieldSet* mutable_unknown_fields() {
    return &_unknown_fields_;
  }
  
  static const ::google::protobuf::Descriptor* descriptor();
  static const ProtoCSDonatePowerReq& default_instance();
  
  void Swap(ProtoCSDonatePowerReq* other);
  
  // implements Message ----------------------------------------------
  
  ProtoCSDonatePowerReq* New() const;
  void CopyFrom(const ::google::protobuf::Message& from);
  void MergeFrom(const ::google::protobuf::Message& from);
  void CopyFrom(const ProtoCSDonatePowerReq& from);
  void MergeFrom(const ProtoCSDonatePowerReq& from);
  void Clear();
  bool IsInitialized() const;
  
  int ByteSize() const;
  bool MergePartialFromCodedStream(
      ::google::protobuf::io::CodedInputStream* input);
  void SerializeWithCachedSizes(
      ::google::protobuf::io::CodedOutputStream* output) const;
  ::google::protobuf::uint8* SerializeWithCachedSizesToArray(::google::protobuf::uint8* output) const;
  int GetCachedSize() const { return _cached_size_; }
  private:
  void SharedCtor();
  void SharedDtor();
  void SetCachedSize(int size) const;
  public:
  
  ::google::protobuf::Metadata GetMetadata() const;
  
  // nested types ----------------------------------------------------
  
  // accessors -------------------------------------------------------
  
  // required uint32 othuid = 1;
  inline bool has_othuid() const;
  inline void clear_othuid();
  static const int kOthuidFieldNumber = 1;
  inline ::google::protobuf::uint32 othuid() const;
  inline void set_othuid(::google::protobuf::uint32 value);
  
  // @@protoc_insertion_point(class_scope:ProtoFriend.ProtoCSDonatePowerReq)
 private:
  inline void set_has_othuid();
  inline void clear_has_othuid();
  
  ::google::protobuf::UnknownFieldSet _unknown_fields_;
  
  ::google::protobuf::uint32 othuid_;
  
  mutable int _cached_size_;
  ::google::protobuf::uint32 _has_bits_[(1 + 31) / 32];
  
  friend void  protobuf_AddDesc_ProtoFriend_2eproto();
  friend void protobuf_AssignDesc_ProtoFriend_2eproto();
  friend void protobuf_ShutdownFile_ProtoFriend_2eproto();
  
  void InitAsDefaultInstance();
  static ProtoCSDonatePowerReq* default_instance_;
};
// ===================================================================


// ===================================================================

// RecommendInfo

// required uint32 uid = 1;
inline bool RecommendInfo::has_uid() const {
  return (_has_bits_[0] & 0x00000001u) != 0;
}
inline void RecommendInfo::set_has_uid() {
  _has_bits_[0] |= 0x00000001u;
}
inline void RecommendInfo::clear_has_uid() {
  _has_bits_[0] &= ~0x00000001u;
}
inline void RecommendInfo::clear_uid() {
  uid_ = 0u;
  clear_has_uid();
}
inline ::google::protobuf::uint32 RecommendInfo::uid() const {
  return uid_;
}
inline void RecommendInfo::set_uid(::google::protobuf::uint32 value) {
  set_has_uid();
  uid_ = value;
}

// required string name = 2;
inline bool RecommendInfo::has_name() const {
  return (_has_bits_[0] & 0x00000002u) != 0;
}
inline void RecommendInfo::set_has_name() {
  _has_bits_[0] |= 0x00000002u;
}
inline void RecommendInfo::clear_has_name() {
  _has_bits_[0] &= ~0x00000002u;
}
inline void RecommendInfo::clear_name() {
  if (name_ != &::google::protobuf::internal::kEmptyString) {
    name_->clear();
  }
  clear_has_name();
}
inline const ::std::string& RecommendInfo::name() const {
  return *name_;
}
inline void RecommendInfo::set_name(const ::std::string& value) {
  set_has_name();
  if (name_ == &::google::protobuf::internal::kEmptyString) {
    name_ = new ::std::string;
  }
  name_->assign(value);
}
inline void RecommendInfo::set_name(const char* value) {
  set_has_name();
  if (name_ == &::google::protobuf::internal::kEmptyString) {
    name_ = new ::std::string;
  }
  name_->assign(value);
}
inline void RecommendInfo::set_name(const char* value, size_t size) {
  set_has_name();
  if (name_ == &::google::protobuf::internal::kEmptyString) {
    name_ = new ::std::string;
  }
  name_->assign(reinterpret_cast<const char*>(value), size);
}
inline ::std::string* RecommendInfo::mutable_name() {
  set_has_name();
  if (name_ == &::google::protobuf::internal::kEmptyString) {
    name_ = new ::std::string;
  }
  return name_;
}
inline ::std::string* RecommendInfo::release_name() {
  clear_has_name();
  if (name_ == &::google::protobuf::internal::kEmptyString) {
    return NULL;
  } else {
    ::std::string* temp = name_;
    name_ = const_cast< ::std::string*>(&::google::protobuf::internal::kEmptyString);
    return temp;
  }
}

// required string fig = 3;
inline bool RecommendInfo::has_fig() const {
  return (_has_bits_[0] & 0x00000004u) != 0;
}
inline void RecommendInfo::set_has_fig() {
  _has_bits_[0] |= 0x00000004u;
}
inline void RecommendInfo::clear_has_fig() {
  _has_bits_[0] &= ~0x00000004u;
}
inline void RecommendInfo::clear_fig() {
  if (fig_ != &::google::protobuf::internal::kEmptyString) {
    fig_->clear();
  }
  clear_has_fig();
}
inline const ::std::string& RecommendInfo::fig() const {
  return *fig_;
}
inline void RecommendInfo::set_fig(const ::std::string& value) {
  set_has_fig();
  if (fig_ == &::google::protobuf::internal::kEmptyString) {
    fig_ = new ::std::string;
  }
  fig_->assign(value);
}
inline void RecommendInfo::set_fig(const char* value) {
  set_has_fig();
  if (fig_ == &::google::protobuf::internal::kEmptyString) {
    fig_ = new ::std::string;
  }
  fig_->assign(value);
}
inline void RecommendInfo::set_fig(const char* value, size_t size) {
  set_has_fig();
  if (fig_ == &::google::protobuf::internal::kEmptyString) {
    fig_ = new ::std::string;
  }
  fig_->assign(reinterpret_cast<const char*>(value), size);
}
inline ::std::string* RecommendInfo::mutable_fig() {
  set_has_fig();
  if (fig_ == &::google::protobuf::internal::kEmptyString) {
    fig_ = new ::std::string;
  }
  return fig_;
}
inline ::std::string* RecommendInfo::release_fig() {
  clear_has_fig();
  if (fig_ == &::google::protobuf::internal::kEmptyString) {
    return NULL;
  } else {
    ::std::string* temp = fig_;
    fig_ = const_cast< ::std::string*>(&::google::protobuf::internal::kEmptyString);
    return temp;
  }
}

// required uint32 level = 4;
inline bool RecommendInfo::has_level() const {
  return (_has_bits_[0] & 0x00000008u) != 0;
}
inline void RecommendInfo::set_has_level() {
  _has_bits_[0] |= 0x00000008u;
}
inline void RecommendInfo::clear_has_level() {
  _has_bits_[0] &= ~0x00000008u;
}
inline void RecommendInfo::clear_level() {
  level_ = 0u;
  clear_has_level();
}
inline ::google::protobuf::uint32 RecommendInfo::level() const {
  return level_;
}
inline void RecommendInfo::set_level(::google::protobuf::uint32 value) {
  set_has_level();
  level_ = value;
}

// required uint32 grade = 5;
inline bool RecommendInfo::has_grade() const {
  return (_has_bits_[0] & 0x00000010u) != 0;
}
inline void RecommendInfo::set_has_grade() {
  _has_bits_[0] |= 0x00000010u;
}
inline void RecommendInfo::clear_has_grade() {
  _has_bits_[0] &= ~0x00000010u;
}
inline void RecommendInfo::clear_grade() {
  grade_ = 0u;
  clear_has_grade();
}
inline ::google::protobuf::uint32 RecommendInfo::grade() const {
  return grade_;
}
inline void RecommendInfo::set_grade(::google::protobuf::uint32 value) {
  set_has_grade();
  grade_ = value;
}

// optional uint32 onlineTs = 6;
inline bool RecommendInfo::has_onlinets() const {
  return (_has_bits_[0] & 0x00000020u) != 0;
}
inline void RecommendInfo::set_has_onlinets() {
  _has_bits_[0] |= 0x00000020u;
}
inline void RecommendInfo::clear_has_onlinets() {
  _has_bits_[0] &= ~0x00000020u;
}
inline void RecommendInfo::clear_onlinets() {
  onlinets_ = 0u;
  clear_has_onlinets();
}
inline ::google::protobuf::uint32 RecommendInfo::onlinets() const {
  return onlinets_;
}
inline void RecommendInfo::set_onlinets(::google::protobuf::uint32 value) {
  set_has_onlinets();
  onlinets_ = value;
}

// optional uint32 donationTs = 7;
inline bool RecommendInfo::has_donationts() const {
  return (_has_bits_[0] & 0x00000040u) != 0;
}
inline void RecommendInfo::set_has_donationts() {
  _has_bits_[0] |= 0x00000040u;
}
inline void RecommendInfo::clear_has_donationts() {
  _has_bits_[0] &= ~0x00000040u;
}
inline void RecommendInfo::clear_donationts() {
  donationts_ = 0u;
  clear_has_donationts();
}
inline ::google::protobuf::uint32 RecommendInfo::donationts() const {
  return donationts_;
}
inline void RecommendInfo::set_donationts(::google::protobuf::uint32 value) {
  set_has_donationts();
  donationts_ = value;
}

// optional uint32 battleTs = 8;
inline bool RecommendInfo::has_battlets() const {
  return (_has_bits_[0] & 0x00000080u) != 0;
}
inline void RecommendInfo::set_has_battlets() {
  _has_bits_[0] |= 0x00000080u;
}
inline void RecommendInfo::clear_has_battlets() {
  _has_bits_[0] &= ~0x00000080u;
}
inline void RecommendInfo::clear_battlets() {
  battlets_ = 0u;
  clear_has_battlets();
}
inline ::google::protobuf::uint32 RecommendInfo::battlets() const {
  return battlets_;
}
inline void RecommendInfo::set_battlets(::google::protobuf::uint32 value) {
  set_has_battlets();
  battlets_ = value;
}

// optional uint32 battle = 9;
inline bool RecommendInfo::has_battle() const {
  return (_has_bits_[0] & 0x00000100u) != 0;
}
inline void RecommendInfo::set_has_battle() {
  _has_bits_[0] |= 0x00000100u;
}
inline void RecommendInfo::clear_has_battle() {
  _has_bits_[0] &= ~0x00000100u;
}
inline void RecommendInfo::clear_battle() {
  battle_ = 0u;
  clear_has_battle();
}
inline ::google::protobuf::uint32 RecommendInfo::battle() const {
  return battle_;
}
inline void RecommendInfo::set_battle(::google::protobuf::uint32 value) {
  set_has_battle();
  battle_ = value;
}

// repeated uint32 heroId = 10;
inline int RecommendInfo::heroid_size() const {
  return heroid_.size();
}
inline void RecommendInfo::clear_heroid() {
  heroid_.Clear();
}
inline ::google::protobuf::uint32 RecommendInfo::heroid(int index) const {
  return heroid_.Get(index);
}
inline void RecommendInfo::set_heroid(int index, ::google::protobuf::uint32 value) {
  heroid_.Set(index, value);
}
inline void RecommendInfo::add_heroid(::google::protobuf::uint32 value) {
  heroid_.Add(value);
}
inline const ::google::protobuf::RepeatedField< ::google::protobuf::uint32 >&
RecommendInfo::heroid() const {
  return heroid_;
}
inline ::google::protobuf::RepeatedField< ::google::protobuf::uint32 >*
RecommendInfo::mutable_heroid() {
  return &heroid_;
}

// -------------------------------------------------------------------

// ProtoRecommendUserReq

// -------------------------------------------------------------------

// ProtoRecommendUserResp

// repeated .ProtoFriend.RecommendInfo user = 1;
inline int ProtoRecommendUserResp::user_size() const {
  return user_.size();
}
inline void ProtoRecommendUserResp::clear_user() {
  user_.Clear();
}
inline const ::ProtoFriend::RecommendInfo& ProtoRecommendUserResp::user(int index) const {
  return user_.Get(index);
}
inline ::ProtoFriend::RecommendInfo* ProtoRecommendUserResp::mutable_user(int index) {
  return user_.Mutable(index);
}
inline ::ProtoFriend::RecommendInfo* ProtoRecommendUserResp::add_user() {
  return user_.Add();
}
inline const ::google::protobuf::RepeatedPtrField< ::ProtoFriend::RecommendInfo >&
ProtoRecommendUserResp::user() const {
  return user_;
}
inline ::google::protobuf::RepeatedPtrField< ::ProtoFriend::RecommendInfo >*
ProtoRecommendUserResp::mutable_user() {
  return &user_;
}

// -------------------------------------------------------------------

// ProtoGetFriendsReq

// -------------------------------------------------------------------

// ProtoGetFriendsResp

// repeated .ProtoFriend.RecommendInfo user = 1;
inline int ProtoGetFriendsResp::user_size() const {
  return user_.size();
}
inline void ProtoGetFriendsResp::clear_user() {
  user_.Clear();
}
inline const ::ProtoFriend::RecommendInfo& ProtoGetFriendsResp::user(int index) const {
  return user_.Get(index);
}
inline ::ProtoFriend::RecommendInfo* ProtoGetFriendsResp::mutable_user(int index) {
  return user_.Mutable(index);
}
inline ::ProtoFriend::RecommendInfo* ProtoGetFriendsResp::add_user() {
  return user_.Add();
}
inline const ::google::protobuf::RepeatedPtrField< ::ProtoFriend::RecommendInfo >&
ProtoGetFriendsResp::user() const {
  return user_;
}
inline ::google::protobuf::RepeatedPtrField< ::ProtoFriend::RecommendInfo >*
ProtoGetFriendsResp::mutable_user() {
  return &user_;
}

// -------------------------------------------------------------------

// ProtoCSGetFriendsReq

// required uint32 myuid = 1;
inline bool ProtoCSGetFriendsReq::has_myuid() const {
  return (_has_bits_[0] & 0x00000001u) != 0;
}
inline void ProtoCSGetFriendsReq::set_has_myuid() {
  _has_bits_[0] |= 0x00000001u;
}
inline void ProtoCSGetFriendsReq::clear_has_myuid() {
  _has_bits_[0] &= ~0x00000001u;
}
inline void ProtoCSGetFriendsReq::clear_myuid() {
  myuid_ = 0u;
  clear_has_myuid();
}
inline ::google::protobuf::uint32 ProtoCSGetFriendsReq::myuid() const {
  return myuid_;
}
inline void ProtoCSGetFriendsReq::set_myuid(::google::protobuf::uint32 value) {
  set_has_myuid();
  myuid_ = value;
}

// repeated uint32 othuid = 2;
inline int ProtoCSGetFriendsReq::othuid_size() const {
  return othuid_.size();
}
inline void ProtoCSGetFriendsReq::clear_othuid() {
  othuid_.Clear();
}
inline ::google::protobuf::uint32 ProtoCSGetFriendsReq::othuid(int index) const {
  return othuid_.Get(index);
}
inline void ProtoCSGetFriendsReq::set_othuid(int index, ::google::protobuf::uint32 value) {
  othuid_.Set(index, value);
}
inline void ProtoCSGetFriendsReq::add_othuid(::google::protobuf::uint32 value) {
  othuid_.Add(value);
}
inline const ::google::protobuf::RepeatedField< ::google::protobuf::uint32 >&
ProtoCSGetFriendsReq::othuid() const {
  return othuid_;
}
inline ::google::protobuf::RepeatedField< ::google::protobuf::uint32 >*
ProtoCSGetFriendsReq::mutable_othuid() {
  return &othuid_;
}

// -------------------------------------------------------------------

// ProtoCSGetFriendsResp

// required uint32 myuid = 1;
inline bool ProtoCSGetFriendsResp::has_myuid() const {
  return (_has_bits_[0] & 0x00000001u) != 0;
}
inline void ProtoCSGetFriendsResp::set_has_myuid() {
  _has_bits_[0] |= 0x00000001u;
}
inline void ProtoCSGetFriendsResp::clear_has_myuid() {
  _has_bits_[0] &= ~0x00000001u;
}
inline void ProtoCSGetFriendsResp::clear_myuid() {
  myuid_ = 0u;
  clear_has_myuid();
}
inline ::google::protobuf::uint32 ProtoCSGetFriendsResp::myuid() const {
  return myuid_;
}
inline void ProtoCSGetFriendsResp::set_myuid(::google::protobuf::uint32 value) {
  set_has_myuid();
  myuid_ = value;
}

// repeated .ProtoFriend.RecommendInfo info = 2;
inline int ProtoCSGetFriendsResp::info_size() const {
  return info_.size();
}
inline void ProtoCSGetFriendsResp::clear_info() {
  info_.Clear();
}
inline const ::ProtoFriend::RecommendInfo& ProtoCSGetFriendsResp::info(int index) const {
  return info_.Get(index);
}
inline ::ProtoFriend::RecommendInfo* ProtoCSGetFriendsResp::mutable_info(int index) {
  return info_.Mutable(index);
}
inline ::ProtoFriend::RecommendInfo* ProtoCSGetFriendsResp::add_info() {
  return info_.Add();
}
inline const ::google::protobuf::RepeatedPtrField< ::ProtoFriend::RecommendInfo >&
ProtoCSGetFriendsResp::info() const {
  return info_;
}
inline ::google::protobuf::RepeatedPtrField< ::ProtoFriend::RecommendInfo >*
ProtoCSGetFriendsResp::mutable_info() {
  return &info_;
}

// -------------------------------------------------------------------

// ProtoConcernReq

// required uint32 otherId = 1;
inline bool ProtoConcernReq::has_otherid() const {
  return (_has_bits_[0] & 0x00000001u) != 0;
}
inline void ProtoConcernReq::set_has_otherid() {
  _has_bits_[0] |= 0x00000001u;
}
inline void ProtoConcernReq::clear_has_otherid() {
  _has_bits_[0] &= ~0x00000001u;
}
inline void ProtoConcernReq::clear_otherid() {
  otherid_ = 0u;
  clear_has_otherid();
}
inline ::google::protobuf::uint32 ProtoConcernReq::otherid() const {
  return otherid_;
}
inline void ProtoConcernReq::set_otherid(::google::protobuf::uint32 value) {
  set_has_otherid();
  otherid_ = value;
}

// -------------------------------------------------------------------

// ProtoConcernResp

// optional .ProtoFriend.RecommendInfo info = 1;
inline bool ProtoConcernResp::has_info() const {
  return (_has_bits_[0] & 0x00000001u) != 0;
}
inline void ProtoConcernResp::set_has_info() {
  _has_bits_[0] |= 0x00000001u;
}
inline void ProtoConcernResp::clear_has_info() {
  _has_bits_[0] &= ~0x00000001u;
}
inline void ProtoConcernResp::clear_info() {
  if (info_ != NULL) info_->::ProtoFriend::RecommendInfo::Clear();
  clear_has_info();
}
inline const ::ProtoFriend::RecommendInfo& ProtoConcernResp::info() const {
  return info_ != NULL ? *info_ : *default_instance_->info_;
}
inline ::ProtoFriend::RecommendInfo* ProtoConcernResp::mutable_info() {
  set_has_info();
  if (info_ == NULL) info_ = new ::ProtoFriend::RecommendInfo;
  return info_;
}
inline ::ProtoFriend::RecommendInfo* ProtoConcernResp::release_info() {
  clear_has_info();
  ::ProtoFriend::RecommendInfo* temp = info_;
  info_ = NULL;
  return temp;
}

// -------------------------------------------------------------------

// ProtoCSConcernReq

// required uint32 myuid = 1;
inline bool ProtoCSConcernReq::has_myuid() const {
  return (_has_bits_[0] & 0x00000001u) != 0;
}
inline void ProtoCSConcernReq::set_has_myuid() {
  _has_bits_[0] |= 0x00000001u;
}
inline void ProtoCSConcernReq::clear_has_myuid() {
  _has_bits_[0] &= ~0x00000001u;
}
inline void ProtoCSConcernReq::clear_myuid() {
  myuid_ = 0u;
  clear_has_myuid();
}
inline ::google::protobuf::uint32 ProtoCSConcernReq::myuid() const {
  return myuid_;
}
inline void ProtoCSConcernReq::set_myuid(::google::protobuf::uint32 value) {
  set_has_myuid();
  myuid_ = value;
}

// required uint32 othuid = 2;
inline bool ProtoCSConcernReq::has_othuid() const {
  return (_has_bits_[0] & 0x00000002u) != 0;
}
inline void ProtoCSConcernReq::set_has_othuid() {
  _has_bits_[0] |= 0x00000002u;
}
inline void ProtoCSConcernReq::clear_has_othuid() {
  _has_bits_[0] &= ~0x00000002u;
}
inline void ProtoCSConcernReq::clear_othuid() {
  othuid_ = 0u;
  clear_has_othuid();
}
inline ::google::protobuf::uint32 ProtoCSConcernReq::othuid() const {
  return othuid_;
}
inline void ProtoCSConcernReq::set_othuid(::google::protobuf::uint32 value) {
  set_has_othuid();
  othuid_ = value;
}

// -------------------------------------------------------------------

// ProtoCSConcernResp

// required uint32 myuid = 1;
inline bool ProtoCSConcernResp::has_myuid() const {
  return (_has_bits_[0] & 0x00000001u) != 0;
}
inline void ProtoCSConcernResp::set_has_myuid() {
  _has_bits_[0] |= 0x00000001u;
}
inline void ProtoCSConcernResp::clear_has_myuid() {
  _has_bits_[0] &= ~0x00000001u;
}
inline void ProtoCSConcernResp::clear_myuid() {
  myuid_ = 0u;
  clear_has_myuid();
}
inline ::google::protobuf::uint32 ProtoCSConcernResp::myuid() const {
  return myuid_;
}
inline void ProtoCSConcernResp::set_myuid(::google::protobuf::uint32 value) {
  set_has_myuid();
  myuid_ = value;
}

// required .ProtoFriend.RecommendInfo info = 2;
inline bool ProtoCSConcernResp::has_info() const {
  return (_has_bits_[0] & 0x00000002u) != 0;
}
inline void ProtoCSConcernResp::set_has_info() {
  _has_bits_[0] |= 0x00000002u;
}
inline void ProtoCSConcernResp::clear_has_info() {
  _has_bits_[0] &= ~0x00000002u;
}
inline void ProtoCSConcernResp::clear_info() {
  if (info_ != NULL) info_->::ProtoFriend::RecommendInfo::Clear();
  clear_has_info();
}
inline const ::ProtoFriend::RecommendInfo& ProtoCSConcernResp::info() const {
  return info_ != NULL ? *info_ : *default_instance_->info_;
}
inline ::ProtoFriend::RecommendInfo* ProtoCSConcernResp::mutable_info() {
  set_has_info();
  if (info_ == NULL) info_ = new ::ProtoFriend::RecommendInfo;
  return info_;
}
inline ::ProtoFriend::RecommendInfo* ProtoCSConcernResp::release_info() {
  clear_has_info();
  ::ProtoFriend::RecommendInfo* temp = info_;
  info_ = NULL;
  return temp;
}

// -------------------------------------------------------------------

// ProtoCancelConcernReq

// required uint32 otherId = 1;
inline bool ProtoCancelConcernReq::has_otherid() const {
  return (_has_bits_[0] & 0x00000001u) != 0;
}
inline void ProtoCancelConcernReq::set_has_otherid() {
  _has_bits_[0] |= 0x00000001u;
}
inline void ProtoCancelConcernReq::clear_has_otherid() {
  _has_bits_[0] &= ~0x00000001u;
}
inline void ProtoCancelConcernReq::clear_otherid() {
  otherid_ = 0u;
  clear_has_otherid();
}
inline ::google::protobuf::uint32 ProtoCancelConcernReq::otherid() const {
  return otherid_;
}
inline void ProtoCancelConcernReq::set_otherid(::google::protobuf::uint32 value) {
  set_has_otherid();
  otherid_ = value;
}

// -------------------------------------------------------------------

// ProtoDonatePowerReq

// required uint32 ts = 1;
inline bool ProtoDonatePowerReq::has_ts() const {
  return (_has_bits_[0] & 0x00000001u) != 0;
}
inline void ProtoDonatePowerReq::set_has_ts() {
  _has_bits_[0] |= 0x00000001u;
}
inline void ProtoDonatePowerReq::clear_has_ts() {
  _has_bits_[0] &= ~0x00000001u;
}
inline void ProtoDonatePowerReq::clear_ts() {
  ts_ = 0u;
  clear_has_ts();
}
inline ::google::protobuf::uint32 ProtoDonatePowerReq::ts() const {
  return ts_;
}
inline void ProtoDonatePowerReq::set_ts(::google::protobuf::uint32 value) {
  set_has_ts();
  ts_ = value;
}

// required uint32 otherId = 2;
inline bool ProtoDonatePowerReq::has_otherid() const {
  return (_has_bits_[0] & 0x00000002u) != 0;
}
inline void ProtoDonatePowerReq::set_has_otherid() {
  _has_bits_[0] |= 0x00000002u;
}
inline void ProtoDonatePowerReq::clear_has_otherid() {
  _has_bits_[0] &= ~0x00000002u;
}
inline void ProtoDonatePowerReq::clear_otherid() {
  otherid_ = 0u;
  clear_has_otherid();
}
inline ::google::protobuf::uint32 ProtoDonatePowerReq::otherid() const {
  return otherid_;
}
inline void ProtoDonatePowerReq::set_otherid(::google::protobuf::uint32 value) {
  set_has_otherid();
  otherid_ = value;
}

// -------------------------------------------------------------------

// ProtoDonatePowerResp

// optional .DataCommon.CommonItemsCPP commons = 1;
inline bool ProtoDonatePowerResp::has_commons() const {
  return (_has_bits_[0] & 0x00000001u) != 0;
}
inline void ProtoDonatePowerResp::set_has_commons() {
  _has_bits_[0] |= 0x00000001u;
}
inline void ProtoDonatePowerResp::clear_has_commons() {
  _has_bits_[0] &= ~0x00000001u;
}
inline void ProtoDonatePowerResp::clear_commons() {
  if (commons_ != NULL) commons_->::DataCommon::CommonItemsCPP::Clear();
  clear_has_commons();
}
inline const ::DataCommon::CommonItemsCPP& ProtoDonatePowerResp::commons() const {
  return commons_ != NULL ? *commons_ : *default_instance_->commons_;
}
inline ::DataCommon::CommonItemsCPP* ProtoDonatePowerResp::mutable_commons() {
  set_has_commons();
  if (commons_ == NULL) commons_ = new ::DataCommon::CommonItemsCPP;
  return commons_;
}
inline ::DataCommon::CommonItemsCPP* ProtoDonatePowerResp::release_commons() {
  clear_has_commons();
  ::DataCommon::CommonItemsCPP* temp = commons_;
  commons_ = NULL;
  return temp;
}

// -------------------------------------------------------------------

// ProtoCSDonatePowerReq

// required uint32 othuid = 1;
inline bool ProtoCSDonatePowerReq::has_othuid() const {
  return (_has_bits_[0] & 0x00000001u) != 0;
}
inline void ProtoCSDonatePowerReq::set_has_othuid() {
  _has_bits_[0] |= 0x00000001u;
}
inline void ProtoCSDonatePowerReq::clear_has_othuid() {
  _has_bits_[0] &= ~0x00000001u;
}
inline void ProtoCSDonatePowerReq::clear_othuid() {
  othuid_ = 0u;
  clear_has_othuid();
}
inline ::google::protobuf::uint32 ProtoCSDonatePowerReq::othuid() const {
  return othuid_;
}
inline void ProtoCSDonatePowerReq::set_othuid(::google::protobuf::uint32 value) {
  set_has_othuid();
  othuid_ = value;
}


// @@protoc_insertion_point(namespace_scope)

}  // namespace ProtoFriend

#ifndef SWIG
namespace google {
namespace protobuf {


}  // namespace google
}  // namespace protobuf
#endif  // SWIG

// @@protoc_insertion_point(global_scope)

#endif  // PROTOBUF_ProtoFriend_2eproto__INCLUDED
